Product Gallery Large Image: Add the php experimental flag
woocommerce/woocommerce-gutenberg-products-block pull request #10158
Opened 2023-07-10 20:13 UTC by danieldudzic

Add PHP experimental flag to Product Gallery Large Image block

2023-07-11 21:31 UTC, thealexandrelara approved these changes
Nice! LGTM! ✅

2023-07-12 12:18 UTC, thealexandrelara requested changes
I just left a small comment about the PHP CS error that is being shown

2023-07-12 12:18 UTC, thealexandrelara commented on src/BlockTypesController.php
> +			$block_types[] = 'ProductGalleryLargeImage';
The indentation is incorrect in these lines

2023-07-13 22:28 UTC, danieldudzic commented on src/BlockTypesController.php
> +			$block_types[] = 'ProductGalleryLargeImage';
Thanks!

2023-07-14 19:31 UTC, thealexandrelara approved these changes
Great! Thank you for addressing that point! ✅

2023-07-14 19:31 UTC, merged