Add/e2e next previous block
woocommerce/woocommerce-gutenberg-products-block pull request #10329
Opened 2023-07-24 13:06 UTC by gigitux

Fixes #

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|        |       |

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1.
2.
3.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

### Changelog

> Add suggested changelog entry here.

2023-08-18 13:01 UTC, danieldudzic requested changes
The tests are failing for me locally.

<img width="910" alt="woocommerce-blocks_—_danieldudzic_MacBook-Pro-Daniel____LocalSites_productgallery_app_public_wp-content_plugins_woocommerce-blocks_—_-zsh_—_129×63" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/00279a3b-3818-414b-9a12-c13e98565a0b">

2023-08-18 13:01 UTC, danieldudzic commented on tests/e2e/tests/product-gallery/inner-blocks/product-gallery-large-image-next-previous/product-gallery-large-image-next-previous.block_theme.spec.ts
> +	} );
I think we can remove this and still keep the test working.

That was the case for my tests in: https://github.com/woocommerce/woocommerce-blocks/pull/10370
```suggestion

```

2023-08-18 13:01 UTC, danieldudzic commented on tests/e2e/tests/product-gallery/inner-blocks/product-gallery-large-image-next-previous/product-gallery-large-image-next-previous.block_theme.spec.ts
> +	} );
This is a duplicated test for rendering on the **editor** side. Make sure this actually tests rendering on the **frontend**.

2023-08-18 13:06 UTC, danieldudzic commented
I'd also add some testing steps:


> Run the following:
> 1. `nvm use`
> 2. `npm install`
> 3. `npm run env:start`
> 4. `npm run test:e2e ./tests/e2e/tests/product-gallery/inner-blocks/product-gallery-large-image-next-previous/product-gallery-large-image-next-previous.block_theme.spec.ts`
> 5. Make sure all tests pass.

2023-08-18 16:49 UTC, gigitux commented on tests/e2e/tests/product-gallery/inner-blocks/product-gallery-large-image-next-previous/product-gallery-large-image-next-previous.block_theme.spec.ts
> +	} );
We should keep this otherwise when the last test will finished, we don't reset the template and it could be an issue for other E2E tests.

2023-08-18 17:00 UTC, gigitux commented
> The tests are failing for me locally.
> 
> <img alt="woocommerce-blocks_—_danieldudzic_MacBook-Pro-Daniel____LocalSites_productgallery_app_public_wp-content_plugins_woocommerce-blocks_—_-zsh_—_129×63" width="910" src="https://user-images.githubusercontent.com/905781/261611860-00279a3b-3818-414b-9a12-c13e98565a0b.png">

I don't have any issues:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/fd69c1c4-e07e-4f19-8aab-03ef8a40fdaa)

On GitHub, there isn't any errors. Can you check that your env is configured correctly?

2023-08-18 17:00 UTC, gigitux commented on tests/e2e/tests/product-gallery/inner-blocks/product-gallery-large-image-next-previous/product-gallery-large-image-next-previous.block_theme.spec.ts
> +	} );
Fixed with [7565700](https://github.com/woocommerce/woocommerce-blocks/pull/10329/commits/7565700c91029dc8877b19dad39ac2f848385b8d)

2023-08-22 11:23 UTC, imanish003 approved these changes
Hello @gigitux, I've made a few minor suggestions in the PR. Since all the tests have successfully passed, I'm granting my pre-approval. Great job! 🚀

2023-08-22 11:23 UTC, imanish003 commented on tests/e2e/tests/product-gallery/inner-blocks/product-gallery-large-image-next-previous/product-gallery-large-image-next-previous.block_theme.spec.ts
> +		} );
Is it possible to use `addBlock` from ./utils here?

2023-08-22 11:23 UTC, imanish003 commented on tests/e2e/tests/product-gallery/inner-blocks/product-gallery-large-image-next-previous/product-gallery-large-image-next-previous.block_theme.spec.ts
> +};
I think we can move this to ./utils. What do you think?

2023-08-22 11:23 UTC, imanish003 commented on tests/e2e/tests/product-gallery/inner-blocks/product-gallery-large-image-next-previous/product-gallery-large-image-next-previous.block_theme.spec.ts
> +		} ) => {
The comment is a bit confusing. Can you please check again if it's correct? 🤔

2023-08-22 11:23 UTC, imanish003 commented on tests/e2e/tests/product-gallery/inner-blocks/product-gallery-large-image-next-previous/product-gallery-large-image-next-previous.block_theme.spec.ts
> +				// eslint-disable-next-line playwright/no-conditional-in-test
I don't think it's a good idea to ignore this eslint rule. Can you think of any scenario where it's acceptable for the parent clientId to be undefined?

2023-08-22 11:26 UTC, imanish003 commented
Hi @danieldudzic,

> The tests are failing for me locally.

Could it be possible that you didn't run `npm start` before running the tests? I ask because this step isn't mentioned explicitly in the testing instructions, so it's possible that it was overlooked. Just a thought! 🙂

2023-08-22 13:49 UTC, danieldudzic commented
> Hi @danieldudzic,
> 
> > The tests are failing for me locally.
> 
> Could it be possible that you didn't run `npm start` before running the tests? I ask because this step isn't mentioned explicitly in the testing instructions, so it's possible that it was overlooked. Just a thought! 🙂

@imanish003 Do you think running `npm start` is necessary?

If so, do you think we should add this step here: https://github.com/woocommerce/woocommerce-blocks/blob/fb1b69190fed13d6e2bcaa051c343c54c9d91192/tests/e2e/README.md ?

2023-08-22 14:31 UTC, danieldudzic approved these changes
> Hi @danieldudzic,
> 
> > The tests are failing for me locally.
> 
> Could it be possible that you didn't run `npm start` before running the tests? I ask because this step isn't mentioned explicitly in the testing instructions, so it's possible that it was overlooked. Just a thought! 🙂

After running `npm start` all tests passed locally.

I have added a few thoughts regarding the `getBoundingClientRect()` testing method here:
pdCMQf-1Hv-p2

2023-08-23 04:39 UTC, imanish003 commented
> @imanish003 Do you think running npm start is necessary?
> 
> If so, do you think we should add this step here: https://github.com/woocommerce/woocommerce-blocks/blob/fb1b69190fed13d6e2bcaa051c343c54c9d91192/tests/e2e/README.md ?

I agree, including it there seems logical.

2023-08-28 08:16 UTC, merged