Best selling products block: show only products with sales and most sold first
woocommerce/woocommerce-gutenberg-products-block pull request #10448
Opened 2023-08-02 12:41 UTC by albarin

This PR updates the query in the `Best Selling Product` blocks to show only products with sales and show the most sold before.

Fixes https://github.com/woocommerce/woocommerce/issues/42596

### Screenshots

| Before | After |
| ------ | ----- |
| ![CleanShot 2023-08-02 at 14 39 01@2x](https://github.com/woocommerce/woocommerce-blocks/assets/186112/2ffa60e7-317b-4f4b-96ce-a1d1892b955f)|<img alt="Screenshot 2023-08-02 at 14 38 03" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/d1465196-b1ad-49a8-8769-8f3f5eda1bf0">|

### Testing

#### User Facing Testing

1. Create a new page or post.
2. Insert the `Best Selling Product` block.
3. Make sure only products that were sold at least once appear on the block and order by number of sales.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Best Selling Products: show only products with sales, ordered by number of sales.

2023-08-03 09:54 UTC, danieldudzic reviewed
I have tested this, and it works correctly!

I used https://github.com/75nineteen/order-simulator-woocommerce to generate dummy orders - pretty useful :)

One question, shouldn't we also update the `block.json`, which currently is set to:

```
		"orderby": {
			"type": "string",
			"enum": [
				"date",
				"popularity",
				"price_asc",
				"price_desc",
				"rating",
				"title",
				"menu_order"
			],
			"default": "popularity"
		}
```

2023-08-03 12:43 UTC, albarin commented
> I have tested this, and it works correctly!
> 
> I used https://github.com/75nineteen/order-simulator-woocommerce to generate dummy orders - pretty useful :)
> 
> One question, shouldn't we also update the `block.json`, which currently is set to:
> 
> ```
> 		"orderby": {
> 			"type": "string",
> 			"enum": [
> 				"date",
> 				"popularity",
> 				"price_asc",
> 				"price_desc",
> 				"rating",
> 				"title",
> 				"menu_order"
> 			],
> 			"default": "popularity"
> 		}
> ```

🤔 Actually, I think it's not really being used anywhere, I might be missing something but I think the `orderby` attribute can be removed from the `block.json`, do you agree?

2023-08-04 13:54 UTC, danieldudzic commented
I have tried removing the following from `block.json` and it does seem to have an effect on  Best Selling Products::

```
		"orderby": {
			"type": "string",
			"enum": [
				"date",
				"popularity",
				"price_asc",
				"price_desc",
				"rating",
				"title",
				"menu_order"
			],
			"default": "popularity"
		}
```


<img width="1097" alt="TOP_SELLING_–_productgallery_i_TOP_SELLING_–_productgallery_i_woocommerce-blocks_—_danieldudzic_MacBook-Pro-Daniel__npm_start_—_webpack_◂_npm_start_TERM_PROGRAM_Apple_Terminal_SHELL__bin_zsh_—_174×55" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/9ccf1db6-83e0-462c-a885-0146b8d9bd07">

The actual best sellers:

<img width="520" alt="Overview_‹_Analytics_‹_WooCommerce_‹_productgallery_—_WooCommerce" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/9aa22bc9-861a-4d47-bf91-0d0cd6c64002">

2023-08-07 07:23 UTC, dinhtungdu requested changes
@albarin Thanks for the PR! In addition to the review comments, I have a concern about this. 

As people are already using this block (which is a replacement to the shortcode), I'm afraid hiding the products that have no sale may affects the existing users as it changes the current behavior of the blocks. The impact may be small but it's definitely there.

What do you think about adding an option enabling merchant to choose whether to display products without sale?

For example, if I'm just starting a new store, given that I don't have much sales, I still want to use the best selling block as a potential way to drive more traffic from my home page into those products. Hiding all products that don't have any sale will make that block empty and prevent me to use it.

From developer perspective, I can setup the Best Selling Products block that display products that don't have any sales to make store looks good from the start and continue working as expect after that. If the block only displays products with sale, I need to use another block first (newest for example), and then comeback to replace with the Best Selling Products block when the store get more sales.

cc @nielslange as you originally opened the issue.

2023-08-07 07:23 UTC, dinhtungdu commented on src/BlockTypes/ProductBestSellers.php
> +		$query_args['order']    = 'DESC';
The order query arguments will be later [overridden](https://github.com/woocommerce/woocommerce-blocks/blob/c2063cd5fd22e14155811906f1222250d0e4023b/src/BlockTypes/AbstractProductGrid.php#L216) by `AbstractProductGrid::set_ordering_query_args()`, which explains the Danny [comment](https://github.com/woocommerce/woocommerce-blocks/pull/10448#issuecomment-1665648464).

2023-08-07 07:23 UTC, dinhtungdu commented on src/BlockTypes/ProductBestSellers.php
> -		$query_args['orderby'] = 'popularity';
This is the [correct query](https://github.com/woocommerce/woocommerce/blob/c4f00719de39b38257d66cc2e171465ea7c4e9db/plugins/woocommerce/includes/class-wc-query.php#L730-L734) for best selling product. I wonder why do you need to change it 🤔

2023-08-07 07:23 UTC, dinhtungdu commented on src/BlockTypes/ProductBestSellers.php
> +		$query_args['order']    = 'DESC';
If we want to remove the `orderby` attribute in the `block.json` file, we will need to reorder the call of `set_ordering_query_args()` in `AbstractProductGrid` so the query variables set by child classes won't be override by other methods in `AbstractProductGrid`.

2023-08-09 07:43 UTC, albarin commented
@dinhtungdu thanks for your feedback, I think you are right, we need to take into account that users are already using the block. The same happens with https://github.com/woocommerce/woocommerce-blocks/pull/10434 which I merged last week, I think I'm going to revert since it has not been released yet.
@nielslange what do you think about @dinhtungdu proposal about adding an option to choose whether to display products without sale?
Thanks!

2023-08-24 09:43 UTC, nielslange commented
> @nielslange what do you think about @dinhtungdu proposal about adding an option to choose whether to display products without sale?

Apologies for my delayed response, @albarin. I haven't seen your message earlier. I do like @dinhtungdu's suggestion, but I would create adjust the PR in a way that only best-selling products are visible by default. If a merchant wants to show all products, meaning also products without sales, then the merchant needs to manually adjust the visibility. To me, it's rather confusing that the Best Selling Products block shows all products by default, independent of if they've been purchased ion the past or not. To me personally, only products that have been sold can become best-selling products.

2023-12-12 09:13 UTC, closed without merging