Fix shipping method switch
woocommerce/woocommerce-gutenberg-products-block pull request #10457
Opened 2023-08-03 07:40 UTC by tarunvijwani

WIP 

Fixes #9790

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|        |       |

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1.
2.
3.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

### Changelog

> Add suggested changelog entry here.

2023-08-11 10:53 UTC, opr requested changes
Hi, I tested and ran into an issue, not sure if this is intentional behaviour but maybe look into it?

1. Enable [Multiple Packages for WooCommerce](https://wordpress.org/plugins/multiple-packages-for-woocommerce/) and Go to WooCommerce > Settings > Multiple Packages, set the "group by" option to "Product (individual)"
2. Have shipping methods set up for a specific location
3. Do not have shipping methods set up for "other" locations.
4. Add 2 items to the cart and go to Checkout.
5. Enter an address where no shipping options exist.
6. Select Local Pickup.
7. Reload the page, notice local pickup is still selected 
8. With Local Pickup still selected, change address to one covered by a shipping zone.
9. Notice Local Pickup is still selected 
10. Reload the page, notice Local Pickup is no longer selected 

https://www.loom.com/share/f5b16e54e1da4d1c97ff7ad6a8b59ab0

2023-09-07 13:39 UTC, tarunvijwani commented
We've done more research and discovered that WooCommerce has a default behaviour that resets shipping methods every time an address change occurs. However, we have overridden this behaviour using a filter. I'll update the unit tests for the PR shortly and get it ready for review as soon as I can. 

Internal discussion: p1693292016236569-slack-C8X6Q7XQU

2023-09-13 20:09 UTC, tarunvijwani commented
### Problem

If local pickup is enabled but there are no available shipping methods for a specific address, we have noticed that the shipping method will change automatically to the default option that is available first once the shipping address is modified.

This issue occurs because WooCommerce Core resets shipping methods whenever the address changes.

### Solution 1

When the address is changed during checkout, it calls the "cart/update-customer" endpoint. Within this endpoint, the boolean value "prefersCollection" is passed as "true" if the customer has selected the "local pickup" option. This value then overrides the selected shipping rate with the available shipping rates. You can find the relevant code for this process here: https://github.com/woocommerce/woocommerce-blocks/pull/10457/commits/4660933bc47111160896320348f07f3ca4144dbe

However, this process works only if the shopper remains on the same page. If the shopper navigates away from the checkout page and returns, the first available shipping method will be selected instead of the one previously chosen. This issue occurs because we only modify the selected shipping rate after the address changes. The value in "wc()->session->get( 'chosen_shipping_methods', array() );" remains the same. This causes the "prefersCollection" value to be false when the page loads for the first time or gets refreshed.

### Solution 2 

There is a way to override the behavior of Woo Core that resets the chosen shipping method. This is done by implementing a "woocommerce_shipping_chosen_method" filter. However, using this filter caused some of the existing unit test cases for store API to fail. Additionally, I have observed that the filter does not always work when the page is refreshed. 
You can find the relevant code for this process here: https://github.com/woocommerce/woocommerce-blocks/pull/10457/commits/3b7367ac940f0181fbb8629377b1ec6d850756af

### Solution 3 
Along with Solution 1, manually update the 'chosen_shipping_methods' session data when the shipping address changes.



@opr @mikejolley I followed Solution 3 in this PR and manually overrode the session data. However, it's a hacky workaround, and there seems to be no other solution.

I have invested significant time into this PR, so I'm marking this PR as ready for review. However, I am also interested in exploring alternative solutions if available. I'm up for the pairing sessions. Let me know.

2023-09-14 15:07 UTC, mikejolley commented
Based on the testing steps I am confused as to why so much code, particularly in store API, is needed to solve this. The simplest case to test this is:

1. Go to checkout and select local pickup
2. In another tab, open zones and add a new rate to your current zone.
3. Refresh checkout.

In trunk this reverts selection from local pickup, to shipping. But this can be manipulated via 1 filter on core to determine the "default" selected rate. Adding this to ShippingController in blocks:

```php
		add_filter(
			'woocommerce_shipping_chosen_method',
			function ( $default, $package_rates, $chosen_method ) {
				// If we had a chosen method, and it still exists, return it. This prevents the selection changing if new
				// rates are added or removed.
				if ( $chosen_method && isset( $package_rates[ $chosen_method ] ) ) {
					return $chosen_method;
				}
				// Otherwise pass through new default.
				return $default;
			},
			20,
			3
		);
```

@tarunvijwani did you try this approach?

2023-09-15 18:39 UTC, tarunvijwani commented
@mikejolley I tried this approach and shared the Slack earlier: p1694001430672649/1693292016.236569-slack-C8X6Q7XQU

However, it seems that I wasn't using it correctly, so it was causing some tests to fail. 

Thank you so much for sharing the correct approach. It works great! 🎉 

Updated the PR ✅

2023-09-18 19:07 UTC, opr approved these changes
Thanks Tarun, this looks good! Tested ok too.

I noticed in the PR you ticked that this is covered by unit tests, let's untick that, and let's create a ticket to follow up with some E2E tests for this.

2023-09-18 19:07 UTC, opr commented on src/Shipping/ShippingController.php
> +		add_filter( 'woocommerce_shipping_chosen_method', array( $this, 'prevent_shipping_method_selection_changes' ), 20, 3 );
Minor nitpick but let's remove the linebreak from above this line.

2023-09-19 08:28 UTC, tarunvijwani commented
@opr Thank for reviewing the PR.

>I noticed in the PR you ticked that this is covered by unit tests, let's untick that, and let's create a ticket to follow up with some E2E tests for this.

I forgot to untick the box when I changed the code and description of the PR. I don't think we will need unit test cases for the current changes in the PR because we are not altering any store API anymore.

2023-09-19 08:29 UTC, merged

2023-09-19 08:33 UTC, ralucaStan commented
> @[tarunvijwani](https://github.com/tarunvijwani) tarunvijwani [force-pushed](https://github.com/woocommerce/woocommerce-blocks/compare/d9c2ca7bd382f9d2d2a551193c7db4fc2ab73e2e..ecf2d337d761676acf94539046af0eef82c51dec) the fix/9790-shipping-method-switch branch from [d9c2ca7 ](https://github.com/woocommerce/woocommerce-blocks/commit/d9c2ca7bd382f9d2d2a551193c7db4fc2ab73e2e)to [ecf2d33](https://github.com/woocommerce/woocommerce-blocks/commit/ecf2d337d761676acf94539046af0eef82c51dec)

Happy to see this merged. For long-lived branches like this one let's refrain from force pushing. There is a lot of context that has been lost.

2023-09-19 08:36 UTC, tarunvijwani commented
@ralucaStan Sure, I will avoid force pushing the code. 👍