Add E2E tests for Product Collection with Compatibility Layer
woocommerce/woocommerce-gutenberg-products-block pull request #10540
Opened 2023-08-11 08:36 UTC by kmanijak

Recreation of https://github.com/woocommerce/woocommerce-blocks/pull/10463 due to unnnecessarily complex conflicts to resolve.

This PR adds set of E2E Playwright tests for Compatibility Layer against the Product Collection used in Product Archive template.

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [x] E2E tests

#### User Facing Testing

1. E2E test are passing

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental

2023-08-11 13:00 UTC, gigitux requested changes
Thanks for your work! Overall LGTM, but before merging it, we should address some comments!

2023-08-11 13:00 UTC, gigitux commented on tests/e2e/tests/product-collection/compatibility-layer-block_theme.spec.ts
> +} from '../../mocks/custom-plugins';
We are trying to importing the utils avoiding the relative import:

```suggestion
} from 'from '@woocommerce/e2e-mocks/custom-plugins';
```

2023-08-11 13:00 UTC, gigitux commented on tests/e2e/tests/product-collection/compatibility-layer-block_theme.spec.ts
I think that this E2E test contain some side-effects, so we should rename this E2E test with:
compatibility-layer.block_theme.side-effects.spec.ts. Also, currently missing a `.` before block_theme.

The suffix adoption is really important for our E2E test infrastructure.

2023-08-11 13:00 UTC, gigitux commented on tests/e2e/tests/product-collection/compatibility-layer-block_theme.spec.ts
> +	);
If I understand well, we are checking that the text is present in the page. We are not checking the order, right?

2023-08-11 13:00 UTC, gigitux commented on tests/e2e/tests/product-collection/compatibility-layer-block_theme.spec.ts
> +		await uninstallPluginFromPHPFile(
Since that we have update the template, we have to cleanup the global change with:
```
	await deleteAllTemplates( 'wp_template' );
```

2023-08-11 14:17 UTC, kmanijak commented on tests/e2e/tests/product-collection/compatibility-layer-block_theme.spec.ts
> +	);
That's true. I have an idea to test the order but I need a bit more time for it to verify. For now I'd go ahead and merge this PR in its current state. I addressed other comments though.

Thanks for the great review with great tips! 🙇

2023-08-16 09:05 UTC, kmanijak commented
@gigitux I addressed most of the comments except for:

> If I understand well, we are checking that the text is present in the page. We are not checking the order, right?

> That's true. I have an idea to test the order, but I need more time to verify it. For now I'd go ahead and merge this PR in its current state. I addressed other comments though.

I'd be grateful if you could review again 🙏

2023-08-16 09:09 UTC, gigitux approved these changes
I’m pre-approving this PR, but before merging the PR it is necessary to update the suffix to `side_effects`.

2023-08-16 09:09 UTC, gigitux commented on tests/e2e/tests/product-collection/compatibility-layer.block_theme.side-effects.spec.ts
The right suffix is `side_effects`.

2023-08-16 09:54 UTC, merged