Order confirmation: Add wrapper for the order downloads block
woocommerce/woocommerce-gutenberg-products-block pull request #10606
Opened 2023-08-15 14:43 UTC by mikejolley

Adds a wrapper for the order downloads block so the heading is only visible when downloads are present in the order. Also introduces styling controls for the downloads block itself.

Fixes #10599

### Screenshots

![Screenshot 2023-08-15 at 15 31 06](https://github.com/woocommerce/woocommerce-blocks/assets/90977/9720461c-029c-4303-8975-3b53e732d5ea)

![Screenshot 2023-08-15 at 15 29 17](https://github.com/woocommerce/woocommerce-blocks/assets/90977/278a6cfc-4862-4d4f-bede-9381523101d3)

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Ensure you have a legacy order confirmation page before testing. You should reset the template.
2. Also delete/trash any downloadable products in your store.
3. Convert the template to blocks. There should be no downloads section right now, but save the template anyway.
4. Untrash the downloadable products in your store, or create some new ones.
5. Go back to the template editor. The downloads section is now visible.
6. Change styles/controls etc and check that styles appear. Save changes.
7. Go to the frontend and purchase some downloadable products.
8. The confirmation page will show but downloads may not be present yet. Leave the page open.
9. Go into admin and mark the order complete or processing.
10. Refresh the confirmation page.
11. See the downloads block is now visible.

* [x] Do not include in the Testing Notes 
* [x] Should be tested by the development team exclusively 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental

2023-08-18 00:04 UTC, tarhi-saad requested changes
Thank you, @mikejolley, for working on this PR! I left some minor comments below.

Why is an API request triggered each time we edit the style controls of the `Downoalds` Block? As a result, this Block gets rerendered!

<img width="1456" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/dac5e6b9-2e9b-4a0b-9020-37196b1214f3">

2023-08-18 00:04 UTC, tarhi-saad commented on assets/js/blocks/order-confirmation/downloads-wrapper/block.json
> +	"description": "Display the downloadale products section.",
A typo here: "downloadable"

2023-08-18 00:04 UTC, tarhi-saad commented on assets/js/blocks/order-confirmation/downloads-wrapper/index.tsx
> +					icon={ mapMarker }
Maybe we can use the same "download" icon that we used for the inner block.

2023-08-18 12:12 UTC, mikejolley commented
> Why is an API request triggered each time we edit the style controls of the Downoalds Block? As a result, this Block gets rerendered!

Its a server side rendered block, so the request is to update styles. Thats expected for these blocks I believe.

2023-08-24 06:41 UTC, tarhi-saad commented
> Its a server side rendered block, so the request is to update styles. Thats expected for these blocks I believe.

I replaced the server-side rendering of the Dowloads Block on the edit page with a placeholder. The same way we did for the Shipping and Billing addresses Blocks

2023-08-24 06:56 UTC, tarhi-saad approved these changes

2023-08-24 06:57 UTC, merged