Product Gallery Block: Add zoom on hovering on the frontend
woocommerce/woocommerce-gutenberg-products-block pull request #10791
Opened 2023-08-31 08:30 UTC by gigitux

~~⚠️ This PR is blocked by #10764.~~

## What

Fixes #9941

## Why

This PR adds the zoom when the image is hovered, thanks to the Interactivity API. Please review #10795.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Open the Site Editor. Visit the Single Product Template.
2. Add the Product Gallery Block.
3. Ensure that the setting about the zoom on hovering is enabled.
4. Save.
5. Visit a product page.
6. Hover the image and ensure that the image is zoomed on hovering.
7. Visit the Single Product Template.
8. Disable the setting about the zoom on hovering.
9. Visit a product page.
10. Ensure that the image isn't zoomed on hover.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

https://github.com/woocommerce/woocommerce-blocks/assets/4463174/2faa862e-af81-4730-85eb-0e411e7ea488

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

2023-08-31 17:11 UTC, danieldudzic requested changes
Awesome job, @gigitux - you are one brave man for tackling this!

The zoom gets triggered correctly, but the behavior (left to right) seems a little bit off.

For example you can't really zoom onto the left side of the image:

<img width="1041" alt="Cursor_i_V-Neck_T-Shirt_–_newproductgallery" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/d613b0d0-60e7-41c9-9490-650d46b6ed94">

2023-08-31 17:11 UTC, danieldudzic commented on src/BlockTypes/ProductButton.php
>  				'wp_enqueue_scripts',
This seems to be unrelated :)

2023-08-31 17:11 UTC, danieldudzic commented on src/BlockTypes/MiniCartContents.php
This seems to be unrelated also.

2023-08-31 17:11 UTC, danieldudzic commented on src/BlockTypes/Checkout.php
>  		 *
Same here, doesn't seem like this code belongs in this PR.

2023-08-31 17:11 UTC, danieldudzic commented on src/BlockTypes/Cart.php
>  		 *
Same here, doesn't seem like this code belongs in this PR.

2023-08-31 17:11 UTC, danieldudzic commented on src/BlockTypes/AbstractBlock.php
Doesn't seem like this code belongs in this PR :)

2023-08-31 17:11 UTC, danieldudzic commented on assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/frontend.tsx
> +				handleMouseMove: async ( {
I have a small question. Both `handleMouseMove` and `handleMouseLeave` are marked as `async` but but I don't see any subsequent `await`'s in the code, within these functions.

Is this necessary for the Interactivity API to work correctly?

2023-08-31 17:11 UTC, danieldudzic commented on assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/frontend.tsx
> +							percentageY > 100 ? 100 : percentageY;
Is it possible for `percentageX` and `percentageY` to be greater than `100`?

2023-08-31 17:11 UTC, danieldudzic commented on assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/frontend.tsx
> +					context.woocommerce.styles[ 'transform-origin' ] = '';
Maybe instead of setting it to nothing we should set it to the default value: `50% 50% 0` ?

2023-09-01 07:17 UTC, gigitux commented
> Awesome job, @gigitux - you are one brave man for tackling this!
> 
> The zoom gets triggered correctly, but the behavior (left to right) seems a little bit off.
> 
> For example you can't really zoom onto the left side of the image:
> 
> <img alt="Cursor_i_V-Neck_T-Shirt_–_newproductgallery" width="1041" src="https://user-images.githubusercontent.com/905781/264724087-d613b0d0-60e7-41c9-9490-650d46b6ed94.png">

Mmm, it seems that it works correctly:


https://github.com/woocommerce/woocommerce-blocks/assets/4463174/f0749ef2-3271-4b8b-b65c-950c5202077a


https://github.com/woocommerce/woocommerce-blocks/assets/4463174/7e387716-940b-4184-9c01-3aad3df034e5


The changes relative to the function `enqueue_assets` aren't unrelated. The goal is to enqueue the Interactivity API only if the setting is enabled ([source code](https://github.com/woocommerce/woocommerce-blocks/pull/10791/files#diff-1ad160860b7b0cdac44eab7d3344949822d8d32db90384d2ecd92c9fcb1700d3R31-R34)). To do this, it is necessary to have access to the context. So, it was necessary to update the `AbstractBlock` class and all the classes that use `enqueue_assets`.

2023-09-01 07:19 UTC, gigitux commented on assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/frontend.tsx
> +				handleMouseMove: async ( {
Good catch! They are not necessary. Fixed with be651ce954cef309866f537ccc14855c3eb6c684.

2023-09-01 07:21 UTC, gigitux commented on assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/frontend.tsx
> +							percentageY > 100 ? 100 : percentageY;
Yes, it is possible in some cases. When they are greater than 100, there is this weird behavior:

https://github.com/woocommerce/woocommerce-blocks/assets/4463174/a40befd4-2c0e-48ee-aac5-a55e6f69f11e

2023-09-01 07:22 UTC, gigitux commented on assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/frontend.tsx
> +					context.woocommerce.styles[ 'transform-origin' ] = '';
IMHO, it is clearer if the property is empty, but I don't have a strong preference.

2023-09-01 19:03 UTC, thealexandrelara requested changes
Great work so far; however I got the same issue as @danieldudzic, there are some regions that the image is not zooming in:

https://github.com/woocommerce/woocommerce-blocks/assets/20469356/9a5a155b-2957-4f89-9913-a7e131c5edb7

It seems the transform-origin property is not being updated correctly when I have the mouse pointing to the left edge of the image the minimum percentage is set to about 17-18% which prevent the left part of the image to display:
![CleanShot 2023-09-01 at 15 41 24](https://github.com/woocommerce/woocommerce-blocks/assets/20469356/e63405ae-2afd-4d22-897e-1b4c90d33505)

I left some suggestion that can address this issue, hope it helps!

2023-09-01 19:03 UTC, thealexandrelara commented on assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/frontend.tsx
> +						] = `${ maxPercentageX }% ${ maxPercentageY }%`;
I noticed that you're calculating the offsetX and offsetY. However, the MouseEvent already has these properties in `event.offsetX` and `event.offsetY`. By using these properties, we can simply divide their values by clientWidth and clientHeight, and then multiply them by 100 to obtain the result as a percentage. This approach simplifies the code a little bit, and the value will always fall between 0 and 100%, allowing you to remove the condition that checks if the value is greater than 100%.

```suggestion
						const element = event.target as HTMLElement;
						const percentageX =
							( event.offsetX / element.clientWidth ) * 100;
						const percentageY =
							( event.offsetY / element.clientHeight ) * 100;

						context.woocommerce.styles.transform = `scale(1.3)`;

						context.woocommerce.styles[
							'transform-origin'
						] = `${ percentageX }% ${ percentageY }%`;
```

2023-09-04 07:55 UTC, gigitux commented
Thanks @thealexandrelara, for the suggestion! I applied your suggestion and it seems that the bug is fixed as well!.

In this image, the pointer is on top of the left of the image:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/9ae45d00-8e5a-45da-b550-ddca79735dcc)

2023-09-04 20:49 UTC, thealexandrelara requested changes
Thank you addressing that issue, I can confirm that now the zoom is working correctly! 🥳 

However, for some reason, the large image in the editor is getting cut off when I have the Thumbnails block enabled :/

![CleanShot 2023-09-04 at 17 45 53](https://github.com/woocommerce/woocommerce-blocks/assets/20469356/9444da97-b8d3-41d9-93e7-89b7982c75d4)

2023-09-05 08:07 UTC, gigitux commented
> Thank you addressing that issue, I can confirm that now the zoom is working correctly! 🥳
> 
> However, for some reason, the large image in the editor is getting cut off when I have the Thumbnails block enabled :/
> 
> ![CleanShot 2023-09-04 at 17 45 53](https://user-images.githubusercontent.com/20469356/265539223-9444da97-b8d3-41d9-93e7-89b7982c75d4.png)

This issue isn't caused by this PR. We have already in trunk:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/83c64a0f-d3f0-41a6-a6a3-fc288e766c6b)

The image is cut for `overflow:hidden` ([source code](https://github.com/woocommerce/woocommerce-blocks/pull/10791/files#diff-a09342e95aa95757f96b7535611b55c9b6a1c76bc6b02c6e0cbced9de85daceaR5)), but I think that we should address the original issue in a dedicated issue. If you agree, I will create it.

2023-09-05 12:45 UTC, thealexandrelara approved these changes
Okay, so since it's already happening on trunk let's create a separate issue to address that error. Everything looks good with this PR, great work! 🚀

2023-09-05 13:17 UTC, gigitux commented
Issue created: https://github.com/woocommerce/woocommerce-blocks/issues/10838

2023-09-05 13:22 UTC, gigitux commented
Issue created: https://github.com/woocommerce/woocommerce-blocks/issues/10838

2023-09-05 13:22 UTC, merged

2023-09-05 13:38 UTC, Marc-pi commented
awesome ;-)

2023-09-19 13:15 UTC, mikejolley commented
Hopefully this won't cause issues and no-one is extending this, but this change to `enqueue_assets` is a breaking change for classes extending it. I came across this when rebasing the order confirmation block.

2023-09-19 14:37 UTC, gigitux commented
@mikejolley Good point... the `AbstractBlock` isn't marked as an internal class. Do you think we should revert the change about the `enqueue_assets`?

2023-09-19 15:23 UTC, mikejolley commented
@gigitux did it ship already? I guess you could handle this unique case in the class that needs it and leave the abstract but its up to you. I only noticed because I had some fatal errors after rebasing.

2023-09-19 15:27 UTC, gigitux commented
@mikejolley Yes! It will be included in the WooCommerce 8.2 release.