Add Featured Categories Grid pattern
woocommerce/woocommerce-gutenberg-products-block pull request #10807
Opened 2023-09-01 10:34 UTC by albarin

## What

Adds the new `Featured Categories Grid` pattern.

## Why

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/10771

## Testing Instructions

1. Create a new page or post.
2. Insert the `Featured Categories Grid` pattern.
3. Check it has 3 items per row and all the Product Categories are present.
4. Save, and check it looks good also con the front end.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

<img width="992" alt="Screenshot 2023-09-01 at 12 31 36" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/3d0d6a2f-2a36-48a7-89e0-d81d92cfa1c8">

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Adds the new `Featured Categories Grid` pattern.

2023-09-05 08:21 UTC, danieldudzic requested changes
The pattern works correctly!

Requested some minor changes. Feel free to ignore the `$rows` calculation suggestion.

2023-09-05 08:21 UTC, danieldudzic commented on patterns/featured-categories-grid.php
> +$rows = intdiv( count( $categories ), $cols ) + count( $categories ) % $cols;
I believe this could be simplified to:
```suggestion
$rows = ceil( count( $categories ) / $cols );
```

2023-09-05 08:21 UTC, danieldudzic commented on patterns/featured-categories-grid.php
> + * Title: Featured Category Grid
The instructions mention `Featured Categories Grid`

2023-09-06 04:38 UTC, dinhtungdu reviewed
I think instead of showing all possible categories (and having a complex logic in pattern file), we can show only first three categories. If merchants need to display more, they can duplicate the row/column blocks and make changes.

2023-10-02 07:21 UTC, albarin commented
> I think instead of showing all possible categories (and having a complex logic in pattern file), we can show only first three categories. If merchants need to display more, they can duplicate the row/column blocks and make changes.

Sorry for the delay in the response 🙏 
That's fair, maybe it's too much logic for a pattern.
Just thinking about it, I'm not sure how much sense this pattern has right now. What would happen if there are no categories, or there's only one available, or any other weird case? We would need to control all the logic in the pattern file. WDYT?

2023-10-09 09:53 UTC, dinhtungdu commented
> Just thinking about it, I'm not sure how much sense this pattern has right now. What would happen if there are no categories, or there's only one available, or any other weird case? We would need to control all the logic in the pattern file. WDYT?

I see. Maybe an improved Category list block or a new Category grid block should be better than a pattern. Handling logic inside patterns doesn't feel right to me.

2023-10-09 11:57 UTC, albarin commented
> I see. Maybe an improved Category list block or a new Category grid block should be better than a pattern. Handling logic inside patterns doesn't feel right to me.

Totally agree 👌 I'm closing this PR for now.

2023-10-09 11:57 UTC, closed without merging

2023-10-09 12:03 UTC, dinhtungdu commented
@albarin Anyway, thank you so much for working on this PR! Even we closed it, it's worth the effort as we have a good direction as the result.