Add local pickup tracking
woocommerce/woocommerce-gutenberg-products-block pull request #10841
Opened 2023-09-05 16:09 UTC by senadir

This adds PHP side tracking to Local Pickup save action, it will push the whole object everytime being saved.
## What

Closes https://github.com/woocommerce/woocommerce/issues/37699
Closes https://github.com/woocommerce/woocommerce-blocks/issues/9731

### Testing

1. Enable trackings
2. Save settings
3. See if the action shows up in the tracks.

* [x] Do not include in the Testing Notes 
* [x] Should be tested by the development team exclusively

2023-09-07 17:26 UTC, opr requested changes
I think we need to move 
`$this->container->get( JetpackWooCommerceAnalytics::class )->init();`

from [this line in Bootstrap.php](https://github.com/woocommerce/woocommerce-blocks/blob/627f6c1c7ea89e629f9e075be1d13972a2ef2ec9/src/Domain/Bootstrap.php#L141) outside of the `if ( ! $is_rest )` condition, because currently pressing save does not trigger the event.

2023-09-19 13:16 UTC, senadir commented
@opr We can gate loading the assets file behind a `is_rest` then.

2023-09-19 13:35 UTC, opr commented
> @opr We can gate loading the assets file behind a `is_rest` then.

Sounds like a good idea, let me know when you need a new review!

2023-09-19 21:57 UTC, opr approved these changes
Working well for me, just a suggestion about the event name.

2023-09-19 21:57 UTC, opr commented on src/Domain/Services/JetpackWooCommerceAnalytics.php
> +		$event_name = 'wcadmin_local_pickup_save_changes';
This actually tracks as `wcadmin_wcadmin_local_pickup_save_changes` should we remove the prefix here?
```suggestion
		$event_name = 'local_pickup_save_changes';
```

2023-09-20 09:00 UTC, merged