Update experimental blocks in the feature-flags-and-experimental-interfaces doc
woocommerce/woocommerce-gutenberg-products-block pull request #10937
Opened 2023-09-13 14:16 UTC by danieldudzic

This PR updates the `feature-flags-and-experimental-interfaces.md` doc to reflect the current blocks that are behind the experimental flag.

It removes the following entries:
- Product Gallery Thumbnails ([PHP flag](https://github.com/woocommerce/woocommerce-blocks/blob/04af396b9aec5a915ad98188eded53e723a051d3/src/BlockTypesController.php#L234) | [webpack flag](https://github.com/woocommerce/woocommerce-blocks/blob/04af396b9aec5a915ad98188eded53e723a051d3/bin/webpack-entries.js#L57-L60)). - **It doesn't make sense to list each of the inner blocks of the Product Gallery here**
- Product Average Rating ([PHP flag](https://github.com/woocommerce/woocommerce-blocks/blob/1111e2fb9d6f5074df96a444b99e2fc00e4eb8d1/src/BlockTypesController.php#L229) | [webpack flag](https://github.com/woocommerce/woocommerce-blocks/blob/1111e2fb9d6f5074df96a444b99e2fc00e4eb8d1/bin/webpack-entries.js#L68-L70)) - **graduated**
- Product Rating Stars ([PHP flag](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypesController.php#L230) | [webpack flag](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/bin/webpack-entries.js#L68-L70)) - **graduated**
- Product Rating Counter ([PHP flag](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypesController.php#L229) | [webpack flag](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/bin/webpack-entries.js#L71-L73)) - **graduated**

## Testing Instructions

N/A

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [x] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [x] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

2023-09-14 06:44 UTC, tarhi-saad requested changes
Thank you, @danieldudzic, for this PR! I left a comment below!

2023-09-14 06:44 UTC, tarhi-saad commented on docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md
> --   Product Gallery Thumbnails ([PHP flag](https://github.com/woocommerce/woocommerce-blocks/blob/04af396b9aec5a915ad98188eded53e723a051d3/src/BlockTypesController.php#L234) | [webpack flag](https://
@danieldudzic, the `Product Gallery Thumbnails` is still behind an experimental flag in trunk ([PHP](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypesController.php#L236), [webpack](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/bin/webpack-entries.js#L66-L68)). Is this block supposed to be no longer experimental? Cc: @kmanijak

2023-09-14 06:51 UTC, kmanijak reviewed
> Product Gallery Thumbnails ([PHP flag](https://github.com/woocommerce/woocommerce-blocks/blob/04af396b9aec5a915ad98188eded53e723a051d3/src/BlockTypesController.php#L234) | [webpack flag](https://github.com/woocommerce/woocommerce-blocks/blob/04af396b9aec5a915ad98188eded53e723a051d3/bin/webpack-entries.js#L57-L60)). - It doesn't make sense to list each of the inner blocks of the Product Gallery here

I think it does for clarity. Otherwise, it's all good! 👍

2023-09-15 09:26 UTC, danieldudzic commented
> > Product Gallery Thumbnails ([PHP flag](https://github.com/woocommerce/woocommerce-blocks/blob/04af396b9aec5a915ad98188eded53e723a051d3/src/BlockTypesController.php#L234) | [webpack flag](https://github.com/woocommerce/woocommerce-blocks/blob/04af396b9aec5a915ad98188eded53e723a051d3/bin/webpack-entries.js#L57-L60)). - It doesn't make sense to list each of the inner blocks of the Product Gallery here
> 
> I think it does for clarity. Otherwise, it's all good! 👍

@gigitux what do you think?

Does it make sense listing all Product Gallery inner blocks in the feature-flags-and-experimental-interfaces doc?:
- Thumbnails
- Pager
- Next/Previous Buttons
- Large Image

2023-09-18 13:10 UTC, gigitux commented
> > > Product Gallery Thumbnails ([PHP flag](https://github.com/woocommerce/woocommerce-blocks/blob/04af396b9aec5a915ad98188eded53e723a051d3/src/BlockTypesController.php#L234) | [webpack flag](https://github.com/woocommerce/woocommerce-blocks/blob/04af396b9aec5a915ad98188eded53e723a051d3/bin/webpack-entries.js#L57-L60)). - It doesn't make sense to list each of the inner blocks of the Product Gallery here
> > 
> > 
> > I think it does for clarity. Otherwise, it's all good! 👍
> 
> @gigitux what do you think?
> 
> Does it make sense listing all Product Gallery inner blocks in the feature-flags-and-experimental-interfaces doc?:
> 
> * Thumbnails
> * Pager
> * Next/Previous Buttons
> * Large Image

I think that it does. In this way, we reduce the chance of forgetting to remove the check when the block is production-ready!

2023-09-19 15:03 UTC, gigitux approved these changes
LGTM

2023-09-19 21:24 UTC, tarhi-saad approved these changes
Thank you for working on this PR, @danieldudzic! 🚢

2023-09-19 21:37 UTC, merged