Update documentation
woocommerce/woocommerce-gutenberg-products-block pull request #10935
Opened 2023-09-13 12:15 UTC by corners2wall

## What

Closes #10902 

Fixes #

## Why

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1.
2.
3.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

Before:
![Screenshot from 2023-09-13 15-11-52](https://github.com/woocommerce/woocommerce-blocks/assets/110557519/919007ce-30e6-4d00-9ed9-3d050ebe3ed6)

After:
![Screenshot from 2023-09-13 15-09-06](https://github.com/woocommerce/woocommerce-blocks/assets/110557519/3cc48da1-9382-40f2-aa83-f1942954e192)

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [x] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

2023-09-14 04:56 UTC, nielslange requested changes
Thank you so much for your contribution, @corners2wall. We appreciate this very much. 

While reviewing this PR, I noticed a few things, that should be changed:
- Please replace _"Update documentation"_ with a speaking title, such as _"Cart Line Items » saleBadgePriceFormat: Add code snippet and screenshot"_, which is the title of the corresponding issue.
- Please provide information in the section _"What"_ so that a reviewer can see what had been changed. (Example: #10930)
- Please provide information in the section _"Why"_ so that a reviewer can see why this change was needed. (Example: #10930)
- Please provide information in the section _"Testing Instructions"_ so that a reviewer can see how to test this PR. (Example: #10930)
- The section _"Screenshots or screencast"_ shows the initial screenshot as _"Before"_ and the code example and the new screenshot as _"After"_. This indicates that the original screenshot had been removed, which is not the case. As the section _"Screenshots or screencast"_ is not really needed for this PR, you can remove it.
- Currently, the code example and the new screenshot are placed directly below the title _"Cart Line Items"_. Please move both the code example and the new screenshot below the table with the filter names and the sentence _"Each of these filters has the following arguments [...]"_, and add the following subheading:
```md
saleBadgePriceFormat
```
I haven't mentioned this in the initial issue, as I noticed this too late. Sorry for that.

---

Other than that, the PR looks good. If you have addressed these points, we should be able to approve and merge this PR. 

If you have any questions regarding the points I mentioned, please let me know, and thanks again for your contribution. 🙏

2023-09-14 08:29 UTC, nielslange commented on docs/third-party-developers/extensibility/checkout-block/available-filters.md
> +    return ' per item';
```suggestion
    return '<price/> per item';
```

2023-09-14 08:29 UTC, nielslange commented on docs/third-party-developers/extensibility/checkout-block/available-filters.md
> +    return ' per item';
For some reason, the part `<price/>` got lost when pasting the code example. I just added it to the issue. Please also add it to the PR. 😀

2023-09-15 07:30 UTC, nielslange commented
Hello @corners2wall, I see that you committed my suggestions. Could you also address the points that I mentioned in https://github.com/woocommerce/woocommerce-blocks/pull/10935#pullrequestreview-1625829820? 😀

2023-09-15 16:16 UTC, corners2wall commented
@nielslange No, I don't want to understand this, sorry

2023-09-16 04:32 UTC, nielslange commented
> @nielslange No, I don't want to understand this, sorry

Thanks for letting me know. In https://github.com/woocommerce/woocommerce-blocks/pull/10935#pullrequestreview-1625829820, I am mainly talking about the description of this PR and not the code itself. 

Let's compare https://github.com/woocommerce/woocommerce-blocks/pull/10976 with this PR:

<img width="2560" alt="Screenshot 2023-09-16 at 11 22 52" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/e140d8e5-6433-40e5-a293-7fd9e9d37b4d">

If you don't understand my suggestions because of a language barrier, maybe it would help if you use [Google Translate](https://translate.google.com/) to translate my comment into your language. 

Please let me know if that helps or if I shall explain my suggestions in detail.

2023-09-18 14:35 UTC, nielslange commented
Hello @corners2wall, I haven't heard back from you. Based on your comment in https://github.com/woocommerce/woocommerce-blocks/pull/10935#issuecomment-1721533316, I assume you no longer want to work on this issue. I'm going to close this PR for now. That said, I'd be happy to see you again as a contributor to WooCommerce Blocks in the future.

2023-09-18 14:35 UTC, closed without merging