Recognise template parts after theme switch
woocommerce/woocommerce-gutenberg-products-block pull request #11190
Opened 2023-10-10 06:29 UTC by nielslange

## What

Ensure consistent recognition of header and footer template parts in the Order Confirmation template when switching themes.

Fixes #11106 

## Why

In the current setup, blockifying the Order Confirmation template locks in the name of the active theme, e.g. `twentytwentyfour`, for its header and footer template parts. Upon switching themes, these template parts fail to load as they search for the initially set theme's header and footer, causing a mismatch.

## Testing Instructions

1. Install [WordPress 6.4 Beta 1](https://wordpress.org/news/2023/09/wordpress-6-4-beta-1/).
2. Ensure that the Twenty Twenty-Four theme is active.
3. Go to `WP Admin » Appearance » Editor » Templates » Order Confirmation`.
4. Open the template, click on it, press the button `Transform into blocks` and save the template.
5. Switch to the Twenty Twenty-Three theme. 
6. Verify that both the header and the footer templates are loading.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

<table>
<tr>
<td>Before:
<br><br>
<img width="1441" alt="Screenshot 2023-10-10 at 13 25 05" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/bfacbee0-de94-4061-adf6-f0f041673d0b">
</td>
<td>After:
<br><br>
<img width="1441" alt="Screenshot 2023-10-10 at 13 26 19" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/fbe33646-d545-41e1-b73e-7e8fd881c1ae">
</td>
</tr>
</table>

## WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Fixed loader issue for header and footer template parts in Order Confirmation template after theme switch.

2023-10-12 18:24 UTC, tarhi-saad requested changes
Hi, @nielslange! I followed the testing steps, but I still see the same bug (Template part has been deleted or is unavailable: header):

<img width="1549" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/dfcd0bc3-7ad5-4774-a8f6-1a97f560ba95">

We can't see it in this screenshot, but the same error occurs for the footer. The only difference I made in my testing is that I was invited to install `WordPress 6.4 Beta 3` instead of `Beta 1`.

2023-10-13 02:39 UTC, nielslange commented
> Hi, @nielslange! I followed the testing steps, but I still see the same bug (Template part has been deleted or is unavailable: header):

@tarhi-saad Is it possible that your Order Confirmation template had been converted before this PR, thus, that you're using an older version of the template?

2023-10-13 06:07 UTC, tarhi-saad commented
@nielslange, I tested using a Ninja website and even set up a new one a few minutes ago, where I encountered the same bug. Would you like the credentials for my Ninja website? This time, I was invited to install the Beta 4 of WP!

2023-10-13 06:53 UTC, nielslange commented
> @nielslange, I tested using a Ninja website and even set up a new one a few minutes ago, where I encountered the same bug. Would you like the credentials for my Ninja website? This time, I was invited to install the Beta 4 of WP!

Hi @tarhi-saad, it would be great if you could send me the credentials to your JN site via DM in Slack. I'll take a look then.

2023-10-21 08:16 UTC, nielslange commented
Closing this PR as the issue is related to the `BlockTemplatesController`, see pca54o-6sH-p2#comment-5886.

2023-10-21 08:16 UTC, closed without merging