Add rounded borders to product images on TT4
woocommerce/woocommerce-gutenberg-products-block pull request #11447
Opened 2023-10-25 10:32 UTC by sunyatasattva

## What

This PR adds rounded borders as default to product images in the context of the TT4 theme.

Fixes #11328

## Why

We want to ship with the best possible TT4 default experience: TT4 uses a rounded-borders aesthetic throughout. In order to better fit into the default experience of the theme, we include this aesthetic as a default on our images.

Note that we are not adding rounded borders where they couldn't be overridden by the user (e.g. “All Products” block) as this could cause frustration to the user.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Activate the TT4 theme.
2. Add “Single Product”, “Featured Product”, “Featured Category”, “Product Collection” and other blocks containing product images to a page.
3. Ensure that the images show a default border radius which is in line with TT4 images.
4. Ensure that it can be overridden by the user via the inspector controls.
5. Ensure that only blocks including images whose border-radius styles can be overridden by the user are affected by this change.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

2023-10-25 18:52 UTC, roykho approved these changes
LGTM!

2023-10-27 09:10 UTC, nerrad requested changes
Any theme-specific CSS should not go in the block files but instead into a dedicated CSS file in WooCommerce core (see [examples for other themes here](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/client/legacy/css)). I think @xristos3490 might be doing some relevant work for that as well so it'd be good to co-ordinate with him in case he's already created a PR adding a tt4 specific CSS file.

Outside of that, I wonder if we should even be adding these specific styles. Ideally, this kind of design element in the block itself would adapt to whatever borders themes set on images (i.e. this should not be tied to a specific theme, but rather the design tokens set in the `theme.json`).

2023-10-30 06:19 UTC, sunyatasattva commented
Hey @nerrad !

Thank you for the insight about design tokens. I'm not fully sure on how we should implement them, however: the example you provided is about a `rounded` variation of the image, while the [featured image block comes with a default border](https://github.com/WordPress/twentytwentyfour/blob/61a733f9d1050c131c3b711b7a9131f08db34b33/theme.json#L597). How should we add this default border to our “image-like” blocks? I saw [a conversation](https://github.com/WordPress/gutenberg/issues/41707) where you participated about a similar issue. Even in the proposal, however, it would not be possible to add theme-specific defaults. Do you have something in mind?

Re: the theme-specific styles, I wholeheartedly agree and meant to open a GitHub discussion on where to put them. As it currently stands, however, there are many examples of that in our repo, so we might want to refactor them out (you can have a search for `twentytwenty` to see them). Some of them are in block files, other in generic CSS files.

2023-10-30 11:27 UTC, nerrad commented
> How should we add this default border to our “image-like” blocks?
It would need to be explored, but I'm suggesting there'd be some code server-side that would read the active `theme.json` and apply any adjustments to our blocks that require CSS (as opposed to style attributes) to custom CSS generated server-side dynamically. 

Even there though, you'd need to account for user styles that might override `theme.json` (which is also not accounted for by the CSS changes in this PR).

> Re: the theme-specific styles, I wholeheartedly agree and meant to open a GitHub discussion on where to put them. As it currently stands, however, there are many examples of that in our repo, so we might want to refactor them out (you can have a search for twentytwenty to see them). Some of them are in block files, other in generic CSS files.

Yeah, that's unfortunate, I don't think we should refactor all the older ones out, but let's make sure TT4 adjustments are in Woo core only.

2023-10-31 11:35 UTC, sunyatasattva commented
> Even there though, you'd need to account for user styles that might override theme.json (which is also not accounted for by the CSS changes in this PR).

I'll close this PR for now, then. Just wanted to briefly mention that user styles (if you mean styles added through Inspector Controls) do indeed override these CSS rules, and it was one of the testing steps in the description.

I'll align with Chris on how to proceed with this :)

2023-10-31 11:35 UTC, closed without merging