Migration of the Product Button to the new `store()` API
woocommerce/woocommerce-gutenberg-products-block pull request #11558
Opened 2023-11-02 16:28 UTC by luisherranz

## What

Migrates the Product Button block to the new store() API.

Resources:

- https://github.com/woocommerce/woocommerce-blocks/issues/11065
- https://github.com/woocommerce/woocommerce-blocks/pull/11071
- https://github.com/WordPress/gutenberg/discussions/53586

## Why

Because we are switching from the old `store()` API to the new `store()` API, and we need to migrate all the blocks at once.

## Testing Instructions

1. Load a template that contains with Product Button blocks
2. Test that it keeps working as exactly as it is working on `trunk`

## Screenshots or screencast

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

Migrate the Product Button to the new `store()` API of the Interactivity API.

2023-11-09 10:11 UTC, luisherranz commented
I think I'm going to leave the type of the async `addToCart` action as `() => void` instead of `() => Generator` for now, as it probably makes less sense to make TS think that that function returns a generator when it doesn't.

I've documented this along with the need to cast getters in the original discussion:

- https://github.com/WordPress/gutenberg/discussions/53586#discussioncomment-7520599

2023-11-09 13:43 UTC, DAreRodz commented
The Product Collection block has required insignificant changes, so I included them in this PR instead of creating a new one.

I've updated the PR's title and description to reflect that. 🙂

2023-11-10 09:13 UTC, imanish003 approved these changes
I've just finished testing the changes and I'm happy to report that everything is working perfectly! 🚀 Before we go ahead with merging the PR, it would be awesome to get a thumbs-up from either Luigi or Albert as well 🙂

By the way, a big shoutout to Luis for the attached video - it was super helpful and explained things brilliantly. Kudos to you! 🙌🏻

2023-11-10 09:13 UTC, imanish003 commented on assets/js/atomic/blocks/product-elements/button/frontend.tsx
> +const getTextButton = (
Nitpicking: The function's name initially led me to expect it would yield a TextButton component, but it appears to actually return a string for display on a Button. Perhaps a rename to `getButtonText` or `getButtonTextBasedOnCartQuantity` could be more descriptive. However, please feel free to disregard this suggestion if you have a different perspective 🙂.

2023-11-10 09:13 UTC, imanish003 commented on src/BlockTypes/ProductCollection.php
> +				$p->set_attribute( 'data-wc-interactive', wp_json_encode( array( 'namespace' => 'woocommerce' ) ) );
Just curious, We are using `woocommerce/product-button` namespace for Product button, but we aren't using `woocommerce/product-collection` for Product Collection block. Is it because we are just using client-side pagination, therefore, it doesn't have to do much with Store? 
Additionally, why can't we simply use true as a value? Does this relate to recent modifications in the Store API?

2023-11-10 14:35 UTC, Aljullu reviewed
I really like how the code gets much simpler with these changes, good job @luisherranz!

The code changes look good to me and I did some smoke testing and everything is working as expected. However, I don't have much experience in how the Interactivity API worked before, so I would also like if @gigitux can take a look and give his approvall.

By the way, before merging there will need to be some changes to the PR itself: `WooCommerce Visibility` should be `WooCommerce Core` and we should add a `type` label (I guess `type: enhancement`?).

2023-11-10 14:35 UTC, Aljullu commented on assets/js/atomic/blocks/product-elements/button/frontend.tsx
> +					state.inTheCartText!,
Heads-up that there is an ESLint warning in this line and L121.

2023-11-13 09:34 UTC, luisherranz commented on src/BlockTypes/ProductCollection.php
> +				$p->set_attribute( 'data-wc-interactive', wp_json_encode( array( 'namespace' => 'woocommerce' ) ) );
> we aren't using woocommerce/product-collection for Product Collection block

Yeah, we're testing "block-based store parts". So let's switch to `woocommerce/product-collection` here as well.

_It's true that now the logic is abstracted in a `data-wc-link` directive, but we'll eventually replace it with custom store logic once you start adding things like loading indicators or accessibility, similar to what we did for the [Query block](https://github.com/WordPress/gutenberg/blob/c20462652e63ea3f9769ae8694ad8f48509f40b3/packages/block-library/src/query/view.js#L35-L78)._

> why can't we simply use true as a value? Does this relate to recent modifications in the Store API?

Yes, blocks now have a default namespace.

2023-11-13 11:00 UTC, gigitux requested changes
Thanks for your precious work and the helpful video!

I just added a NIT, feel free to skip it! However, I noticed two things:

- A Circular dependency is detected:
<img width="878" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/4463174/4a0e4bcc-8fb7-4198-aa1e-ea44d85ee6ac">

- Currently, there is an E2E test that fails: "21 [blockTheme] › product-collection/product-collection.block_theme.spec.ts:29:2 › Product Collection › Renders product collection block correctly with 9 items (27.0s)". I already re-run it, but it failed again:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/d93ce2b6-6404-43e0-a52d-c2c3060bc599)

2023-11-13 11:00 UTC, gigitux commented on src/BlockTypes/ProductButton.php
> +				'namespace' => 'woocommerce/product-button',
NIT: We could use using the variables to compose the namespace:

```suggestion
				'namespace' => $this->namespace . "/" . $this->block_name,
```

2023-11-13 11:05 UTC, luisherranz commented
> A Circular dependency is detected

We can [turn CHECK_CIRCULAR_DEPS off](https://github.com/woocommerce/woocommerce-blocks/blob/01015242dcd3b31da7d49f691062c4d3fe46e735/bin/webpack-configs.js#L40) in [the Interactivity API config](https://github.com/woocommerce/woocommerce-blocks/blob/01015242dcd3b31da7d49f691062c4d3fe46e735/bin/webpack-configs.js#L926).

2023-11-13 11:14 UTC, gigitux commented
> > A Circular dependency is detected
> 
> We can [turn CHECK_CIRCULAR_DEPS off](https://github.com/woocommerce/woocommerce-blocks/blob/01015242dcd3b31da7d49f691062c4d3fe46e735/bin/webpack-configs.js#L40) in [the Interactivity API config](https://github.com/woocommerce/woocommerce-blocks/blob/01015242dcd3b31da7d49f691062c4d3fe46e735/bin/webpack-configs.js#L926).

I didn't check the code, but circular dependency could introduce some issues that could be hard to find/debug. I would be more oriented to fix the circular dependency, but it is just an opinion based on my past experience.

2023-11-13 11:28 UTC, luisherranz commented
Oh, sorry, I didn't explain myself well enough. I wouldn't suggest changing how you manage your code. But that warning comes from the Interactivity API code, so it's ok to remove that circle dep check.

2023-11-13 11:34 UTC, gigitux commented
> Oh, sorry, I didn't explain myself well enough. I wouldn't suggest changing how you manage your code. But that warning comes from the Interactivity API runtime, so it's ok to remove that circle dep check in the specific Webpack config of the Interactivity API runtime. It won't affect any Woo code.

Yeah, I got it! 
My suggestion was to fix it, even if it is in the Interactivity API runtime (not a blocker for this PR). But as I said, it is just an opinion that I have on circular dependency based on past experience :D

2023-11-13 11:44 UTC, DAreRodz commented on assets/js/atomic/blocks/product-elements/button/frontend.tsx
> +const getTextButton = (
Makes total sense. I'll update it to `getButtonText`.

2023-11-13 11:46 UTC, DAreRodz commented on src/BlockTypes/ProductCollection.php
> +				$p->set_attribute( 'data-wc-interactive', wp_json_encode( array( 'namespace' => 'woocommerce' ) ) );
I'll change the namespace to `woocommerce/product-collection`. 🙂

2023-11-13 11:49 UTC, DAreRodz commented on assets/js/atomic/blocks/product-elements/button/frontend.tsx
> +const getTextButton = (
Fixed in https://github.com/woocommerce/woocommerce-blocks/commit/5938fef6a1411a6aab5957a24bacf201509b6e18.

2023-11-13 11:49 UTC, DAreRodz commented on src/BlockTypes/ProductCollection.php
> +				$p->set_attribute( 'data-wc-interactive', wp_json_encode( array( 'namespace' => 'woocommerce' ) ) );
Fixed in https://github.com/woocommerce/woocommerce-blocks/commit/cefa07cc6ea24245517df4c6fde56050e61efc79.

2023-11-13 11:53 UTC, luisherranz commented
Thanks, Luigi. For now, we're trying to make things work and want to keep iterating fast. We'll make them _pretty_ after we move them to Gutenberg and we are about to merge them with WP Core 🙂

2023-11-13 12:27 UTC, DAreRodz commented
> By the way, before merging there will need to be some changes to the PR itself: `WooCommerce Visibility` should be `WooCommerce Core` and we should add a `type` label (I guess `type: enhancement`?).

I've updated the visibility and the type label. Feel free to modify them as needed. 🙂

BTW, this branch uses another PR as the base branch, but I added the changes just in case we decide to merge the base branch first to `trunk`.

2023-11-13 13:37 UTC, gigitux commented
With [1a3d9ca](https://github.com/woocommerce/woocommerce-blocks/pull/11558/commits/1a3d9ca50167a3af26ea49b6b20f56b27a80b914) I fixed the E2E test failure. For more details, check [this issue](https://github.com/woocommerce/woocommerce-blocks/issues/10102) (we should use `WP_HTML_Tag_Processor`). The other E2E tests fail due to the Product Gallery block and it is outside of the scope of this PR.

> Thanks, Luigi. For now, we're trying to make things work and want to keep iterating fast. We'll make them pretty after we move them to Gutenberg and we are about to merge them with WP Core

Thanks for the clarification. It makes sense 👍

2023-11-13 13:38 UTC, gigitux approved these changes
LGTM! Thanks for your work!

2023-11-16 22:45 UTC, merged

2023-11-16 22:52 UTC, DAreRodz commented
I've merged it even though some tests did not pass. 🤔 

To be honest, I'm wondering if they were failing because of a real issue in the code, because everything was green in https://github.com/woocommerce/woocommerce-blocks/pull/11721 and that branch already contained all the changes from this one (https://github.com/woocommerce/woocommerce-blocks/pull/11558), so they should be equivalent once it was merged here.