Product Gallery Dialog: Change names of dialog actions and move them …
woocommerce/woocommerce-gutenberg-products-block pull request #11640
Opened 2023-11-06 23:32 UTC by danieldudzic

…from the Large Image to the Product Gallery frontend file

## What

Fixes #11311

## Why

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1.
2.
3.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

2023-11-08 13:48 UTC, roykho requested changes
So there is a regression here. I can no longer click on the gallery thumbnails to change the main image.

2023-11-08 16:25 UTC, thealexandrelara requested changes
Looks good! I added a comment regarding the `handleClick` function for the Thumbnails block that is currently not working.

2023-11-08 16:25 UTC, thealexandrelara commented on src/BlockTypes/ProductGalleryThumbnails.php
> +									'actions.woocommerce.thumbnails.dialog.openDialog'
I believe that when changing the `handleClick` for the dialog, the editor also changed this that is related to the `thumbnails` by mistake and it causes the Thumbnails to not be clickable anymore.

2023-11-08 22:05 UTC, danieldudzic commented
@roykho @thealexandrelara Thank you for your reviews. I have now fixed the regression and updated other actions too, to follow the same semantic naming pattern. Please let me know if you'd change anything.

2023-11-09 21:58 UTC, roykho reviewed
So I guess the only concern I have is the consistency. Because `dialog` has its own sub action but the others do not. So either we use sub actions for example `dialog` for all things housed inside the dialog component and for example `nextPrevious` for all things that belong there such as the `selectNextImage`...etc.

2023-11-09 23:27 UTC, thealexandrelara commented
> So I guess the only concern I have is the consistency. Because `dialog` has its own sub action but the others do not. So either we use sub actions for example `dialog` for all things housed inside the dialog component and for example `nextPrevious` for all things that belong there such as the `selectNextImage`...etc.

I agree with you. Since we now have more descriptive names (`openDialog` and `closeDialog`), maybe we don't need the `dialog` key anymore?

2023-11-10 07:50 UTC, danieldudzic commented
> I agree with you. Since we now have more descriptive names (`openDialog` and `closeDialog`), maybe we don't need the `dialog` key anymore?

That makes sense and would be my preference.

2023-11-10 21:42 UTC, danieldudzic commented
I'm closing this PR, as this is being already addressed in the migration to the new Interactivity API store: https://github.com/woocommerce/woocommerce-blocks/pull/11721

2023-11-10 21:42 UTC, closed without merging