Fix casting error on Utils::wp_version_compare
woocommerce/woocommerce-gutenberg-products-block pull request #11802
Opened 2023-11-16 05:29 UTC by alefesouza

## What

Fixes #10563

## Why

Fix casting error on `Utils::wp_version_compare` when using a different PHP locale.

## Testing Instructions

While testing with `version_compare` with the French locale I could reproduce the errors mentioned on #10563, it looks like it didn't affect `Utils::wp_version_compare` method but as mentioned here: p1692776050961299/1692773342.122439-slack-C8X6Q7XQU it's fine to fix it defensively.

1. On a PHP 7.4 environment, on WordPress installation root run `php -a`
2. Run `setlocale(LC_ALL, 'fr_FR');`
3. Run `var_dump((float)6.4);`
4. If the output is not `float(6,4)` (with the comma instead of dot), you need to install the fr_FR locale, for Docker you can run it on your container:

```
apt-get update && apt-get install -y locales && apt-get clean
sed -i -e 's/# fr_FR ISO-8859-1/fr_FR ISO-8859-1/' /etc/locale.gen
dpkg-reconfigure --frontend=noninteractive locales
docker-php-ext-install gettext
```

5. If you needed to install the above package, redo the first three steps.
6. Run `require_once 'wp-load.php';`
7. Run `require 'wp-content/plugins/woo-gutenberg-products-block/src/Utils/Utils.php'`
8. Run `var_dump(\Automattic\WooCommerce\Blocks\Utils\Utils::wp_version_compare(6.4, '='));`, changing the parameters, all output should run as expected, to simulate WordPress version you can run: `global $wp_version; $wp_version = '6.4.0';`

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:

* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

2023-11-17 20:52 UTC, hsingyuc approved these changes
@alefesouza Thank you for working on this!  I tested with a patch version and the existing code looks like it's not set up to match patches.  Since that seems expected, this PR LGTM.

2023-12-07 09:35 UTC, tarhi-saad requested changes
Thank you for working on this PR, @alefesouza! The regex is correct, but, the version number that we should apply it to is the one we get from the `get_bloginfo`. When I tested I was still getting the same error. Maybe we should apply a `preg_replace` in line 25!

2023-12-07 14:29 UTC, alefesouza commented
@tarhi-saad fixed on https://github.com/woocommerce/woocommerce-blocks/pull/11802/commits/ef429f16ba40c7ce725d663afba605cdd7ad0e25.

2023-12-07 16:48 UTC, tarhi-saad approved these changes
Hey, @alefesouza! 👋 Thanks a lot for taking care of this! 🙌 I'll merge the PR after the CI checks are done! 🎉

2023-12-07 17:18 UTC, merged