Investigate E2E CI caching issue
woocommerce/woocommerce-gutenberg-products-block pull request #11874
Opened 2023-11-22 06:50 UTC by nielslange

## What

Fixes #

## Why

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1.
2.
3.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:

* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

2023-11-24 16:53 UTC, tarhi-saad requested changes
Thank you for working on this PR, @nielslange! The main issue is fixed. I added some comments below regarding the unskipped tests.

2023-11-24 16:53 UTC, tarhi-saad commented on tests/e2e/tests/templates/cart-template.block_theme.spec.ts
> +	test( 'Template can be accessed from the page editor', async ( {
This test should be skipped. The #11671 was closed by mistake. It was automatically closed because it was mentioned in another PR.

2023-11-24 16:53 UTC, tarhi-saad commented on tests/e2e/tests/templates/cart-template.block_theme.spec.ts
> +		await page.getByLabel( 'Template options' ).click();
We should click the `Edit template` option after clicking on the `template options` label.

2023-11-24 16:53 UTC, tarhi-saad commented on tests/e2e/tests/templates/checkout-template.block_theme.spec.ts
> +	test( 'Template can be accessed from the page editor', async ( {
Same here! We should skip this test. This ticket is still relevant: #11671

2023-11-24 17:11 UTC, tarhi-saad requested changes
@nielslange, could you fix the TS errors if the function `admin.visitSiteEditor()` in the Cart and Checkout templates. These errors were introduced in #11866.

2023-11-27 06:27 UTC, nielslange commented
Thanks for your review, @tarhi-saad. I've address all your feedback and ensured that the tests are still passing. You can do another review now.

2023-11-27 20:23 UTC, tarhi-saad approved these changes
Thank you for the changes, @nielslange! 🙌 LGTM! 🚀

2023-11-28 07:16 UTC, merged