replace Stories root to External Components
woocommerce/woocommerce-gutenberg-products-block pull request #11910
Opened 2023-11-22 22:29 UTC by arsanyjoseph

## What

Fixes #

## Why

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1.
2.
3.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:

* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

2023-11-23 00:55 UTC, opr requested changes
@arsanyjoseph hi thank you for taking the time to work on this the changes look great so far!

Please could you update the body of your PR so the "What", "Why" and "Testing Instructions" sections are complete?

Also, please would you update the paths of the story for: `Button`  which is found in `assets/js/base/components/button/stories`?

Thanks! 🙏🏼

2023-11-24 13:40 UTC, arsanyjoseph commented
@opr What should Button stories updated to ? It is currently Base Components

2023-11-24 13:42 UTC, opr commented
> @opr What should Button stories updated to ? It is currently Base Components

Please also update this to `External Components` like the others - even though we didn't move this component, it's still available through the `@woocommerce/block-components` package, so we'd like to include it there.

Thank you!

2023-11-24 13:44 UTC, arsanyjoseph commented
@opr I updated the What Section 
Not sure how to fill in the remaining sections.
any help ?

2023-11-24 14:36 UTC, opr commented
> @opr I updated the What Section Not sure how to fill in the remaining sections. any help ?

No problem, for the "What" section, let's include a "Fixes https://github.com/woocommerce/woocommerce-blocks/issues/11908" section so the issue will be closed.

For the "Why" section, let's use

> To ensure the documentation for components in the components package are grouped together to make it easier for readers to find them.

Testing instructions could be:

> 1. Run `npm run storybook`
> 2. Go to `localhost:6006`
> 3. Ensure none of the components exported in the components package appear in "Base components" or "Editor components" sections.

2023-11-27 12:14 UTC, opr approved these changes
@arsanyjoseph thank you for working on this! I'll approve and merge this PR for you.

I appreciate your efforts here 🙏🏼

2023-11-27 12:14 UTC, merged