Add missing actions to the documentation
woocommerce/woocommerce-gutenberg-products-block pull request #11986
Opened 2023-11-29 15:02 UTC by tarunvijwani

- Add the missing actions to the following:

- data-store/cart
- data-store/checkout
- data-store/collections
- data-store/validation

## What

Fixes #11337

## Why

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1.
2.
3.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:

* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

2023-11-30 07:52 UTC, nielslange reviewed
Thanks for working on this, @tarunvijwani. To make the docs easy accessible, I suggest that we use consistent formatting throughout our docs. I left a few notes with examples.

2023-11-30 07:52 UTC, nielslange commented on docs/third-party-developers/extensibility/data-store/cart.md
> +-   `cartData: Object`: The new cart data.
For consistency-reasons, I suggest using the same formatting as we use in our other docs, e.g.
https://github.com/woocommerce/woocommerce-blocks/blob/6960ae656112b5a5249673db2aaa80e13c4b94c7/docs/third-party-developers/extensibility/data-store/collections.md?plain=1#L33-L40

What are your thoughts on documenting the inner structure of the `cartData` object, similar to what we're doing in https://github.com/woocommerce/woocommerce-blocks/blob/6960ae656112b5a5249673db2aaa80e13c4b94c7/docs/third-party-developers/extensibility/data-store/cart.md?plain=1#L188-L195

2023-11-30 07:52 UTC, nielslange commented on docs/third-party-developers/extensibility/data-store/cart.md
> +-   `Object`: The action object.
Similar to the _Parameters_, what are your thoughts on documenting the inner structure of the objects within the _Returns_ sections? 

Here are two examples of other docs:

https://github.com/woocommerce/woocommerce-blocks/blob/6960ae656112b5a5249673db2aaa80e13c4b94c7/docs/third-party-developers/extensibility/data-store/collections.md?plain=1#L52

https://github.com/woocommerce/woocommerce-blocks/blob/6960ae656112b5a5249673db2aaa80e13c4b94c7/docs/third-party-developers/extensibility/data-store/collections.md?plain=1#L69-L74

2023-11-30 07:52 UTC, nielslange commented on docs/third-party-developers/extensibility/data-store/cart.md
> +-   `isPending: boolean`: The new status of whether the cart item quantity is being updated. Defaults to `true`.
As mentioned earlier, for consistency-reasons, I'd use the same format we're using for our other docs. Here's an example of how other docs display default values and allowed values: https://github.com/woocommerce/woocommerce-blocks/blob/6960ae656112b5a5249673db2aaa80e13c4b94c7/docs/third-party-developers/extensibility/checkout-block/available-filters/coupons.md?plain=1#L149-L155

2023-11-30 07:52 UTC, nielslange commented on docs/third-party-developers/extensibility/data-store/cart.md
> +-   `isResolving: boolean`: The new status of whether the customer data is being updated.
"The new status" sounds a bit strange. For consistency-reasons, I'd use the similar wording for all boolean parameters and returns. Here are two examples of other docs:

https://github.com/woocommerce/woocommerce-blocks/blob/6960ae656112b5a5249673db2aaa80e13c4b94c7/docs/third-party-developers/extensibility/checkout-block/available-filters/coupons.md?plain=1#L84

https://github.com/woocommerce/woocommerce-blocks/blob/6960ae656112b5a5249673db2aaa80e13c4b94c7/docs/third-party-developers/extensibility/checkout-block/available-filters/coupons.md?plain=1#L151

2023-12-05 20:53 UTC, tarunvijwani commented
@nielslange Thank you so much for the suggestions! They were really helpful. I have updated the docs, please take a moment to review the PR again.

2023-12-06 06:47 UTC, nielslange requested changes
Except for one missing parameter name, the PR looks great, @tarunvijwani.

2023-12-06 06:47 UTC, nielslange commented on docs/third-party-developers/extensibility/data-store/checkout.md
> +-   `boolean`: True if the shopper prefers to collect their order.
```suggestion
-   _prefersCollection_ `boolean`: True if the shopper prefers to collect their order.
```

2023-12-06 07:48 UTC, tarunvijwani commented
Good catch, @nielslange. Thank you! I have applied your suggestions. 🎉

2023-12-06 08:33 UTC, nielslange approved these changes
Thanks for applying all changes. Let's ⛴️ this PR now, @tarunvijwani! 🙌

2023-12-06 08:58 UTC, merged