Product gallery/fix/view all link
woocommerce/woocommerce-gutenberg-products-block pull request #11995
Opened 2023-11-29 20:55 UTC by roykho

## What

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/11988

This PR adds specific styling to the "View All" link and thumbnails count depending on how many thumbnails are displayed.

- When set to 3 - 5 thumbnails both thumbnail count and "View All" link is shown.
- When set to 6 - 8 thumbnails only count is shown because "View All" link doesn't have enough space to display nicely.

## Why

This is so that shoppers will have a better visual experience and not have the "View All" link out of place or not showing completely.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Go to Appearance->Editor->Templates->Single Product.
2. Add the Product Gallery block.
3. Go to a product in the frontend with 8 gallery images added.
4. Ensure you see both the "Count" and "View All" link and are displayed nicely.
5. Go back to the Editor Product Gallery block and change to show 8 thumbnails.
6. Go back to the frontend product with 8 gallery images.
7. Ensure you see only the "Count" being displayed and that it is showing nicely and centered.

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|![file.png](https://github.com/woocommerce/woocommerce-blocks/assets/2132595/5d61b08d-2ae1-481b-8e33-d298eb61584a)        |![file.png](https://github.com/woocommerce/woocommerce-blocks/assets/2132595/64fc45cb-2a48-4b84-9115-2c19cc0bd837)       |

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental
* [ ] N/A

## Checklist

Required:

* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

2023-11-30 17:16 UTC, danieldudzic requested changes
I'd rethink the sizing of the View all overlay text.

Is there a way we can make the font-size a bit more fluid?

The Product Gallery might be used for larger widths, and that might result with a very small `View all` text with a static font size:

<img width="910" alt="Moto_Guzzi_v7_–_newproductgallery" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/72f08f53-d868-4cfc-87e0-48a579a5ce58">

2023-11-30 17:16 UTC, danieldudzic commented on src/BlockTypes/ProductGalleryThumbnails.php
> +						'<div class="wc-block-product-gallery-thumbnails wp-block-woocommerce-product-gallery-thumbnails %1$s wc-block-product-gallery-thumbnails__total-count-%2$s" style="%3$s" data-wc-interactive=\'%
I don't think it's necessary to add this additional class for tracking the number of thumbnails.

You can utilize the attribute that's on the parent Product Gallery element.

```
		#{$gallery}[data-thumbnails-number-of-thumbnails='4'] & {

		}
```

Note: this class is not present when the number of thumbnails is default, that is `3`.

2023-11-30 17:16 UTC, danieldudzic commented on assets/js/blocks/product-gallery/style.scss
> +	}
You can use a loop to make the code a bit more concise:

```
	@for $i from 3 through 8 {
		#{$gallery}[data-thumbnails-number-of-thumbnails='#{$i}'] & {

		}
	}
```

2023-12-04 22:52 UTC, danieldudzic commented
At request from @roykho I'm taking over this PR.

2023-12-04 23:14 UTC, danieldudzic commented
@roykho Would you mind reviewing? 🙏

2023-12-05 13:52 UTC, roykho reviewed
@danieldudzic changes looks good!

2023-12-05 15:24 UTC, danieldudzic approved these changes

2023-12-05 15:25 UTC, merged