Update Features Flags and Experimental Interfaces doc with Collection Filters and its inner blocks
woocommerce/woocommerce-gutenberg-products-block pull request #12047
Opened 2023-12-05 10:50 UTC by kmanijak

## What

Update Features Flags and Experimental Interfaces doc with Collection Filters and its inner blocks.

## Why

Keep the doc up to date and make the tracking of flags easier.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Check whether newly added links redirect to the flags
2. Verify MD file is formatted correctly

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [x] N/A

## Checklist

Required:

* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

2023-12-06 17:44 UTC, danieldudzic requested changes
I'd recommend changing links to point to a specific commit, rather than to `trunk`, because in the future, as content is added or removed, the specific lines you are referring to may become incorrect.

2023-12-07 10:31 UTC, kmanijak commented
> I'd recommend changing links to point to a specific commit, rather than to trunk, because in the future, as content is added or removed, the specific lines you are referring to may become incorrect.

Good call! I updated the links @danieldudzic

2023-12-08 08:33 UTC, dinhtungdu approved these changes
LGTM! Thank you so much for working on this. I will add missing JS flags to new filters in followup PR.

2023-12-08 09:10 UTC, danieldudzic approved these changes

2023-12-08 09:10 UTC, merged