Convert PaymentMethodErrorBoundary to Class component
woocommerce/woocommerce-gutenberg-products-block pull request #12088
Opened 2023-12-07 21:28 UTC by tarunvijwani

## What
Related #10565 

## Why

We converted the PaymentMethodErrorBoundary Class component to the function component, and it stopped working. The issue was introduced by https://github.com/woocommerce/woocommerce-blocks/pull/9817 PR.

As per the react docs:

>There is currently no way to write an error boundary as a function component. However, you don’t have to write the error boundary class yourself. For example, you can use react-error-boundary instead.

src: https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary

In this PR, we're converting the function component to the Class component. 

#### We will handle removing the entire express payment block if no valid express payment button exists in a different PR.

## Testing Instructions

1. Enable express checkout payment buttons
2. Go to line https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.js#L166
3. Replace it with the below code:

```js
        const ErrorThrower = () => {
		throw new Error( 'Test error for PaymentMethodErrorBoundary' );
	};

	return (
		<PaymentMethodErrorBoundary isEditor={ isEditor }>
			<ul className="wc-block-components-express-payment__event-buttons">
				{ content }
			</ul>
			<ErrorThrower />
		</PaymentMethodErrorBoundary>
	);
```
5. Visit the checkout page
6. Confirm empty express checkout block is visible.
7. Check browser console and confirm error is visible in browser console.

* [ ] Do not include in the Testing Notes 
* [x] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/2aa03081-2e42-4a99-afb1-1de4f643a7f6)|![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/b6bf6fff-f245-4103-920d-5a1767ba04c2)|

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:

* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Convert PaymentMethodErrorBoundary to Class component

2023-12-08 15:22 UTC, tarhi-saad requested changes
Thank you, @tarunvijwani, for working on this PR! The tests are working as expected. The code mostly looks good. I left a minor suggestion below!

2023-12-08 15:22 UTC, tarhi-saad commented on assets/js/blocks/cart-checkout-shared/payment-methods/payment-method-error-boundary.tsx
> +	expressPaymentMethodId = this.props.expressPaymentMethodId;
@tarunvijwani, it seems that the variable `expressPaymentMethodId` is not used anywhere. Should we consider removing this line, or is there a specific reason for its inclusion?

2023-12-08 15:28 UTC, tarunvijwani commented on assets/js/blocks/cart-checkout-shared/payment-methods/payment-method-error-boundary.tsx
> +	expressPaymentMethodId = this.props.expressPaymentMethodId;
@tarhi-saad Nice catch! `expressPaymentMethodId` will be used in further iteration when we hide the express payment button that has an error. I have removed it from this PR.

2023-12-08 16:10 UTC, tarhi-saad approved these changes
LGTM!

2023-12-08 16:28 UTC, merged

2023-12-12 09:39 UTC, ralucaStan commented
@tarunvijwani could you update the Screenshots or screencast with the final result? The image in the PR description with the after result does not reflect the changes brought in by this PR

2023-12-12 09:47 UTC, tarunvijwani commented
@ralucaStan We are breaking down the solution into multiple PRs. This PR is the first part of the https://github.com/woocommerce/woocommerce/issues/42256, and it only fixes the existing error by converting the PaymentMethodErrorBoundary Class component to the function component. 
The final result of this PR is the after-screen.
We will be hiding the express payment button if it encounters any errors and addressing other scenarios as well in further PRs.