sync shipping with billing when shipping is disabled
woocommerce/woocommerce-gutenberg-products-block pull request #3593
Opened 2020-12-23 11:33 UTC by senadir

This PR syncs shipping with billing when shipping is disabled.

Fixes https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3592

### How to test the changes in this Pull Request:

1.
2.
3.

### Changelog

> Add suggested changelog entry here.

2020-12-23 11:58 UTC, opr requested changes
✅ Great fix, these cases work:
- [x] Shipping fully disabled (no methods in back end)
- [x] Shipping enabled and using shipping as billing
- [x] Shipping enabled and entering different addresses for shipping and billing

My orders in the back end all have the correct shipping address for these cases.

❌ However this flow does not:
1. Open an incognito window, add a physical product to cart and continue to checkout, use shipping address for billing. Checkout should succeed.
2. Stay logged in, and add a downloadable product to the cart.
3. Go to checkout, notice that billing should already be filled, and you should see no shipping fields.
4. Try to check out
5. See "Country is required" error

2020-12-23 14:05 UTC, opr approved these changes
Worked great for me, all the above cases work ok too.

2020-12-23 15:10 UTC, merged

2020-12-24 11:24 UTC, senadir commented
@mikejolley This PR also touches on the code you worked on and is probably a regression, take a look at in when you're back.

2021-01-04 12:00 UTC, mikejolley commented
@senadir was this to fix what you raised in this comment? https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3552#discussion_r547893742

Another solution may have been to not send the empty address to the API if disabled, which would avoid syncing data. We could probably add test coverage against this?

2021-01-04 12:19 UTC, senadir commented
> @senadir was this to fix what you raised in this comment? #3552 (comment)

Yes

> Another solution may have been to not send the empty address to the API if disabled,

Sync would still happen on the backend, I'd prefer we don't sync in the client-side as well.
Wouldn't emitting sending shipping data trigger a validation error as well?

2021-01-04 13:41 UTC, mikejolley commented
@senadir When I tested this, if you left the address completely blank, or left it out of the request, the validation/sanitization would not throw errors. We can tweak this if this approach is preferred - I'd prefer sync on the server side since it enforces the correct data shape for orders rather than us doing it manually in client.

2021-01-04 13:50 UTC, senadir commented
> I'd prefer sync on the server side since it enforces the correct data shape for orders rather than us doing it manually in client.

It's also one less thing to think about when implementing Store API in other places.

> We can tweak this if this approach is preferred 

Yes, I think this is better.