Rest API batching support
woocommerce/woocommerce-gutenberg-products-block pull request #3899
Opened 2021-03-01 17:05 UTC by mikejolley

This PR implements batching in the Store API, and a dataloader class in the client to batch requests within a certain interval.

Batching works for POST, PUT, DELETE API requests. GET requests are not affected.

As well as adding the batching, [this commit](https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/d0b901b06174aa514efaf23bec1482db13f6b276) creates a control to handle fragment updates and adds a timeout. This prevents multiple fragment updates after a batch of events have ran.

NOTE: I am requested feedback/code review, but 2 things are left to do before it can be merged:

- [ ] Check what happens if nonce changes on items in the batch.
- [ ] Reduce batch timeout from 3000 - I have left this high to make testing easier.

Fixes #2094

### How to test the changes in this Pull Request:

1. Go to the products page.
2. Add to items to the cart really quickly. If you focus a button with the keyboard you can hit enter and click another button.
3. Check the network request for a "batch" API call. You'll see 2 responses in an array.
4. Smoke test cart page functionality/cart/checkout. All should be unaffected.

2021-03-15 13:18 UTC, senadir requested changes
I didn't do a code review yet.

While testing cart, I can't do any action, the response is coming back with `woocommerce_rest_missing_nonce` error but no notice is visible.

I'm getting the same error in All Products with an empty red notice
![image](https://user-images.githubusercontent.com/6165348/111159394-59eb1080-8599-11eb-9009-17de83e79eac.png)

2021-03-19 12:49 UTC, mikejolley commented
@senadir I think you have a build issue, I'm not seeing that at all, and tests don't indicate a problem.

2021-03-19 14:29 UTC, mikejolley commented
I've pushed some changes to make nonce-validation run earlier so it cannot change during a batch request.

2021-03-22 16:34 UTC, opr reviewed
This looks good to me, I tested it and see the requests are batched. I left one nitpick comment about TypeScript. 

Code wise everything looks fine, but could we add some PHP unit tests for the batch route?

2021-03-22 16:34 UTC, opr commented on assets/js/data/cart/actions.ts
> +export function updateCartFragments() {
nit: If you write this as a function expression rather than a function declaration you would not get a lint warning.

2021-04-09 16:27 UTC, mikejolley commented
@opr thanks! I've added some tests for this batch endpoint and reduced the timeout to 200ms. Should be good to go if you're happy.

2021-04-13 12:57 UTC, opr approved these changes
> @opr thanks! I've added some tests for this batch endpoint and reduced the timeout to 200ms. Should be good to go if you're happy.

Nice, the tests look good Mike! Thanks 🥳

2021-04-16 12:45 UTC, mikejolley commented
This PR is failing e2e tests in the cart, but testing manually I see no issues. I think this is just e2e timeout-related rather than a new bug. I will merge...

2021-04-16 12:45 UTC, merged

2021-04-18 15:21 UTC, nerrad commented
@mikejolley I had to revert (done through git client not GitHub) this work in trunk for the following reasons:

- The e2e test failures were legit. The Cart Update middleware added in #3960 is broken with these changes.
- Updating the quantity in the cart for a product failed with this JSON response:

```json
{
  "responses": [
    {
      "body": {
        "code": "woocommerce_rest_missing_nonce",
        "message": "Missing the X-WC-Store-API-Nonce header. This endpoint requires a valid nonce.",
        "data": { "status": 401 }
      },
      "status": 401,
      "headers": { "Allow": "POST" }
    }
  ]
}
```

There may be other issues too with other cart updates but I didn't check. I felt it safest to revert for now so this isn't blocking other work while it's being addressed.

2021-04-18 16:28 UTC, nerrad commented
@opr I think we may also want to revisit [these e2e tests](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/tests/e2e/specs/frontend/cart.test.js#L52-L149) you added for the work in #3960. One problem with them is that when the timeout happens for the test not able to retrieve the data from the `localStorage` the error message for the test is ambiguous and makes it a bit harder to capture the reason for why it may be happening. One thing we could try is to wrap the execution of `waitForFunction` in a try/catch and if there is a timeout error we could fail with a better message?