Rename onCheckoutBeforeProcessing to onCheckoutValidationBeforeProcessing
woocommerce/woocommerce-gutenberg-products-block pull request #4039
Opened 2021-04-06 16:31 UTC by ralucaStan

This commit also adds a deprecation warning when using onCheckoutBeforeProcessing.
See the issue below for details.

Fixes #3984

### How to test the changes in this Pull Request:
The renaming part could be tested by smoke testing the Checkout Block:

1. Add something to checkout
2. Submit without a required field
3. Observe validation happens
4. Fix validation and place order

To see the warning you have to call yourself the old `onCheckoutBeforeProcessing`. What I did:

1. I added this component to [Order Summary](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/base/components/cart-checkout/order-summary/index.js) and included it as a child.
2. I went to the Checkout block and tried to submit it without some required fields.
3. I checked the console for the deprecation warning
4. I then fixed the warnings and  successfully submitted the order

```js
const Component = () => {
	const { onCheckoutBeforeProcessing } = useCheckoutContext();
	useEffect( () => {
		const unsubscribe = onCheckoutBeforeProcessing( () => {
			console.log( 'My custom validation callback' );
			return true;
		} );
		return unsubscribe;
	}, [ onCheckoutBeforeProcessing ] );
	return null;
};
```

One thing that could also help with testing is checking the registered observers by adding `console.log(observersByType)` in [emitters.ts](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/base/context/shared/event-emit/emitters.ts#L26). This is logged after submitting with missing inputs.

### Changelog

> Add suggested changelog entry here.

2021-04-07 14:10 UTC, opr approved these changes
Looks great! Works well too, I just have one (non-blocking) comment about TypeScript warnings - it's up to you to decide if we care about this warning for now, or if you want to add the property back to the type-def.

2021-04-07 14:10 UTC, opr commented on assets/js/type-defs/contexts.js
> - * @property {function(function(),number=)} onCheckoutBeforeProcessing           Used to register a callback that will
Removing this causes a TypeScript warning - because this is still used in `usePaymentMethodInterface` but according to the type-defs does not exist on `useCheckoutContext`.

2021-04-08 10:10 UTC, ralucaStan commented on assets/js/type-defs/contexts.js
> - * @property {function(function(),number=)} onCheckoutBeforeProcessing           Used to register a callback that will
I prefer not to handle this here, I've added a deprecated comment where usePaymentMethodInterface is declared, once that file is converted to .ts I image it should be fine

2021-04-13 14:46 UTC, ralucaStan commented
I fixed the tests with commit https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4039/commits/a502d1be8828848270993264c64220731b0ae181, see the description for details.

PR ready to retest

2021-04-13 15:08 UTC, opr requested changes
The latest change looks good, clever way of solving it! I know you did add the comment in the commit message about the reasoning behind this, but could you add an inline comment explaining it too? Without knowing the context this code looks pretty strange.

2021-04-14 11:10 UTC, ralucaStan commented
> The latest change looks good, clever way of solving it! I know you did add the comment in the commit message about the reasoning behind this, but could you add an inline comment explaining it too? Without knowing the context this code looks pretty strange.

Good idea, I added a comment.

2021-04-14 11:32 UTC, opr approved these changes
Approved again! There's one grammar change and I would recommend adding the commit link for additional context. 🥳

2021-04-14 11:32 UTC, opr commented on assets/js/base/context/providers/cart-checkout/checkout-state/index.js
> +	 * To prevent the deprecation message to be shown at render time
```suggestion
	 * To prevent the deprecation message being shown at render time
```

2021-04-14 11:32 UTC, opr commented on assets/js/base/context/providers/cart-checkout/checkout-state/index.js
> +	 * (useMemo calls the passed function at render time)
```suggestion
	 * (useMemo calls the passed function at render time)
	 * See: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4039/commits/a502d1be8828848270993264c64220731b0ae181
```

2021-04-26 15:27 UTC, merged