Create MiniCart block prototype
woocommerce/woocommerce-gutenberg-products-block pull request #4510
Opened 2021-07-27 13:44 UTC by Aljullu

Part of #4245.

This PR creates a prototype of a MiniCart block which has the following characteristics:

* Only a small JavaScript file is downloaded & parsed on each page load if the block is present. That script is used to detect mouse hover/blur on the mini cart button and to preload + append the relevant files.
* Once the page is loaded, all other scripts are preloaded. That means they don't block rendering the page and, instead, they are downloaded in the background after the page is loaded.
* Once the user interacts with the mini cart, those scripts are appended to the page and, because of that, parsed and executed.

The benefits of this approach are:

* We don't block page rendering to download the scripts required to render the block: scripts are dowloaded in the background.
* Files are only parsed and executed when necessary.
* Thanks to rendering a skeleton with real data in PHP, this process is completely transparent to the user as shown in the GIF below. You can see that the Cap item doesn't have the sale badge when the code rendered in PHP is shown, but then it appears when the JS components replace the PHP-rendered elements, that's because for now, I didn't implement sale badges in the PHP rendering code:
![minicart-block-prototype](https://user-images.githubusercontent.com/3616980/127158389-b59719cb-0be6-4b67-be66-cf228a69512b.gif)
* Using the same components and hooks as in the Cart block, we can reuse all the logic. Extensibility points can be reused as well.

Cons of this approach:

* Rendering the same content in PHP and JS means there is some duplication of code.
* In some occasions, the markup rendered in PHP might not be an exact representation of what's rendered with JSX components afterwards. That might happen, for example, if an extension hooks into the extensibility points.

This PR is not ready to be merged: it needs to be updated according to the designs, I didn't pay special attention to the dropdown accessibility and the block in the editor is quite limited...

2021-07-29 15:06 UTC, nerrad commented
Besides the non-blocking improvements this PR suggest is possible, would you be able to get some performance metrics using performance tab in Google Chrome (I think you can measure Web Vitals now there too) to get some idea of the impact between non-lazy and lazy loaded?

2021-07-29 17:34 UTC, Aljullu commented
I quickly created a new branch that removes the lazy-loading (`add/mini-cart-block-prototype-no-lazy-loading`). Then, I loaded a page containing the Mini Cart block and measured three events: Largest Content Paint, DOMContentLoaded and Load. Results can be seen below (I repeated the test three times on each configuration to get more meaningful data):

With lazy loading:

| Largest Contentful Paint | DOMContentLoaded | Load |
| --- | --- | --- |
| 0,856 | 0,823 | 0,891 |
| 0,820 | 0,776 | 0,845 |
| 0,829 | 0,838 | 0,899 |

Without lazy loading:

| Largest Contentful Paint | DOMContentLoaded | Load |
| --- | --- | --- |
| 1,071 | 1,02 | 1,05 |
| 0,863 | 0,951 | 0,972 |
| 0,911 | 0,985 | 1,01 |

Then, I applied a Network throttling of `Slow 3G` to try to make the differences more apparent:

With lazy loading:

| Largest Contentful Paint | DOMContentLoaded | Load |
| --- | --- | --- |
| 6,819 | 10.41 | 12.84 |
| 6,836 | 10.46 | 12.84 |
| 6,853 | 10,50 | 12,88 |

Without lazy loading:

| Largest Contentful Paint | DOMContentLoaded | Load |
| --- | --- | --- |
| 6,873 | 17,57 | 18,22 |
| 6,840 | 17,53 | 18,16 |
| 6,824 | 17,54 | 18,16 |

What's interesting is that _Largest Contentful Paint_ doesn't seem to change when lazy loading is enabled or not. However, differences in DOMContentLoaded and the load event look quite big.

2021-08-20 12:01 UTC, ralucaStan requested changes
Hi Albert, really nice work in this commit. I left some comments, my focus was mostly on the FE part, so I recommend another 👀 for the PHP side.

2021-08-20 12:01 UTC, ralucaStan commented on assets/js/blocks/cart-checkout/mini-cart/preload-script.ts
> +export default preloadScript;
This looks like something that could live outside the mini-cart block, especially since we will want to use prefetching where possible.

2021-08-20 12:01 UTC, ralucaStan commented on assets/js/blocks/cart-checkout/mini-cart/lazy-load-script.ts
> +		// Before
It's not clear what `Before` relates to. It would be helpful if this comment would explain what is happening here.

2021-08-20 12:01 UTC, ralucaStan commented on assets/js/blocks/cart-checkout/mini-cart/lazy-load-script.ts
> +			const handleTranslationsElements = document.querySelectorAll(
is the `-before` suffix something that is used exclusively by translations? I see that both appear in the lazyLoadScriptParams interface, but it's not instantly clear what this API does. Some details about after, before and  translations  param would hep.

2021-08-20 12:01 UTC, ralucaStan commented on assets/js/blocks/cart-checkout/mini-cart/lazy-load-script.ts
> +				// After
This comment isn't also really helpful. I recommend replacing it with something more detailed or removing it

2021-08-20 12:01 UTC, ralucaStan commented on src/BlockTypes/MiniCart.php
> +			<button class="wc-block-mini-cart__button">' .
The button also needs some [a11y aria-attributes](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#associated_aria_roles_states_and_properties), as well as the expanded area. This could be fixed in another PR, as I know this is not the focus of the current one

2021-08-20 12:01 UTC, ralucaStan commented on assets/js/blocks/cart-checkout/mini-cart/frontend.ts
> +			miniCartContents.removeAttribute( 'hidden' );
Here you would need to also handle the [aria attributes](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#associated_aria_roles_states_and_properties) for the expanded/collapsed state.

2021-08-20 12:01 UTC, ralucaStan commented on assets/js/blocks/cart-checkout/mini-cart/frontend.ts
> +	) as Record< string, dependencyData >;
I see that the dependencies list is pretty long and it has things that are already on the page like react, react-dom. I wonder if we could make a list of dependencies to skip. 


```
["lodash", "moment", "regenerator-runtime", "wp-polyfill", "wp-hooks", "wp-i18n", "react", "react-dom", "wp-deprecated", "wp-escape-html", "wp-element", "wc-blocks-registry", "wc-settings", "wp-dom-ready", "wp-a11y", "wp-autop", "wp-blob", "wp-block-serialization-default-parser", "wp-dom", "wp-is-shallow-equal", "wp-keycodes", "wp-priority-queue", "wp-compose", "wp-redux-routine", "wp-data", "wp-html-entities", "wp-primitives", "wp-shortcode", "wp-blocks", "wp-date", "wp-rich-text", "wp-warning", "wc-blocks-checkout", "wp-url", "wp-api-fetch", "wp-data-controls", "wp-notices", "wc-blocks-middleware", "wc-blocks-data-store", "wc-price-format", "wp-plugins", "wp-wordcount", "wc-block-mini-cart-component-frontend"]


```

2021-08-23 12:32 UTC, Aljullu commented on assets/js/blocks/cart-checkout/mini-cart/preload-script.ts
> +export default preloadScript;
Good point. Moved to `base-utils` in 81781f74d2c56ae043f840ff9558d9995d176b73.

2021-08-23 12:32 UTC, Aljullu commented on assets/js/blocks/cart-checkout/mini-cart/lazy-load-script.ts
> +			const handleTranslationsElements = document.querySelectorAll(
You're right, I improved the documentation of `lazyLoadScript` and `preloadScript` in 3487ae5adb0f34acd6be5eb7947bc118294cbd3d. Hopefully things should be more clear now. Let me know how it looks. :slightly_smiling_face:

2021-08-23 12:32 UTC, Aljullu commented on src/BlockTypes/MiniCart.php
> +			<button class="wc-block-mini-cart__button">' .
Aaah, good point, thanks! Let's work on this in #4608 if that's ok.

2021-08-23 12:33 UTC, Aljullu commented on assets/js/blocks/cart-checkout/mini-cart/frontend.ts
> +			miniCartContents.removeAttribute( 'hidden' );
Something that can be fixed in #4608 as well.

2021-08-23 12:33 UTC, Aljullu commented on assets/js/blocks/cart-checkout/mini-cart/frontend.ts
> +	) as Record< string, dependencyData >;
Which dependencies would you skip? Things like `react` or `react-dom`, might or might not be already on the page, so we can't safely skip them, no?

2021-08-23 12:33 UTC, Aljullu commented on assets/js/blocks/cart-checkout/mini-cart/lazy-load-script.ts
> +		// Before
Docs improved in 3487ae5adb0f34acd6be5eb7947bc118294cbd3d.

2021-08-23 12:33 UTC, Aljullu commented on assets/js/blocks/cart-checkout/mini-cart/lazy-load-script.ts
> +				// After
Docs improved in 3487ae5adb0f34acd6be5eb7947bc118294cbd3d.

2021-08-23 12:35 UTC, Aljullu commented
Thanks for reviewing this @ralucaStan. I applied your feedback (except a couple of comments that I leave for #4608). Let me know how everything looks now.

2021-08-25 14:06 UTC, ralucaStan commented on assets/js/blocks/cart-checkout/mini-cart/frontend.ts
> +	) as Record< string, dependencyData >;
My comment was a bit confusing. I was worried that we will load resources twice on the page, so I was suggesting skipping the ones already loaded. I didn't know the already loaded scripts will have ids, like id='react-js', so no change needed here.

2021-08-25 14:07 UTC, ralucaStan approved these changes
Thank you for updating the comments. Really nice work! 👏

2021-08-25 15:37 UTC, Aljullu commented on assets/js/blocks/cart-checkout/mini-cart/frontend.ts
> +	) as Record< string, dependencyData >;
In b10cb4924fa7e49d79376f500f4ae914890e130b, I refactored the `lazyLoadScript()` function a bit to make it easier to understand this part.

2021-08-25 15:42 UTC, merged