Replace deprecated divisions with math.div($size, $base)
woocommerce/woocommerce-gutenberg-products-block pull request #4550
Opened 2021-08-05 09:08 UTC by nielslange

Fixes #4286 

#### Accessibility

n/a

### Screenshots

n/a

### How to test the changes in this Pull Request:

1. Check out this plugin
2. Run `npm i` and `npm run build`
3. See deprecation warnings both for this plugin and external dependencies
4. Apply this PR
5. See only deprecation warnings for external dependencies

### Changelog

> Replace deprecated divisions with math.div($size, $base)

2021-08-11 09:33 UTC, senadir requested changes
Hey Niels, thank you for your PR!

I can still see some warnings, mostly inside functions.

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($gap-small, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
133 │         margin-top: em($gap-small/4);
    │                        ^^^^^^^^^^^^
    ╵
    assets/js/base/components/dropdown-selector/style.scss 133:18  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($gap-small, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
134 │         margin-bottom: em($gap-small/4);
    │                           ^^^^^^^^^^^^
    ╵
    assets/js/base/components/dropdown-selector/style.scss 134:21  root stylesheet
```

I think you attempted to fix this issue manually? If you check the deprecation error, you would find this link https://sass-lang.com/d/slash-div which would provide an automatic tool to fix this (which I tested and it did grab the missing one).
```
npm install -g sass-migrator
sass-migrator division assets/**/*.scss
```

2021-08-11 09:40 UTC, senadir commented
Another note is that for such PRs, we add another label: `skip changelog` and we omit the changelog entry.

2021-08-23 13:40 UTC, nielslange commented
Thanks for your review, @senadir. I must have missed the information on https://sass-lang.com/d/slash-div and just updated this PR accordingly. Also, thank you for pointing out the label `skip changelog`.

2021-08-24 10:18 UTC, senadir approved these changes
Thank you for updating this based on my feedback. When running `npm start` I still see 3 errors, but they're coming from `@wordpress/components` because we're directly importing from node_modules, this is not something we can fix unless we do a PR upstreams but this isn't a high priority for now.

It would be good if in **future PRs** you include in the body:
- The goal of this PR, what are we fixing.
- Any caveats or importing informations I, as a reviewer should know, this include why we didn't fix external depreciation issues, and why they're happening to begin with. It helps me make an informed decision if I should approve this PR or not. and help a release lead green light a release or block it.

2021-08-24 11:24 UTC, nielslange commented
Thanks for your additional feedback, @senadir. I'll keep that in mind for future PRs.

2021-08-24 11:37 UTC, merged