wip: add product on sale test
woocommerce/woocommerce-gutenberg-products-block pull request #4872
Opened 2021-09-30 07:07 UTC by dinhtungdu

Fixes #

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)
- [ ] I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) for any feature flags or experimental interfaces implemented in this pull request.

### Screenshots

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1.
2.
3.

### Performance Impact

### Changelog

> Add suggested changelog entry here.

2021-10-07 06:32 UTC, dinhtungdu commented
Note that #4785 is failing because of the same issue as this PR. It looks like the cart or checkout page isn't always created.

2021-10-15 08:55 UTC, dinhtungdu commented
Marking this PR is ready for review because all of the tests are passed and the flaky test issue (#4916) doesn't relate to changes introduced in this PR.

2021-10-21 05:31 UTC, mikejolley requested changes
Thanks for your contribution @dinhtungdu 

I noticed one incorrect slug. Even though the slug is currently not used, it should be updated before merge. Once that's corrected this is good to go :shipit: 👍🏻

2021-10-21 05:31 UTC, mikejolley commented on tests/e2e/specs/backend/products-by-attribute.test.js
> +	slug: 'woocommerce/product-tag',
Looks like this is the wrong slug?

2021-10-21 09:05 UTC, dinhtungdu commented on tests/e2e/specs/backend/products-by-attribute.test.js
> +	slug: 'woocommerce/product-tag',
@mikejolley It is. I fixed the slug. Can you take another look at this?

2021-10-21 09:12 UTC, mikejolley approved these changes
Thanks 👍🏻 Will wait for tests to pass and then merge.

2021-10-21 09:23 UTC, merged