Add a label to the textarea from the editor view of the Product search block
woocommerce/woocommerce-gutenberg-products-block pull request #4905
Opened 2021-10-06 12:00 UTC by ovidiul

This PR fixes #1682  by adding a label field on top of the Label textarea edit field from the Product Search block.

The label text is announced when moving over the textarea field, so to avoid a duplicate announcement from the label tag, a combination of `className="screen-reader-text" aria-hidden="true"` was used on the label tag.

Fixes #1682 

#### Accessibility

- [x] I've tested using only a keyboard (no mouse)
- [x] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)
- [ ] I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) for any feature flags or experimental interfaces implemented in this pull request.

### Screenshots

<img width="1017" alt="Screenshot 2021-10-06 at 14 53 51" src="https://user-images.githubusercontent.com/537751/136197397-0b8a8dfe-3ac1-4a52-9049-91f8e150510a.png">
<img width="767" alt="Screenshot 2021-10-06 at 14 58 47" src="https://user-images.githubusercontent.com/537751/136197986-11a2c7d8-e623-4a82-90e3-ce6bc6dd15ff.png">

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. create a post and add the search block
2. start Screen reader
3. Move over search label block

### Changelog

> Improve accessibility for the editor view of the Product search block

2021-10-13 15:46 UTC, ralucaStan commented on assets/js/blocks/product-search/edit.js
> +							aria-hidden="true"
I recommend against using `aria-hidden="true"`, because this removes the element from the a11y tree. With `.screen-reader-text` we visually hide the element, but it's still available for screen readers, which is the expected outcome. But using this line removes the element from the screen reader.

2021-10-13 15:48 UTC, ralucaStan requested changes
Thank you @ovidiul for taking care of this. I've added a small change request. I've also edited the PR title and the changelog entry, to make them more human-friendly. Let me know what you think.

2021-10-14 07:22 UTC, ovidiul commented on assets/js/blocks/product-search/edit.js
> +							aria-hidden="true"
@ralucaStan agree on this change, as stated in my initial reply, it seems the Label is being read twice by the screen reader(one from the label tag, and once from the textarea linked to it), although this behaviour is not consistent across all browsers.

Change is now done.

2021-10-14 07:23 UTC, ovidiul commented
> Thank you @ovidiul for taking care of this. I've added a small change request. I've also edited the PR title and the changelog entry, to make them more human-friendly. Let me know what you think.

Thank you @ralucaStan for your help here, changes look great.

2021-10-14 10:23 UTC, ralucaStan approved these changes
👍 🚢

2021-10-14 10:27 UTC, merged