Add cart item name filter
woocommerce/woocommerce-gutenberg-products-block pull request #4993
Opened 2021-10-26 15:32 UTC by senadir

This PR adds productNameFormat filter, to allow cart items names to be customized depending on context.

Cherry-picked from https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4241

### Testing

How to test the changes in this Pull Request:

1. Not much to test given this is a filter, but you can insert this code somewhere.
```js
const { __experimentalRegisterCheckoutFilters } = window.wc.blocksCheckout;
__experimentalRegisterCheckoutFilters( 'my-hypothetical-deposit-plugin', {
	productNameFormat: ( name ) => `${ name } customized`,
} );
```
2. In Checkout, you should see the item name with customized at the end of it.
3. On Cart, you should see the item link with customized at the end of it, it should be included in the link.

### Changelog

> Introduce `productNameFormat` filter for cart items in Cart and Checkout blocks.

2021-10-27 07:06 UTC, nielslange approved these changes
Works as expected! 🚢 

I only added two suggestions where it seems that a dot ended up in the middle of a sentence accidentally. Apart from that, all good!

2021-10-27 07:06 UTC, nielslange commented on docs/extensibility/available-filters.md
> +| `productNameFormat` | This is the name of a single item. before being turned to a link. | `string` and **must** contain the substring `<name/>` where the original name should appear. |
It appears that a dot accidentally ended up in the middle of the sentence:

```suggestion
| `productNameFormat` | This is the name of a single item before being turned to a link. | `string` and **must** contain the substring `<name/>` where the original name should appear. |
```

2021-10-27 07:06 UTC, nielslange commented on docs/extensibility/available-filters.md
> +| `productNameFormat` | This is the name of a single item. before being turned to a link. | `string` and **must** contain the substring `<name/>` where the original name should appear. |
As mentioned before, this sentence here also contains a dot in its middle:

```suggestion
| `productNameFormat` | This is the name of a single item before being turned to a link. | `string` and **must** contain the substring `<name/>` where the original name should appear. |
```

2021-11-10 08:56 UTC, opr requested changes
Could you not use the existing `itemName` filter? The work you did with formatting and validation can be kept, this is great, but we already have a filter in place for product names.

2021-11-10 10:17 UTC, senadir commented
Ah! I must have missed that filter, it does indeed what need here, I will update this PR.

2021-12-20 11:15 UTC, mikejolley commented
@senadir reminder this has follow ups/conflicts.

2022-08-01 12:54 UTC, closed without merging