Correct textdomain from 'woo-gutenberg-product-blocks' to 'woo-gutenberg-products-blocks'
woocommerce/woocommerce-gutenberg-products-block pull request #5020
Opened 2021-10-28 03:54 UTC by nielslange

Related #5005 

### Note

Some strings were using the textdomain `woo-gutenberg-product-blocks` instead of `woo-gutenberg-products-blocks` (note the missing `s` for products). Even though these strings have been translated, due to the incorrect textdomain they aren't visible in the plugin.

### Testing instructions

1. Check out the `trunk`.
2. Search for the incorrect text domain `'woo-gutenberg-product-blocks'`.
3. Verify that you get some results.
4. Check out this PR.
5. Search for the incorrect text domain `'woo-gutenberg-product-blocks'` again.
6. Verify that you no longer get results for the incorrect text domain.

### Additional notes

Issue #5005 is not entierly solved by this PR, but require a follow up PR to lazy load some missing translation files on the frontend.

### Changelog

> Replace incorrect with correct text domain.

2021-10-28 08:03 UTC, opr requested changes
Hi @nielslange looks like you've kept the `s` on `blocks`, however, it should read `woo-gutenberg-products-block`.

Could you also add more robust testing instructions for this PR since the current ones don't actually show the issue being fixed. Something like:

1. Add the terms and conditions block to your Checkout block.
3. Change your site language to Spanish and go to the Checkout block.
3. Verify the text in the terms and conditions block is translated.

2021-10-28 09:02 UTC, ralucaStan commented
I also recommend changing the changelog entry to something like _Fix missing translations in the Checkout block that were using an incorrect textdomain_. This provides more details and is user-friendly

2021-10-28 09:04 UTC, nielslange commented
> Hi @nielslange looks like you've kept the s on blocks, however, it should read woo-gutenberg-products-block.

Good catch, @opr!

> Could you also add more robust testing instructions for this PR since the current ones don't actually show the issue being fixed.

Absolutely. Due to my incorrect fix, I could not see the change initially. That's why I haven't pointed out the testing instructions that you mentioned. I'll correct the testing instructions directly.

2021-10-28 09:10 UTC, nielslange commented
> I also recommend changing the changelog entry to something like Fix missing translations that were using an incorrect textdomain. This provides more details and is user-friendly

Great suggestion, @ralucaStan. I've updated the changelog message accordingly. You could now review this PR.

2021-10-28 09:56 UTC, opr commented
@nielslange on the block in the editor I see the translated string, but not on the front-end.

| Editor | Front-end |
|---|---|
| ![image](https://user-images.githubusercontent.com/5656702/139233214-525a46a8-437d-4734-bffd-d8f1cd857170.png) | ![image](https://user-images.githubusercontent.com/5656702/139233027-116f8297-cb50-4d50-8f76-9e057f6c4e37.png) |

Any ideas why not?

2021-10-28 10:57 UTC, nielslange commented
> Any ideas why not?

@opr I didn't notice that initially. I just looked up this problem and saw that both the editor and the frontend are fetching the translation from the [constants.js](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/blocks/cart-checkout/checkout/inner-blocks/checkout-terms-block/constants.js) file. The translations for the editor and the frontend are coming from this part:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/becd87b67103370d1320ddfcdb577b4b909d3e96/assets/js/blocks/cart-checkout/checkout/inner-blocks/checkout-terms-block/constants.js#L21-L39

When debugging these parts, I do see the translated version in the editor, but the untranslated version in the frontend. However, the i18n functionality is enqueued in the frontend. I'll investigate what is causing this problem.

2021-11-08 12:20 UTC, senadir approved these changes
This does as advertises, which is fix all instances of wrong text domain.
Changelog and testing steps should be updated to reflect the new changes.

2021-11-08 12:42 UTC, nielslange commented
@senadir Thanks for your quick review!

@opr I found out that some strings are not visible on the frontend, due to lazy loading. I'll take care of that in a separate PR.

2021-11-08 12:43 UTC, merged