In `@woocommerce/blocks-checkout` package documentation - reference WCDEWP instead of WPDEWP
woocommerce/woocommerce-gutenberg-products-block pull request #5154
Opened 2021-11-16 13:11 UTC by nerrad

The current documentation for the checkout package references the WordPress Dependency Extraction Webpack plugin. However, there's less configuration needed if folks use the WooCommerce Dependency Extraction Webpack plugin instead, so this PR modifies the documentation accordingly.

There is no impact to released code in this PR.

Reviews mostly just need to ensure the syntax of the example provided is correct and there are no other grammar/spelling errors in the documentation.

2021-11-19 12:53 UTC, opr requested changes
Tested this out on my example plugin and had to make some changes to get it to work, I've added them as suggestions

2021-11-19 12:53 UTC, opr commented on packages/checkout/README.md
> +const WooCommerceDependencyExtractionWebpackPlugin = require( '@wordpress/dependency-extraction-webpack-plugin' );
```suggestion
const WooCommerceDependencyExtractionWebpackPlugin = require( '@woocommerce/dependency-extraction-webpack-plugin' );
```

2021-11-19 12:53 UTC, opr commented on packages/checkout/README.md
> +		new WooCommerceDependencyExtractionWebpackPlugin,
```suggestion
		new WooCommerceDependencyExtractionWebpackPlugin(),
```

2021-11-20 12:08 UTC, nerrad commented on packages/checkout/README.md
> +const WooCommerceDependencyExtractionWebpackPlugin = require( '@wordpress/dependency-extraction-webpack-plugin' );
doh 🤦🏻

2021-11-20 12:08 UTC, merged