Prevent third party blocks from breaking the entire checkout/cart block
woocommerce/woocommerce-gutenberg-products-block pull request #5297
Opened 2021-12-02 17:10 UTC by alexflorisca

If a third party block registers itself on the checkout/cart block (or one of its' inner blocks) it will cause the entire Checkout/Cart block to error. See #5101 for more details.

This PR ads an empty `<BlockErrorBoundary>` component around each of the inner blocks rendered within the checkout/cart components. There is a risk here that because the error boundary doesn't show any errors and fails silently, that it may cause some difficulty in debugging. I think from a user perspective this is the best solution, as we don't want to show any cryptic error messages at the crtical stage of a customer's journey. From a dev perspective, the error is thrown in the console and If a whole block goes missing from your checkout, you will know something is wrong! Would love to hear other's thoughts on this.

Fixes #5101 

### Testing

### Manual Testing

How to test the changes in this Pull Request:

1. Install the [Newsletter test](https://github.com/woocommerce/newsletter-test) plugin locally and activate
2. Visit the Checkout page. Expect to see a newsletter checkbox under the email input field added by the newsletter-test plugin
3. Throw an error anywhere in this [Block](https://github.com/woocommerce/newsletter-test/blob/main/assets/js/checkout-newsletter-subscription-block/block.js#L10)
4. Reload the Chekout page. 
5. The newsletter checkbox should not be visible and the rest of the checkout block should display and function as normal.

### Changelog

> Prevent third party blocks from breaking the entire checkout/cart blocks

2022-01-17 17:29 UTC, opr commented
Hey @alexflorisca, I believe we talked about this briefly, there's an issue with the implementation because any third party block erroring will cause the section it's rendered in to disappear. For example, using the newsletter plugin, making the checkbox block error causes the "Contact Information" section to leave the page. We'll need to explore more ways to prevent third party blocks breaking the checkout experience while also ensuring that the experience remains fully functional.

2022-01-18 18:25 UTC, senadir approved these changes
Thank you for working on this Alex! Are we sure that for two blocks on the same level, one of them breaking won't break the other one? I tested locally and it didn't happen to me so I think we're all good.

Another issue is that we want to show errors for admin and store managers, but not everyone else. Currently, logged in as a admin, I didn't see any errors whatsoever?

Apart from that, this is good to go!

2022-01-20 12:21 UTC, opr requested changes
Hey Alex, thanks for working on this, I noticed something that doesn't work quite right. The children of `InnerBlockComponentWrapper` receive the `children` and `checkoutExtensionData` props, but since we're wrapping each inner block within a `BlockErrorBoundary` the props don't get passed down to the children.

You could make `renderForcedBlocks` return this to fix it, let me know what you think.

```typescript
	return forcedBlocks.map(
		( { blockName, component }, index: number ): JSX.Element | null => {
			const ForcedComponent = component
				? component
				: getBlockComponentFromMap( blockName, blockMap );
			return ForcedComponent ? (
				<BlockErrorBoundary
					text={ `Unexpected error in: ${ blockName } }` }
					showErrorBlock={ CURRENT_USER_IS_ADMIN as boolean }
				>
					<InnerBlockComponentWrapper>
						<ForcedComponent
							key={ `${ blockName }_forced_${ index }` }
						/>
					</InnerBlockComponentWrapper>
				</BlockErrorBoundary>
			) : null;
		}
	);
```

I think there's also an issue with `renderInnerBlocks` it looks like it's only rendering one part of the block, and `children` is null, do you see this too?

2022-01-20 12:21 UTC, opr commented on assets/js/atomic/utils/render-parent-block.tsx
> +							text={ `Unexpected error in: ${ blockName } }` }
There is an extra `}` here

2022-01-20 12:21 UTC, opr commented on assets/js/atomic/utils/render-parent-block.tsx
> +					text={ `Unexpected error in: ${ blockName } }` }
And here

2022-01-20 12:21 UTC, opr commented on assets/js/base/components/block-error-boundary/types.ts
> +	showErrorMessage?: boolean;
Nice 😎  thanks for adding these types!

2022-01-21 13:39 UTC, alexflorisca commented on assets/js/atomic/utils/render-parent-block.tsx
> +							text={ `Unexpected error in: ${ blockName } }` }
Good spot, thanks 👍

2022-01-25 10:42 UTC, opr approved these changes
Woo! This is working for me now, both forced and unforced inner blocks are rendering correctly, nice one Alex!

2022-01-25 12:01 UTC, merged