Remove deprecated data controls in favour of those from the `@wordpress/data` package
woocommerce/woocommerce-gutenberg-products-block pull request #5574
Opened 2022-01-17 14:01 UTC by mikejolley

Removes usage of the deprecated functions `select` and `dispatch` imported from `@wordpress/data-controls` ([deprecated here](https://github.com/WordPress/gutenberg/pull/26509)) and replaces them with `controls.select` and `controls.dispatch` from the `@wordpress/data` package.  

Fixes #5339

Questions from the issue:

> What version of WordPress is the replacement available?

The switch to `@wordpress/data` happened in Gutenberg 9.2, which was part of [WordPress 5.6](https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/), but controls existed before then. 

> Is the deprecated implementation in Woo Blocks in code that is exposed to users via Woo Core?

Yes, it's part of schema and collections data-stores, used by All Products block.

> What version of WordPress does Woo Core still require as minimum support and does that fall in the appropriate range?

The `controls` export existed in WordPress 5.6 ([see here](https://github.com/WordPress/WordPress/blob/5.6/wp-includes/js/dist/data.js)). This is the min supported version of Woo core.

Blocks min support is 5.8. Both are satisfied.

### Testing

How to test the changes in this Pull Request:

1. Smoke test changing quantities of items in the cart
2. Smoke test All Products block and add to cart buttons within that block
3. Smoke test All Products block with Filter Blocks

JS tests must also pass. I removed the deprecation assertions from those.

### Changelog

> Remove deprecated data controls in favour of those from the `@wordpress/data` package

2022-02-03 17:34 UTC, alexflorisca requested changes
Hey @mikejolley, ran into an issue when testing this

The all products block seems to think there are no products (even though there definitely are)

<img width="755" alt="Screenshot 2022-02-03 at 16 41 56" src="https://user-images.githubusercontent.com/3966773/152388235-d9cbfc2d-36ee-4dc6-bcbe-4592f8140ad5.png">

Filter blocks alongside it also seem to be broken:

<img width="265" alt="Screenshot 2022-02-03 at 16 42 52" src="https://user-images.githubusercontent.com/3966773/152395304-5a5c59a2-b9d3-40a1-8561-529bff335aba.png">

I don't know enough about how `@wordpress/data` works to suggest why this might be but I'm happy to help you figure it out!

The code looks good though and the Cart quantity selector seems to work fine ok and the tests pass 👍

2022-02-03 17:34 UTC, alexflorisca commented on assets/js/blocks/cart-checkout/cart/test/block.js
>  		render( <CartBlock /> );
I think the render method should go inside the `act()` function from the [react docs](https://reactjs.org/docs/test-utils.html#act)

2022-02-24 17:22 UTC, mikejolley commented
I see the products issue too. I can't figure out why though 🤔  I don't see anything obvious in the diff which would break. I do see `const route = yield controls.select` is returning blank for some reason.

2022-03-09 11:32 UTC, mikejolley commented
Found the issue. `select` does not wait for the resolution. `resolveSelect` does. See https://github.com/WordPress/gutenberg/blob/trunk/packages/data/src/controls.js#L40-L84

2022-03-09 18:07 UTC, alexflorisca approved these changes
Ah good spot. I wonder why there's 2 methods, from what I know `select` ran the resolver automatically if there was one specified and waited for it. Anyway good to go 👍

2022-03-10 13:22 UTC, merged