Remove custom `Icon` component in favour of `@wordpress/icons` where possible
woocommerce/woocommerce-gutenberg-products-block pull request #5599
Opened 2022-01-19 15:30 UTC by mikejolley

This PR removes our `Icon` component in favour of the Icon component that is included with `@wordpress/icons`. On top of this, I've removed/migrated as many `@woocommerce/icons` as possible in favour of similar or equivalent `@wordpress/icons` in order to reduce our package size.

Fixes #3512

List of substitutions: 

| Woo Library | Usage | WP Library | 
|:---:|:-----:|:---:|
| atom | Product Elements/Atomic Blocks Section | woo |
| done | Cart button checkmark | check |
| folder | Block icon | file or archive |
| image | Block icon | image |
| star | Block icon | starEmpty |
| tag | Block icon | tag |
| grid | Block icon | grid |
| bill | Block icon | currencyDollar |
| box | Block icon | box |
| notes | Block icon | page |
| bookmark | Block icon | heading |
| arrowBack | Button | arrowLeft |
| noAlt | Chip component | closeSmall |
| card | Gateways | payment |
| bank | Gateways | institution |
| search | Search components | search |
| notice | Error message components | warning |
| discussion | Reviews widgets | postComments |
| chevronUp/chevronDown | Panels | chevronUp/chevronDown |
| external | External links in panels | external |
| server | Block icon for attributes | category |
| truck | Block icon | shipping |
| stonks | Block icon | trendingUp |
| address | Block icon | mapMarker |
| comment | Block icon | commentContent |
| asterisk | Terms and Conditions Block | customPostType |
| list | Block icon | list |
| review | Block icon | commentContent |
| reader | Single product block icon | mediaAndText |
| restore | Single Product Block | backup |
| contact | Contact Block Icon | atSymbol |
| tags | Products by attribute Block | category |
| more | Products by tag block | tag |
| exclamation | New products block icon | sparkles |
| widgets | Handpicked products block | category |

#### Other Checks

- [ ] We need to confirm the packages are available in supported WordPress versions before shipping
- [x] Need to confirm bundle size has not increased too much on frontend where icons are used

### Screenshots

| Before | After |
| ------------- | ------------- |
| <img width="248" alt="Screenshot 2022-02-01 at 12 36 17" src="https://user-images.githubusercontent.com/1628454/151965347-e6802d2f-6cb2-463a-8c7b-76b0594d8210.png"> |  <img width="250" alt="Screenshot 2022-02-01 at 13 04 10" src="https://user-images.githubusercontent.com/1628454/151971955-8907a318-b461-45ae-b586-e7db9b650284.png"> |
| <img width="251" alt="Screenshot 2022-02-01 at 13 06 50" src="https://user-images.githubusercontent.com/1628454/151965729-2dde8265-d323-4376-b392-de794bc50098.png"> |  <img width="252" alt="Screenshot 2022-02-01 at 13 05 45" src="https://user-images.githubusercontent.com/1628454/151965707-3b6141df-a83b-483d-9792-18d20347ea11.png"> |

### Testing

### Manual Testing

**Confirm there are no build errors** since this should pick up any mistakes with icon naming.

How to test the changes in this Pull Request:

1. Open block inserted and smoke test block icons
2. Try inner blocks within cart/checkout/single-product/all product blocks and confirm icons are working for inner blocks.
3. Check storybook works for icon library

No testing steps for end-users.

### Performance Impact

We need to confirm bundles sizes are not increased due to using the `@wordpress/icons` package. 

### Changelog

> Update block icons to use `@wordpress/icons` where possible.

2022-01-28 10:41 UTC, mikejolley commented
Conflicts :/ 

I'll resolve them once this is reviewed.

2022-02-01 12:00 UTC, ralucaStan requested changes
Huge effort here @mikejolley !
Code wise it looks good I made some small comments. 

Personally I liked the old All products better, but other than that I think most icon changes look better. I will post a comment with before and after image

2022-02-01 12:00 UTC, ralucaStan commented on assets/js/icons/library/woo.tsx
> +import { SVG } from '@wordpress/primitives';
There is a small leftover import in the project, it would be great if that could be replaced as well 
```
import { Path, SVG } from '@wordpress/components';
```

2022-02-01 12:00 UTC, ralucaStan commented on assets/js/icons/README.md
> +import { woo } from '@woocommerce/icons';
It would be great if we had a small comment explaining why the two imports. 

Also, under `## Adding Icons` we could mention

0. Make sure the icon is not already included in [the Library](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library) that comes with @wordpress/icons package.

2022-02-01 12:01 UTC, ralucaStan commented
The brach has some conflicts now :(

2022-02-01 12:03 UTC, mikejolley commented
@ralucaStan I am rebasing now. I knew it would get conflicts due to number of files changed.

2022-02-01 12:09 UTC, ralucaStan commented
@mikejolley I've used the images below to understand the changes, maybe add them to the description so that they could be used in the release post? 

| Before | After |
| ------------- | ------------- |
| <img width="248" alt="Screenshot 2022-02-01 at 12 36 17" src="https://user-images.githubusercontent.com/1628454/151965347-e6802d2f-6cb2-463a-8c7b-76b0594d8210.png"> |  <img width="250" alt="Screenshot 2022-02-01 at 13 04 10" src="https://user-images.githubusercontent.com/1628454/151971955-8907a318-b461-45ae-b586-e7db9b650284.png"> |
| <img width="251" alt="Screenshot 2022-02-01 at 13 06 50" src="https://user-images.githubusercontent.com/1628454/151965729-2dde8265-d323-4376-b392-de794bc50098.png"> |  <img width="252" alt="Screenshot 2022-02-01 at 13 05 45" src="https://user-images.githubusercontent.com/1628454/151965707-3b6141df-a83b-483d-9792-18d20347ea11.png"> |

2022-02-01 12:11 UTC, mikejolley commented
@ralucaStan thanks Ill update it. Your "after" image on the first row is not the correct one.

2022-02-01 12:54 UTC, ralucaStan commented
> @ralucaStan thanks Ill update it. Your "after" image on the first row is not the correct one.

fixed

2022-02-01 13:32 UTC, mikejolley commented
Thanks @ralucaStan I've updated the issue and fixed your suggestions. Should we merge as-is, or did you want to find an alternative for all products block? I went with a grid theme similar to what we had before.

2022-02-01 14:55 UTC, ralucaStan approved these changes
I've added some suggestions for the readme update. 

I am ok to move fw with the All products icon you chose.

2022-02-01 14:55 UTC, ralucaStan commented on assets/js/icons/README.md
> +Note we use hte `Icon` component from `@wordpress/icons`, and the Icon SVG from `@woocommerce/icons`.
```suggestion
Note we use the `Icon` component from `@wordpress/icons`. We use some SVG icons from `@woocommerce/icons` for WC Blocks specific icons, but we also use existing icons from `@wordpress/icons`.
```

2022-02-01 14:55 UTC, ralucaStan commented on assets/js/icons/README.md
> +import { Icon } from '@wordpress/icons';
```suggestion
import { Icon, postComments } from '@wordpress/icons';
```

2022-02-01 14:55 UTC, ralucaStan commented on assets/js/icons/README.md
> +<Icon icon={ woo } />
```suggestion
<Icon icon={ woo } /> // icon  from '@woocommerce/icons'
<Icon icon={ postComments } /> // icon from '@wordpress/icons'
```

2022-02-01 16:54 UTC, merged