Add Testing Details In Contributors Guide
woocommerce/woocommerce-gutenberg-products-block pull request #5879
Opened 2022-02-17 11:54 UTC by tarunvijwani

Fixes #5878

This PR adds the testing details in the [Getting Started Contributors Guide](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/contributors/getting-started.md).

### Testing

Read the [Getting Started Contributors Guide](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/contributors/getting-started.md) and make sure testing steps are added correctly.

2022-02-18 11:44 UTC, opr requested changes
Thanks Tarun, just left a comment that will need to be addressed before we can merge this.

2022-02-18 11:44 UTC, opr commented on docs/contributors/getting-started.md
> +You can also use [Docker](https://www.docker.com/) to run end-to-end or php tests.
I don't think this should be here, the npm scripts for PHP and E2E run in Docker anyway, maybe we should just skip this line, keep the line below about `npm run wp-env` though 👍🏼

2022-02-24 16:04 UTC, tarunvijwani commented on docs/contributors/getting-started.md
> +You can also use [Docker](https://www.docker.com/) to run end-to-end or php tests.
Sure, I have removed those lines. 👍

2022-02-24 16:19 UTC, opr approved these changes
Thanks! Looks good now

2022-02-25 14:51 UTC, merged