Shopper → Cart → Can remove product
woocommerce/woocommerce-gutenberg-products-block pull request #6015
Opened 2022-03-08 20:30 UTC by tarunvijwani

Fixes #5756

This PR adds e2e tests to verify that a shopper can remove products in the Cart block page.

### Testing

#### Automated Tests
* [x] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [x] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. Check out this PR.
2. Start Docker Desktop.
3. Run `npm run wp-env destroy && npm run wp-env start` to start a fresh e2e environment.
4. Run `npm run test:e2e -- tests/e2e/specs/shopper/cart-products.test.js` to run only this test case.
5. Make sure all tests pass.

2022-03-09 10:19 UTC, alexflorisca requested changes
Nice work Tarun! If you pull in the latest `trunk` into your branch, you'll notice I've made some changes top the shopper object in this [PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6013) which needs a code minor change which I've mentioned inline

2022-03-09 10:19 UTC, alexflorisca commented on tests/e2e/specs/shopper/cart-products.test.js
> +		await shopper.goToCartBlock();
You'll need to use `shopper.block.goToCart()` here.

2022-03-09 10:19 UTC, alexflorisca commented on tests/e2e/specs/shopper/cart-products.test.js
> +		await shopper.addToCartFromShopPage( SIMPLE_PRODUCT_NAME );
I didn't know this existed, nice one, this makes adding items to cart a one liner!

2022-03-09 17:02 UTC, tarunvijwani commented on tests/e2e/specs/shopper/cart-products.test.js
> +		await shopper.goToCartBlock();
@alexflorisca Thank you for the suggestion. I have updated the code. :)

2022-03-10 10:06 UTC, alexflorisca approved these changes
Good work, ship it!

2022-03-10 11:47 UTC, merged