Filter Products by Attribute: Fix dropdown search case sensitivity
woocommerce/woocommerce-gutenberg-products-block pull request #6096
Opened 2022-03-23 11:56 UTC by danieldudzic

Fix dropdown search case-sensitivity handling for the Filter Products by Attribute block.

Fixes #5718 

### Screenshots
|Before|After|
|-|-|
|![before](https://user-images.githubusercontent.com/905781/159692538-c43838cb-9bd7-4ad5-a9d7-1bb3f3a77d77.jpg)|![after](https://user-images.githubusercontent.com/905781/159692560-a13d6259-b85c-4068-b0be-42e676dfabdd.jpg)|

### Manual Testing
How to test the changes in this Pull Request:

1. Check out this branch and compile the changes
2. Activate a **block theme**, like Twenty Twenty Two
3. Create a new page, and add the **Filter Products by Attribute** block
4. Change the **Display Style** to **Dropdown**
5. In the **Filter Products by Attribute** section select the attribute you want to be filtering by (in my case 'Size')
6. Test the page on the front-end by searching for product attributes
7. Make sure that relevant values are being found for both Uppercase and Lowercase input

### User Facing Testing
These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).

- [x] Same as above

2022-03-23 19:31 UTC, danieldudzic reviewed
By default, the search will be case-insensitive, but setting `isCaseSensitive` to `true` changes it to case-sensitive.

This refactor also fixes the original issue.

2022-03-24 10:14 UTC, tomasztunik requested changes
Good idea including the option for case sensitivity control!

Leaving small change request regarding drying the code a bit and will be good to go!

2022-03-24 10:14 UTC, tomasztunik commented on assets/js/base/components/dropdown-selector/index.js
> + * @param {boolean} props.isCaseSensitive Whether the dropdown search should be case-sensitive.
FYI - optional params can be denoted with [] and we can provide default value here as well.

ie. `@param {boolean} [props.isCaseSensitive=false] ...`

2022-03-24 10:14 UTC, tomasztunik commented on assets/js/base/components/dropdown-selector/index.js
> +							} ) }
Could we dry this bit a bit? we could simplify it to normalize the inputValue and optionName only when needed ie.

we could also add trim to the inputValue

ie.

```
const optionName = isCaseSensitive ? option.name : option.name.toLowerCase();
const nameQuery = isCaseSensitive ? inputValue...

return ! inputValue || optionName.includes( nameQuery.trim() )
```

This way we'll have input/data normalisation separated and all business logic in one place

2022-03-25 06:49 UTC, tomasztunik approved these changes

2022-03-25 06:50 UTC, tomasztunik commented
Looks good! :)

2022-03-25 09:49 UTC, merged