Fix release schedule link in release and patch initial checklist
woocommerce/woocommerce-gutenberg-products-block pull request #6338
Opened 2022-04-27 14:45 UTC by tarunvijwani

We moved the [release schedule page](PdToLP-K-p2) to [WC Blocks repo](dToLP-p2). This PR updates the release schedule link present in the release and patch initial checklist.

2022-04-27 15:07 UTC, alexflorisca requested changes
Hey @tarunvijwani, ideally we would want to use a TamperMonkey script to hide any internal links. See this [FG page](PCYsg-5Xx-p2) and the [TM script here](https://github.com/Automattic/tampermonkey-highlighter)

2022-04-27 15:07 UTC, alexflorisca commented on .github/patch-initial-checklist.md
> -* [ ] Update the schedules p2 with the shipped date for the release (Pca54o-1N-p2).
It's good to use a tampermonkey script here as we ideally don't want internal urls to be public

2022-04-27 15:07 UTC, alexflorisca commented on .github/release-initial-checklist.md
> +* [ ] Update the schedules p2 with the shipped date for the release ([`Release Schedules`](https://wooblocksrepo.wordpress.com/release-schedules/)).
Same as above ^^

2022-04-27 17:58 UTC, tarunvijwani commented
> Hey @tarunvijwani, ideally we would want to use a TamperMonkey script to hide any internal links. See this FG page (PCYsg-5Xx-p2) and the [TM script here](https://github.com/Automattic/tampermonkey-highlighter)

Thank you, @alexflorisca! It was a TIL for me. I have added the TamperMonkey script generated link now. 🙂

Link added: PdToLP-K-p2

2022-05-03 10:48 UTC, alexflorisca approved these changes
Looks good 👍

2022-05-05 10:01 UTC, merged