Mini Cart: Add font size and font family controls
woocommerce/woocommerce-gutenberg-products-block pull request #6396
Opened 2022-05-10 15:41 UTC by danieldudzic

This PR adds support for Typography options: `Font size` and `Font family` for the `Mini Cart` block.

Fixes #6254 

### Screenshots
|Before|After|
|-|-|
|![before_now](https://user-images.githubusercontent.com/905781/167665373-ca4d9de0-77e9-4e98-bafb-b168c2e62638.jpg)|![after_now](https://user-images.githubusercontent.com/905781/167665212-fbe1c92b-22cb-494a-b007-76c1bf9fa6b4.jpg)|

### Testing
How to test the changes in this Pull Request:

1. Activate a **block** theme, like Twenty Twenty Two
2. Create a new page, and add the Mini Cart block
3. Check if the `Typography` option is available for the block
4. Check if the `Font size` and `Font family` options work correctly both in the editor and on the frontend

2b. After testing the above, try the same with the Mini Cart block added via the FSE editor (for example in the header)

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
  
### User Facing Testing
These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).
* [ ] Same as above

### Changelog

> Add support for `Font size` and `Font family` for the `Mini Cart` block.

2022-05-13 13:09 UTC, gigitux requested changes
Good job! Just two tiny comments! 💪

2022-05-13 13:09 UTC, gigitux commented on assets/js/hooks/style-attributes.ts
> +			fontFamily: attributesObject.attributes.fontFamily,
I guess that can we revert this change, right?

2022-05-13 13:09 UTC, gigitux commented on assets/js/blocks/mini-cart/index.tsx
> +			__experimentalFontFamily: true,
The experimental feature should be enabled only for the featuring plugin. We can do it, in this way:
```suggestion
				...( isFeaturePluginBuild() && {
				__experimentalFontFamily: true,
			} ),
```

2022-05-20 14:47 UTC, danieldudzic commented on assets/js/blocks/mini-cart/index.tsx
> +			__experimentalFontFamily: true,
Hmm, this actually broke the block. It would no longer show on the list of blocks 🤔

2022-05-20 15:24 UTC, gigitux commented on assets/js/blocks/mini-cart/index.tsx
> +			__experimentalFontFamily: true,
Mmm, strange. Did you import the function?

2022-05-27 19:48 UTC, danieldudzic commented on assets/js/blocks/mini-cart/index.tsx
> +			__experimentalFontFamily: true,
Yup. Forgot about the import! :)

2022-05-30 07:48 UTC, gigitux approved these changes
LGTM

2022-05-30 08:45 UTC, merged