Convert validation context to data store
woocommerce/woocommerce-gutenberg-products-block pull request #6402
Opened 2022-05-11 11:46 UTC by tarunvijwani

This PR is for moving the validation errors to a @wordpress/data store instead of using context

### Testing

#### Automated Tests
* [x] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [x] E2E tests

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Manual Testing

How to test the changes in this Pull Request:

1. Run `npm run test -- validation` to run only this test case.
5. Make sure all tests pass.

2022-05-24 16:35 UTC, alexflorisca requested changes
Nice work Tarun 👏 ! Laying down some good foundations. I left a few comments inline for a few potential improvements

2022-05-24 16:35 UTC, alexflorisca commented on packages/checkout/validation/reducers.ts
> +				return state;
Shouldn't this filter based on `hidden: false` here? Otherwise we would also show the validation errors that are set to be hidden.

2022-05-24 16:35 UTC, alexflorisca commented on packages/checkout/validation/test/reducers.js
> +		const state = {
It would be good to add 2 more errors to the state here that have `{ hidden: false }` to test wether this action will also hide any errors that are currently visible, and only show the specified one

2022-05-24 16:35 UTC, alexflorisca commented on packages/checkout/validation/test/selectors.js
> +	it( 'Can get the validation error', () => {
I would include the name of the selector we are testing in the test description in these tests to make it a bit clearer

2022-05-24 16:35 UTC, alexflorisca commented on packages/checkout/validation/test/selectors.js
> +	it( 'Can check if state has any validation errors', () => {
This test would pass if I changed the `hasValidationErrors()` function to always `return true`. Let's test the other option here as well and check that it returns `false` when there are no validation errors in the state

2022-05-24 16:35 UTC, alexflorisca commented on packages/checkout/validation/test/reducers.js
> +/**
Let's convert this file to TypeScript as we are moving to using TS throughout the codebase

2022-05-24 16:35 UTC, alexflorisca commented on packages/checkout/validation/test/selectors.js
> +/**
Let's convert this file to TS as well

2022-06-06 14:21 UTC, opr commented on packages/checkout/validation/reducers.ts
> +				return state;
I am not sure I follow your question, this action `SHOW_VALIDATION_ERROR` sets `hidden` to be `false` on an error in the store, so the point of this is to show hidden ones, the checks above are for ensuring the error actually exists in the store.

2022-06-06 15:30 UTC, opr commented on packages/checkout/validation/test/reducers.js
> +		const state = {
That's not the goal of this action actually, it's just to change whether a specific action is hidden or not. But good idea to add a visible one and ensure it remains visible after this action is applied to a different error!

2022-06-07 01:04 UTC, opr commented
@tarunvijwani - I've been working on this and I have updated the main PR description to include testing steps for what I changes! Thanks for your initial work on this PR, it was invaluable!

2022-06-07 06:37 UTC, tarunvijwani commented
> @tarunvijwani - I've been working on this and I have updated the main PR description to include testing steps for what I changes! Thanks for your initial work on this PR, it was invaluable!

@opr Thank you for working on this! 👍

2022-06-29 00:06 UTC, tarhi-saad requested changes
Thank you, @opr, for this fantastic PR! You did an excellent job! I did review & test the changes thoroughly, and everything is working as expected. Below are some minor fixes to apply before merging our PR!

2022-06-29 00:06 UTC, tarhi-saad commented on assets/js/base/components/text-input/validated-text-input.tsx
> +import { VALIDATION_STORE_KEY } from '../../../data/validation';
Maybe using the re-mapped path is more appropriate in this case:

```js
import { VALIDATION_STORE_KEY } from '@woocommerce/block-data';
```

2022-06-29 00:06 UTC, tarhi-saad commented on assets/js/data/validation/index.ts
> +registerStore< State >( STORE_KEY, {
`registerStore` [is deprecated](https://github.com/WordPress/gutenberg/tree/trunk/packages/data#registerstore). Let's use `register` instead!

2022-06-29 00:06 UTC, tarhi-saad commented on assets/js/base/components/validation-input-error/index.tsx
>  import PropTypes from 'prop-types';
We converted this file to a `jsx` file. It would be great to use `TS types` instead of `prop-types`?

2022-06-29 00:06 UTC, tarhi-saad commented on assets/js/base/context/hooks/payment-methods/use-payment-method-interface.ts
> +import { ValidationInputError } from '@woocommerce/base-components/validation-input-error';
This file has a TS error for `ValidationInputError` (see line 139).  We'll need to update the `ValidationInputError` in `assets/js/types/type-defs/payment-method-interface.ts` at line 78.

2022-06-29 00:06 UTC, tarhi-saad commented on assets/js/data/validation/test/reducers.ts
> +import reducer, { FieldValidationStatus } from '../reducers';
We have an import error: `Module '"../reducers"' has no exported member 'FieldValidationStatus'`. Let's import it from the types.ts file instead.

2022-06-29 00:06 UTC, tarhi-saad commented on assets/js/data/validation/test/selectors.ts
> +import type { FieldValidationStatus } from '../reducers';
We have an import error: Module '"../reducers"' has no exported member 'FieldValidationStatus'. Let's import it from the types.ts file instead.

2022-07-01 23:06 UTC, merged