Remove `useStoreSnackbarNotices` and interact directly with data store instead
woocommerce/woocommerce-gutenberg-products-block pull request #6411
Opened 2022-05-13 23:33 UTC by tarhi-saad

This PR will remove the `StoreSnackbarNoticesContext` (The value - `isSuppressed` - isn't used for the Snackbars, so we can safely remove the whole context). The notice system is provided by `@wordpress/notices` and a data store from `@wordpress/data` so we can interact directly with this store instead of confusing hooks and contexts.

- Remove `useStoreSnackbarNotices` hook.
- Remove `StoreSnackbarNoticesContext`.
- Make `StoreSnackbarNoticesContainer` a named export, so it can be imported from `@woocommerce/base-context`.
- Update all uses of `useStoreSnackbarNotices` so that it gets data from the `core/notices` store directly.
- Use the `StoreSnackbarNoticeContainer` in the cart & checkout blocks directly without a context Provider.

Fixes #5710

### To Fix

- [ ] The `SnackbarList` doesn't close for some reason, unlike in this PR #6215 (closed because of some complicated merge conflicts), even though we've applied the same changes. This is to be investigated!

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [x] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. Add a coupon to your store.
2. Add items to your cart.
3. Go to the Cart block, and apply the coupon. Ensure you see the snackbar notice for a successful coupon application.
4. **In a new tab**, open the Cart block again and remove the coupon. Ensure you see the snackbar notice for successful coupon removal.
5. Go back to the original tab and try removing the coupon, ensure you see an error message above the Cart.
6. Repeat the same steps but for the Checkout block.

### User Facing Testing
These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).
* [x] Same as above

2022-05-17 17:10 UTC, opr requested changes
This looks pretty good! Thanks for working on it

In terms of code, I think it's good to go, but I think we should update `https://github.com/woocommerce/woocommerce-blocks/blob/1db29ebd2d5cf541b547af5c60b6a00cc51bdb52/docs/block-client-apis/notices.md#L8-L7` though because it refers to `useStoreSnackbarNotices` which is no longer around.

2022-05-20 09:00 UTC, tarunvijwani reviewed
It worked like charm. Thank you for working on this, @tarhi-saad!

2022-05-25 08:42 UTC, tarhi-saad commented
> This looks pretty good! Thanks for working on it
> 
> In terms of code, I think it's good to go, but I think we should update `https://github.com/woocommerce/woocommerce-blocks/blob/1db29ebd2d5cf541b547af5c60b6a00cc51bdb52/docs/block-client-apis/notices.md#L8-L7` though because it refers to `useStoreSnackbarNotices` which is no longer around.

We should also update the `useStoreNotices` API doc, but maybe in a separate PR?

2022-05-25 08:53 UTC, opr commented
> We should also update the `useStoreNotices` API doc, but maybe in a separate PR?

Yes ok that sounds good! If you could create the follow up issues that would be great! 🙌🏼

2022-05-25 08:53 UTC, opr approved these changes

2022-05-25 21:00 UTC, merged