Clean up docs
woocommerce/woocommerce-gutenberg-products-block pull request #6550
Opened 2022-06-10 17:04 UTC by nielslange

In #6405, we adjusted the documentation of this repo. Due to a merge conflict, a few mistakes slipped in. This PR applies the following changes:

- Link the translation docs to the main README.md file.
- Move docs for internal developers into the corresponding subfolder.
- Delete obsolete files.

### Testing

1. Ensure that the translation docs are linked correctly.
2. Ensure that every file, that had been removed from the main docs folder, is available in a subfolder.

2022-06-17 11:10 UTC, opr requested changes
Good one Niels, but I noticed the testing notes went into `docs/internal-developers/testing` so we should update that here:
https://github.com/woocommerce/woocommerce-blocks/blob/update/clean-up-docs/.github/release-initial-checklist.md

and here:

https://github.com/woocommerce/woocommerce-blocks/blob/update/clean-up-docs/.github/patch-initial-checklist.md

2022-06-17 11:10 UTC, opr commented on docs/internal-developers/testing/releases/270.md
> +    -   Add the All Products block and the Hand-picked Products block in a page and verify (#2573): - That with the All Products block you can add the On Sale badge and it's correctly aligned in the
The `\` is visible in the rendered file

2022-06-17 11:10 UTC, opr commented on docs/internal-developers/testing/releases/270.md
> +-   The Hand-picked Products block discounted prices are not underlined. \
This bulletpoint is not rendered underneath the image in the rendered file.

2022-06-20 08:39 UTC, nielslange commented on docs/internal-developers/testing/releases/270.md
> +    -   Add the All Products block and the Hand-picked Products block in a page and verify (#2573): - That with the All Products block you can add the On Sale badge and it's correctly aligned in the
When looking at https://github.com/woocommerce/woocommerce-blocks/blob/fad6a96e657d84759c1ccb4346e3077b747bc3a3/docs/internal-developers/testing/releases/270.md, I do not see the `\` rendered.

2022-06-20 08:45 UTC, nielslange commented on docs/internal-developers/testing/releases/270.md
> +    -   Add the All Products block and the Hand-picked Products block in a page and verify (#2573): - That with the All Products block you can add the On Sale badge and it's correctly aligned in the
Good catch. The problem was caused by the list item in the next row. This should not be a separate list item, but belong to the previous one.

2022-06-20 08:46 UTC, nielslange commented on docs/internal-developers/testing/releases/270.md
> +-   The Hand-picked Products block discounted prices are not underlined. \
This is the same problem as mentioned in https://github.com/woocommerce/woocommerce-blocks/pull/6550#discussion_r901408862. The image should not be in a separate list item, but belongs to the previous one. I've corrected this problem.

2022-06-20 08:47 UTC, nielslange commented
@opr I've addressed all points you mentioned. Would you mind reviewing this PR again?

2022-06-20 08:52 UTC, opr approved these changes
Thanks Niels! Looks good now! 🚢 it 🥳

2022-06-20 17:04 UTC, merged