Fix: Convert Active Filters Block codebase to TypeScript
woocommerce/woocommerce-gutenberg-products-block pull request #6580
Opened 2022-06-16 11:42 UTC by dinhtungdu

Fixes #6494 

This PR converts the codebase of the Active Filters block to TypeScript. This also adds some type guards for attribute, stock and rating query state.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) .
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md)
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

N/A
### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

Ensure no regression after the conversion.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

N/A
### Changelog

N/A

2022-06-17 02:55 UTC, dinhtungdu commented
Note that among the filter blocks, only `<AttributeFilterBlock>` uses `@wordpress/components`. This PR updates the Filter Products by Attribute block to import from `wordpress-components` instead of `@wordpress/components` as part of #5611.

2022-06-20 16:19 UTC, gigitux requested changes

2022-06-20 16:19 UTC, gigitux commented on assets/js/types/type-defs/stock-status.ts
> +export type stockStatusOptions = {
I guess that it is a typo

```suggestion
export type StockStatusOptions = {
```

2022-06-20 16:19 UTC, gigitux commented on assets/js/blocks/active-filters/block.tsx
> +	const STOCK_STATUS_OPTIONS = getSetting< stockStatusOptions >(
This is a suggestion, feel free to skip :)

It would be cool if we will use `getSettingWithCoercion` util. You need to create a type guard for the type `StockStatusOptions`. If the type guard will return true, it will use the settings, otherwise, you will pass a fallback (in this case an empty array). In this way:
- we avoid the casting.
- we have validation at runtime, so less potential errors.

2022-06-20 16:20 UTC, gigitux approved these changes
Great work! There is a typo and there is a suggestion, but feel to free to skip :) 

I'm pre-approving the PR 👍

2022-06-21 00:14 UTC, dinhtungdu commented on assets/js/blocks/active-filters/block.tsx
> +	const STOCK_STATUS_OPTIONS = getSetting< stockStatusOptions >(
> This is a suggestion, feel free to skip :)

No, this makes a lot of sense to me. Thanks so much! I applied your suggestion in [d3041a7](https://github.com/woocommerce/woocommerce-blocks/pull/6580/commits/d3041a70525144b58f038612ddac341f5e61c0bb)

2022-06-21 00:15 UTC, dinhtungdu commented on assets/js/types/type-defs/stock-status.ts
> +export type stockStatusOptions = {
It is. Thanks for spotting it!

2022-06-21 08:01 UTC, gigitux commented on assets/js/blocks/active-filters/block.tsx
> +	const STOCK_STATUS_OPTIONS = getSetting< stockStatusOptions >(
Mmm, You need to replace `getSetting` with [`getSettingsWithCoercion`](https://github.com/woocommerce/woocommerce-blocks/blob/841cd4b6e3b89ae9d25f0d9f58864c8370ee9927/assets/js/settings/shared/utils.ts/#L28-L35) too.

2022-06-21 11:10 UTC, dinhtungdu commented
@gigitux E2E tests went so weird this time. I tried to fix some but looks like I will need more time. So I will move on with other tasks in the project and come back to fix this later. I tested and didn't find any regression. Can you please do another manual test so I can merge this one after that?

2022-06-21 14:53 UTC, merged

2022-06-21 14:54 UTC, dinhtungdu commented
Merged with 1/2 passing E2E tests workflow.