Create 2e2 tests for Cross-Sells block
woocommerce/woocommerce-gutenberg-products-block pull request #6983
Opened 2022-08-25 13:00 UTC by nielslange

Fixes #6559 

#### Notes

With #6554, we're bringing the Cross-Sells block to the Cart block. This PR aims to add e2e tests for the Cross-Sells block.

### Testing

#### Automated Tests
* [x] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [x] E2E tests

1. Check out this PR.
2. Start Docker Desktop.
3. Run the following command to start a fresh testing environment:
```
npm run wp-env destroy && npm run wp-env start
``` 
4. Run the following command to run only the added e2e test:
```
npm run test:e2e -- tests/e2e/specs/shopper/cart-checkout/cart.test.js
```
6. Verify that the test pass.

* [x] Do not include in the Testing Notes

2022-09-19 13:38 UTC, tarunvijwani requested changes
Thank you for working on this, @nielslange! I'm getting the following error when running the test cases in my local:
![image](https://user-images.githubusercontent.com/11503784/191030295-1f162f45-3508-4e51-a866-e42b790360f2.png)

2022-09-20 06:25 UTC, nielslange commented
> Thank you for working on this, @nielslange! I'm getting the following error when running the test cases in my local:

I wonder if this was a flaky test, @tarunvijwani. I just checked out this PR on my end and received this result:

<img width="752" alt="Screenshot 2022-09-20 at 13 22 09" src="https://user-images.githubusercontent.com/3323310/191182330-718f932a-7bb8-4fd5-9501-1b76546f1013.png">

Could you run the test again, to see if it actually was a flaky test?

If that does not work, maybe running the following commands will help:

```sh
nvm use && npm ci && npm run build
npm run wp-env destroy && npm run wp-env start
npm run test:e2e -- tests/e2e/specs/shopper/cart-checkout/cart.test.js
```

2022-09-20 06:47 UTC, nielslange commented on package.json
> +		"lint:php-fix": "composer run-script phpcbf ./src && composer run-script phpcbf ./tests/mocks/woo-test-helper",
I've updated these entries so that the `woo-test-helper` plugin can be linted and fixed.

2022-09-20 06:47 UTC, nielslange commented on tests/e2e/specs/backend/__fixtures__/cart.fixture.json
> +{"title": "Cart Block","pageContent": "<!-- wp:woocommerce/cart -->\n<div class=\"wp-block-woocommerce-cart is-loading\"><!-- wp:woocommerce/filled-cart-block -->\n<div class=\"wp-block-woocommerce-f
This change adds the Cross-Sells block to the Cart block.

2022-09-20 06:47 UTC, nielslange commented on tests/mocks/woo-test-helper/woo-test-helper.php
> +}
This section adds `32GB USB Stick` as a Cross-Sells product to `128GB USB Stick`. This setup is needed for the following test: https://github.com/woocommerce/woocommerce-blocks/blob/b2014309d9f041bfc1cac140df31efca0414731b/tests/e2e/specs/shopper/cart-checkout/cart.test.js#L116-L121

2022-09-20 07:37 UTC, tarunvijwani approved these changes
It worked, thank you! Let's merge it. 👍

2022-09-21 06:29 UTC, merged