Document the selectors for the wc/store/validation data store
woocommerce/woocommerce-gutenberg-products-block pull request #7086
Opened 2022-09-08 07:23 UTC by nielslange

Fixes #6947 

## Notes

In #6612, we ran a Data Store Migration. This PR aims to create the external documentation for the `wc/store/checkout` data store.

### Testing

1. Open https://github.com/woocommerce/woocommerce-blocks/blob/361b48b6220f57fab8a62b9a9272757530d6f14a/assets/js/data/validation/selectors.ts
2. Verify that `validation.md` from this PR documents all selector that appear in the document mentioned before.

* [x] Do not include in the Testing Notes

2022-09-14 21:50 UTC, opr reviewed
Hi Niels, thanks for documenting these, I have opened https://github.com/woocommerce/woocommerce-blocks/pull/7146 to track changes to this. Please could you revisit this documentation to update the selectors when that is merged?

2022-09-14 21:50 UTC, opr commented on docs/third-party-developers/extensibility/data-store/validation.md
> +### getValidationError
This selector actually returns a **function** which allows you to get an error based on ID. 

The reason for this is: the store can contain multiple errors. Getting an error by ID in a [`useSelect` like this](https://github.com/woocommerce/woocommerce-blocks/blob/c5d048127e221abe1d01d3e31eca563d9cc36603/assets/js/base/components/cart-checkout/totals/coupon/index.tsx#L48) would be tough.

By returning a function from the selector, the consumer can then use this function to get any error from the data store. I don't know if I'm fond of this anymore though.

I think we may be better to require the developer to select multiple errors individually from the store.

Taking this example: https://github.com/woocommerce/woocommerce-blocks/blob/c5d048127e221abe1d01d3e31eca563d9cc36603/assets/js/base/components/cart-checkout/totals/coupon/index.tsx#L48

and rewriting it we'd get:

```js
const { couponValidationError, getValidationErrorId } = useSelect(
		( select ) => {
			const store = select( VALIDATION_STORE_KEY );
			return {
				couponValidationError: store.getValidationError( 'coupon' ),
				getValidationErrorId: store.getValidationErrorId(),
			};
		}
	);
```

2022-09-14 21:50 UTC, opr commented on docs/third-party-developers/extensibility/data-store/validation.md
> +### getValidationErrorId
Same issue as above, this is not a problem with the work you've done, Niels. It's something we need to fix in the data store, so you may end up re-writing them.

2022-09-15 08:09 UTC, nielslange commented
> Hi Niels, thanks for documenting these, I have opened https://github.com/woocommerce/woocommerce-blocks/pull/7146 to track changes to this. Please could you revisit this documentation to update the selectors when that is merged?

Thanks for reaching out, @opr. Do you have a vague idea when https://github.com/woocommerce/woocommerce-blocks/pull/7146 might be merged?

2022-09-15 18:43 UTC, opr commented
> Thanks for reaching out, @opr. Do you have a vague idea when #7146 might be merged?

Hopefully within the next couple of days! Feel free to review it to move it along :wink:

2022-09-26 05:33 UTC, nielslange commented
> Hi Niels, thanks for documenting these, I have opened #7146 to track changes to this. Please could you revisit this documentation to update the selectors when that is merged?

Hi @opr, I see that #7146 had been merged, but the two functions in question `getValidationError()` and `getValidationErrorId` still show `string` as a return value. The corresponding file can be found on https://github.com/woocommerce/woocommerce-blocks/blob/73dbd80892268eb7caa046d098c9653ad9df7ab1/assets/js/data/validation/selectors.ts. Is this correct? I thought you mentioned that these functions would return a function itself.

2022-09-26 08:38 UTC, opr commented
> Hi @opr, I see that #7146 had been merged, but the two functions in question `getValidationError()` and `getValidationErrorId` still show `string` as a return value. The corresponding file can be found on https://github.com/woocommerce/woocommerce-blocks/blob/73dbd80892268eb7caa046d098c9653ad9df7ab1/assets/js/data/validation/selectors.ts. Is this correct? I thought you mentioned that these functions would return a function itself.

Yes this is correct now! Previously they would return a function, but that was a poor developer experience so I updated it :) Your documentation is correct now

2022-09-26 08:39 UTC, opr reviewed
@nielslange do you think it would be possible to add an example to each of the selectors?

2022-09-26 11:13 UTC, nielslange commented
> @nielslange do you think it would be possible to add an example to each of the selectors?

Sure. This should be possible, @opr. I'll look into this.

2022-10-07 10:45 UTC, alexflorisca approved these changes
Looks good, you misspelt `wether` that's all.

2022-10-07 10:45 UTC, alexflorisca commented on docs/third-party-developers/extensibility/data-store/validation.md
> +### getValidationError
I think this was solved in a different PR

2022-10-07 10:45 UTC, alexflorisca commented on docs/third-party-developers/extensibility/data-store/validation.md
> +-   `boolean`: Weather validation errors occured.
nitpick: `Whether` instead of `Weather`

2022-10-07 11:10 UTC, alexflorisca requested changes
Looks good, just one thing - see inline comment

2022-10-07 11:10 UTC, alexflorisca commented on docs/third-party-developers/extensibility/data-store/validation.md
> +### clearValidationErrors
This should be `clearValidationError` which takes the id of the error to clear

2022-10-07 11:20 UTC, alexflorisca approved these changes
Noice 👍

2022-10-07 11:24 UTC, merged