Add Product Query Support for Atomic SKU Block
woocommerce/woocommerce-gutenberg-products-block pull request #7385
Opened 2022-10-13 01:30 UTC by danielwrobert

Adds Product Query support for the atomic SKU block.

On the client side, when the SKU Block is used within the Product Query block, the markup will be rendered on the server side - no javascript related to the SKU block will be loaded.

Fixes #7332 

### Testing

1. Checkout this branch and run `npm start` (need to run the `start` command to catch the experimental flags).
1. Be sure that you have the latest version of the Gutenberg feature plugin installed and activated.
1. Add the `woocommerce/product-sku` block to the Product Query `INNER_BLOCKS_TEMPLATE` in `assets/js/blocks/product-query/constants.ts` under line 54 (**only for testing, remove afterwards**).
1. Create a post/page and add the Product Query block.
1. Save it.
1. Open the frontend side and confirm that:
    - No JS related to the Product SKU block is loaded (search in your network tab for `product-sku-frontend.js`).
    - The UI of the block is identical to on the editor side.
    - That the settings are reflected correctly (eg: custom style).
1. Back in the editor confirm that the Product SKU block can be added as a child of the Product query block via the inserter (inside **Product Query > Post Template** use **Insert Before/After** one of the existing children blocks).
1. For comparison, switch to trunk and add the All Products block to confirm that the aforementioned `product-sku-frontend.js` _is_ loaded.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental

2022-11-09 09:08 UTC, imanish003 commented
> The UI of the block is identical to on the editor side.

For me, UI looks different in editor vs frontend. 
| Editor | Frontend |
| - | -  |
| ![image](https://user-images.githubusercontent.com/16707866/200787557-d9c6b96d-7439-4cfd-8916-d2f7943a2677.png) | ![image](https://user-images.githubusercontent.com/16707866/200787632-adea4c34-8436-42f6-9c02-3f6c50340fe0.png) |

2022-11-09 09:12 UTC, imanish003 requested changes
> The UI of the block is identical to on the editor side.

For me, UI looks different in editor vs frontend. 
| Editor | Frontend |
| - | -  |
| ![image](https://user-images.githubusercontent.com/16707866/200787557-d9c6b96d-7439-4cfd-8916-d2f7943a2677.png) | ![image](https://user-images.githubusercontent.com/16707866/200787632-adea4c34-8436-42f6-9c02-3f6c50340fe0.png) |

----

Also, in this [PR for the Rating block](https://github.com/woocommerce/woocommerce-blocks/pull/7352), you converted js to ts. I am not sure if that is something we wanna cover in this PR too.

2022-11-09 20:44 UTC, danielwrobert commented
@imanish003 nice catch, thank you! Fixed in d6952b0c4.

The TS conversion took place separately but I have rebased this PR to include those changes from `trunk`.

2022-11-10 02:19 UTC, danielwrobert commented on assets/js/atomic/blocks/product-elements/sku/index.ts
> -	...sharedConfig,
Just want to confirm we don't need this here, as we're spreading/merging the same config object in the `registerExperimentalBlockType` function below.

It seems redundant to spread it here in this definition, unless I'm missing something.

2022-11-10 12:02 UTC, imanish003 approved these changes
Verified, Now UI on Editor and Frontend looks the same 🚀

2022-11-10 18:32 UTC, merged