Improve the performance of checking payment methods
woocommerce/woocommerce-gutenberg-products-block pull request #7413
Opened 2022-10-17 14:15 UTC by alexflorisca

This PR aims to improve performance of the C & C blocks by reducing the number of times we check that each payment method can pay. After the data store migration, we call `checkPaymentMethodsCanPay` for each change to the cart store. This is a function that does a lot of heavy processing (calls the `canPay` method for each payment method registered on the store). It was being run 4 times for standard payment methods, and 4 for express payment methods just on loading the cart page. 

I've done 2 things here:

1. I've debounced the function that runs on each cart store change, similar to the [pushChanges](https://github.com/woocommerce/woocommerce-blocks/blob/fix/too-many-calls-too-check-payment-methods-can-pay/assets/js/data/cart/push-changes.ts#L127) function.
2. I've refactored and renamed the `__internalInitializePaymentStore` function to `__internalUpdateAvailablePaymentMethods` to better reflect what it's doing. It now checks if the payment methods have been initialised and only calls the action to initialize them if they haven't. This allows us to call this function from a `.subscribe()` function without worrying that the `__internalSetPaymentMethodsInitialized` and `__internalSetExpressPaymentMethodsInitialized` will be called multiple times.

Fixes #7031

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. @opr You know what to do. Try and break it :)

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

This should speed things up slightly on the front-end

2022-10-19 11:19 UTC, opr requested changes
I will take over this since @alexflorisca is AFK.

2022-10-19 11:19 UTC, opr commented on assets/js/data/cart/update-payment-methods.ts
> +	select as wpDataSelect,
we can just import these normally now, the reason they were named before was because there were other methods already called `dispatch` and `select`

2022-10-24 14:56 UTC, ralucaStan commented
This branch has some conflicts

2022-10-24 14:57 UTC, ralucaStan commented
@alexflorisca does this close https://github.com/woocommerce/woocommerce-blocks/issues/7031? If so, let's add this info in the description

2022-10-25 08:50 UTC, alexflorisca commented
> @alexflorisca does this close #7031? If so, let's add this info in the description

It's already in the description. I'll catch up with @opr about this today and wrap it up

2022-10-25 10:34 UTC, alexflorisca commented on assets/js/data/cart/update-payment-methods.ts
> +import { STORE_KEY as PAYMENT_STORE_KEY } from '../payment/constants';
Need to import from constants here to avoid circular dependency

2022-10-25 13:09 UTC, opr approved these changes
Thanks Alex, working well for me! Code changes look fine.

2022-10-25 13:20 UTC, alexflorisca commented
Cool, E2E tests seem unrelated so merging

2022-10-25 13:21 UTC, merged