use correct path when running php unit tests
woocommerce/woocommerce-gutenberg-products-block pull request #7489
Opened 2022-10-26 15:44 UTC by senadir

When running PHP unit tests, we mount the current folder to docker, to have flexibility, we assign the current folder name in docker instead of hardcoding.

The part that inferred the folder name didn't take into account that folders and parent folders might have spaces in them, switching from `$(basename $(pwd))` to `$(basename "$(pwd)"` because when passing `$(pwd)` directly with unescaped spaces, you're passing N values to basename, when wrapping it in "" you're passing a single value.

### Testing

- Change the parent folder name of your folder to something with spaces
- Run `npm run test:php`, it should work fine.
- Rename the current folder to something with spaces, run the command again, it should work.

2022-10-26 16:10 UTC, dinhtungdu approved these changes
LGTM! 🎉

2022-10-26 19:07 UTC, danieldudzic commented
Hmm, it still seems to be broken for me:

![danieldudzic_Dannys-MacBook____Local_Sites_ratings_app_public_wp-content_plugins_woocommerce-blocks_and_use_correct_path_when_running_php_unit_tests_by_senadir_·_Pull_Request__7489_·_woocommerce_woocommerce-blocks](https://user-images.githubusercontent.com/905781/198114748-13762b09-f927-4a54-8af9-895024e84da1.jpg)

2022-10-28 12:16 UTC, alexflorisca approved these changes
This works for me too, but I wonder why it doesn't work for @danieldudzic? Maybe let's get to the bottom of that before we merge

2023-02-28 10:46 UTC, ralucaStan commented
Why does this PR have the on hold label @senadir ?

2023-03-02 11:18 UTC, wavvves commented
It does not work for me too:
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/17236129/222413059-66cbb455-d01d-4675-8b92-b0482d32d76c.png">

@dinhtungdu I see the path for your PHPUnit conf does not have spaces, and I'm wondering if Alex's was the same. Can you re-test using a clean copy? I suspect wp-env is not updating paths.

In the meantime, I'll test some changes to try and fix this.

2023-03-02 12:35 UTC, nielslange commented
> It does not work for me too

Thanks for reviewing this PR, @wavvves. Initially, I faced the same problem. I solved the problem by running the following command:

```sh
npm run wp-env destroy && npm run wp-env start
```

I hope that commend helps to run `npm run test:php` successfully.

2023-03-02 12:36 UTC, wavvves commented
> > It does not work for me too
> 
> 
> 
> Thanks for reviewing this PR, @wavvves. Initially, I faced the same problem. I solved the problem by running the following command:
> 
> 
> 
> ```sh
> 
> npm run wp-env destroy && npm run wp-env start
> 
> ```
> 
> 
> 
> I hope that commend helps to run `npm run test:php` successfully. 

I cleared out wp-env and started fresh with a new git clone and problem still persisted.

2023-03-02 12:39 UTC, wavvves requested changes

2023-03-02 12:39 UTC, wavvves commented on package.json
> +		"test:php": "npm run wp-env run phpunit '/var/www/html/wp-content/plugins/$(basename \"$(pwd)\")/vendor/bin/phpunit -c /var/www/html/wp-content/plugins/$(basename \"$(pwd)\")/phpunit.xml.dist'",
Hey @nielslange previous fix does not work, and there's no need to use basename here. Still I feel you can never really win with these things, we just keep trading bugs 🙄😂

```suggestion
		"test:php": "npm run wp-env run phpunit '/var/www/html/wp-content/plugins/${PWD##*/}/vendor/bin/phpunit -c /var/www/html/wp-content/plugins/${PWD##*/}/phpunit.xml.dist'",
```

2023-03-02 12:45 UTC, nielslange commented on package.json
> +		"test:php": "npm run wp-env run phpunit '/var/www/html/wp-content/plugins/$(basename \"$(pwd)\")/vendor/bin/phpunit -c /var/www/html/wp-content/plugins/$(basename \"$(pwd)\")/phpunit.xml.dist'",
> Hey @nielslange previous fix does not work, and there's no need to use basename here. Still I feel you can never really win with these things, we just keep trading bugs 🙄😂

Thanks for the suggestions. Can you think of a better approach to solve the current problem?

2023-03-02 12:47 UTC, wavvves commented on package.json
> +		"test:php": "npm run wp-env run phpunit '/var/www/html/wp-content/plugins/$(basename \"$(pwd)\")/vendor/bin/phpunit -c /var/www/html/wp-content/plugins/$(basename \"$(pwd)\")/phpunit.xml.dist'",
That is the best alternative I can think of 😅

2023-03-02 15:36 UTC, nielslange commented on package.json
> +		"test:php": "npm run wp-env run phpunit '/var/www/html/wp-content/plugins/$(basename \"$(pwd)\")/vendor/bin/phpunit -c /var/www/html/wp-content/plugins/$(basename \"$(pwd)\")/phpunit.xml.dist'",
Given that this is the best alternative you can think of, I'm happy to accept your suggestion, @wavvves! 🙏

2023-03-06 09:52 UTC, dinhtungdu commented
> @dinhtungdu I see the path for your PHPUnit conf does not have spaces, and I'm wondering if Alex's was the same. Can you re-test using a clean copy? I suspect wp-env is not updating paths.

@wavvves I tested using a clean copy but the initial fix still works for me.

I also tested your suggestion and it works for me too. I prefer yours because it is shorter and cleaner.

cc @nielslange

2023-03-07 03:21 UTC, merged