Convert product-element/sku to TypeScript
woocommerce/woocommerce-gutenberg-products-block pull request #7533
Opened 2022-10-31 07:25 UTC by nielslange

Fixes #7095 

Currently, the `product-element/sku` is still written in JS and is using [prop-types](https://www.npmjs.com/package/prop-types) for type checking. This PR aims to convert `product-element/sku` to TypeScript.

### Testing

#### User Facing Testing

1. Create a test page and add the `Single Product block` to it.
2. Verify that the `Product SKU inner block` is still visible.

* [x] Do not include in the Testing Notes

2022-10-31 11:05 UTC, mikejolley requested changes
Added some feedback. Let me know what you think. I think the `import type` suggestion is most important.

2022-10-31 11:05 UTC, mikejolley commented on assets/js/atomic/blocks/product-elements/sku/block.tsx
> +import { HTMLAttributes } from 'react';
This is only used for typing things, so rather than import into the app, can we not say:

`import type {...`

2022-10-31 11:05 UTC, mikejolley commented on assets/js/atomic/blocks/product-elements/sku/block.tsx
> +import { Attributes } from './types';
This could also be `import type`.

2022-10-31 11:05 UTC, mikejolley commented on assets/js/atomic/blocks/product-elements/sku/block.tsx
>   * @param {Object} props             Incoming props.
This doc block isn't necessary with the type addition.

2022-10-31 11:05 UTC, mikejolley commented on assets/js/atomic/blocks/product-elements/sku/types.ts
> +export interface Attributes {
Should this have a more specific name to indicate that it's the Attributes of a Block or is it clear enough?

2022-10-31 12:33 UTC, nielslange commented
> Added some feedback. Let me know what you think. I think the `import type` suggestion is most important.

Thanks for your review, @mikejolley. I do appreciate your suggestions and implemented all of them. Would you mind doing another review?

2022-11-01 16:54 UTC, mikejolley approved these changes
Looks good now. Thanks for making the changes.

2022-11-02 06:48 UTC, merged