Add woocommerce_blocks_loaded hook information to actions doc
woocommerce/woocommerce-gutenberg-products-block pull request #7600
Opened 2022-11-07 15:19 UTC by tarunvijwani

We were not clear about the usage of `woocommerce_blocks_loaded`.  With this PR, we're informing the developers to use `woocommerce_blocks_loaded` explicitly to ensure WooCommerce Blocks are loaded and ready to use. 

More details in the internal discussion p1664968789479409-slack-C8X6Q7XQU

Fixes #7432

## Changes in the PR
Added  `woocommerce_blocks_loaded` information to [Actions doc.](https://github.com/woocommerce/woocommerce-blocks/blob/13dfa9db23864948305e8389898ec61204d461e3/docs/third-party-developers/extensibility/hooks/actions.md#woocommerce_blocks_loaded)

2022-11-08 09:59 UTC, alexflorisca commented on docs/third-party-developers/extensibility/hooks/actions.md
> +This is because the functions hooked into plugins_loaded on the same priority load in an inconsistent and unpredictable manner. You must use the `woocommerce_blocks_loaded` hook to guarantee that all
nitpick: put `plugins_loaded` in code formatting

2022-11-08 10:00 UTC, alexflorisca approved these changes
Nice work @tarunvijwani, thanks for picking this up, I was planning to work on this during the cooldown but I had to take some AFK.

2022-11-08 16:04 UTC, mikejolley commented
@tarunvijwani @alexflorisca Don't merge this yet. Details to follow.

2022-11-08 16:10 UTC, mikejolley requested changes
The documentation for actions and filters is generated automatically. These changes would be lost on regeneration via `npm run docs`.

Documentation should be added inline, above `do_action( 'woocommerce_blocks_loaded' );` in the actual codebase. If you need to include example code, the script generator supports an `@example` docblock e.g.:

```
@example See docs/examples/checkout-order-processed.md
```

Can we see if we can get docs generated for this hook instead via the script?

2022-11-09 09:30 UTC, ralucaStan requested changes
@tarunvijwani I've added a comment

2022-11-09 09:30 UTC, ralucaStan commented on docs/third-party-developers/extensibility/hooks/actions.md
> +```
I think the structure can be improved here:
- `Fires when the woocommerce blocks are loaded and ready to use.` is related to do_action, from the order here it looks like it's related to add_action
- we can use add action to provide an example, just like [here](https://github.com/woocommerce/woocommerce-blocks/blob/00a1174aebefae2b37178a3ded68cc6c8d56bbf4/docs/third-party-developers/extensibility/hooks/actions.md#example)


The expected result would be something like...

Fires when the woocommerce blocks are loaded and ready to use.

```php
do_action( 'woocommerce_blocks_loaded' )
```
### Example

# Do something when blocks is loaded

```php
// The action callback function.
function my_function_callback( ) {
// start doing your WC Blocks related logic
}

add_action( 'woocommerce_blocks_loaded', 'my_function_callback' );
```

2022-11-09 09:42 UTC, ralucaStan approved these changes

2022-11-09 09:42 UTC, ralucaStan commented on docs/third-party-developers/extensibility/hooks/actions.md
> +```
This change is not needed, the change from @senadir took care of my suggestion, and we can skip the example.

2022-11-09 09:47 UTC, senadir approved these changes
Moved the docs to the actual function and fixed some PHP parsing issues that prevented the hook from being included.

2022-11-09 09:47 UTC, senadir commented on bin/add-doc-footer.sh
> +find ./docs -name "*.md" -or -path "./docs/examples/*" -prune|while read filename; do
grep was failing and those files under `./docs/examples` never got updated.

2022-11-09 09:47 UTC, senadir commented on bin/hook-docs/data/actions.json
> +        },
Bootstrap file had a syntax error and never actually run, now it's running and it picked up this one.

2022-11-09 09:47 UTC, senadir commented on bin/hook-docs/data/actions.json
> +        },
doc gen didn't run when the rate limiting PR was created so this was missed.

2022-11-09 09:47 UTC, senadir commented on src/Domain/Bootstrap.php
> +				return $container->get( StoreApi::class )->container()->get( \Automattic\WooCommerce\StoreApi\Formatters::class );
This was failing parsing because `::` expects a class name but `$container->get( StoreApi::class )` returns an instance of a class.

2022-11-09 12:33 UTC, mikejolley commented on bin/add-doc-footer.sh
> +find ./docs -name "*.md" ! -path "./docs/examples*"  ! -path "./docs/internal-developers*"|while read filename; do
This now correctly excludes examples and internal developer docs from including the feedback text.

2022-11-09 12:35 UTC, mikejolley requested changes
Doc generation is fixed up here now, so I think all that is needed is to respond to @ralucaStan's feedback regarding the new hook documentation, then regenerate it one last time.

cc @senadir footers are fixed up here now.

2022-11-09 12:37 UTC, mikejolley approved these changes
Looks like the change was not needed. Nevermind :)

2022-11-09 13:19 UTC, ralucaStan commented
> Looks like the change was not needed. Nevermind :)

@mikejolley if you see value in that example let's add it then

2022-11-09 15:52 UTC, ralucaStan commented
There are some conflicts with `composer.json` and `composer.lock` files on this PR introduced after this commit 964b62a39edb35b9c94f1710d008f22f57935ef6 @mikejolley 

The changed files in this PR are also now at over 140, I noticed some other docs were formated. Was that expected?

2022-11-09 15:57 UTC, senadir commented
> The changed files in this PR are also now at over 140, I noticed some other docs were formated. Was that expected?

Yes, some of them has dead links that are now updated. Other had a footer that they shouldn't have, some actions and filter were never picked up by the documentation script.

2022-11-10 08:52 UTC, merged