Document the selectors for the wc/store/cart data store
woocommerce/woocommerce-gutenberg-products-block pull request #7708
Opened 2022-11-17 20:01 UTC by tarunvijwani

In this PR, we're adding the document the selectors for the cart store. 

Fixes #7690

#### Changes in the PR:

- Fixed the readme file links. 
- Added selectors doc for cart store. 

#### Testing

1. Go to [readme file link of this branch](https://github.com/woocommerce/woocommerce-blocks/blob/fdbf366f3820e2e10934f63cc582ae7ed7a0fbdc/docs/third-party-developers/extensibility/data-store/README.md).
2. Confirm the link to payment doc is working fine. 
3. Confirm the link to Cart doc is working fine. 
4. Review the Cart doc. 

* [ ] Do not include in the Testing Notes 

### Changelog

> Add cart selector documentation

2022-11-21 19:12 UTC, opr requested changes
Hey @tarunvijwani thanks for this! It looks really good, I just wonder if we could add a little more description to some of the items? I feel like having a little more context about what some keys do would be really helpful to third party devs.

2022-11-21 19:12 UTC, opr commented on docs/third-party-developers/extensibility/data-store/cart.md
> +- `tax_lines`- array containing the tax lines
I think the language here could be a little clearer, for example `total_items` is the sum total of items in the cart without the tax or shipping applied to that item. Please could you try to improve this?

2022-11-21 19:12 UTC, opr commented on docs/third-party-developers/extensibility/data-store/cart.md
> +Returns the cart errors from state.
Could we be a little more descriptive here? Where are these errors from?

2022-11-21 19:12 UTC, opr commented on docs/third-party-developers/extensibility/data-store/cart.md
> +- `quantity_limits`- object containing the quantity limits
Do you think it would be useful to describe the shape of these objects here? `prices` and `totals` too?

2022-12-09 18:45 UTC, tarunvijwani commented
Thank you for the suggestions @opr! I have made the changes. 👍

2022-12-12 10:37 UTC, opr approved these changes
Thanks Tarun, looks better now! Let's merge 😎

2022-12-12 13:07 UTC, merged