[NOT Review]Fix/7921 product query product search result preview
woocommerce/woocommerce-gutenberg-products-block pull request #7965
Opened 2022-12-16 10:51 UTC by gigitux

⚠️ ⚠️ THIS PR IS WIP

Fixes #

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|        |       |

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1.
2.
3.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

### Changelog

> Add suggested changelog entry here.

2023-01-18 22:34 UTC, nefeline commented
Hey @gigitux ! I see this PR is flagged as blocked by #7956 : All good to review it right away or are more changes expected here after the blocker is removed & the other PR merged?

2023-01-19 08:48 UTC, gigitux commented
> Hey @gigitux ! I see this PR is flagged as blocked by #7956 : All good to review it right away or are more changes expected here after the blocker is removed & the other PR merged?

You can already review it. This PR includes changes from #7956. I suggest reviewing #7956 and, after that, reviewing this PR.

2023-01-19 10:36 UTC, nefeline commented
Great work! 👏 

> I suggest reviewing https://github.com/woocommerce/woocommerce-blocks/pull/7956 and, after that, reviewing this PR.

I see @danieldudzic is already assigned to review that one, so I'll focus here, but heads up, the tests here are failing (both on the CI and locally). 

### User facing test results:

> Edit the Product Search Results template.
> Add the Products block.
> Add the Sale Status filter and select Show only products on sale.

✅ Confirmed that when the sale status filter is enabled, only products on sale are displayed

> Now, enable Inherit query from template.
> Be sure that all products are displayed.

✅ Confirmed all products are displayed when the Inherit query from template option is enabled.

> Disable Inherit query from template.
> Be sure that only on-sale products are visible.

✅ Confirmed only on-sale products are visible.

### e2e test results:

The tests on this branch are failing. When running the product-query test suite locally, they also failed, so probably worth investigating the causes.

2023-01-19 17:02 UTC, gigitux commented
Thanks for the review!

> ### e2e test results:
> The tests on this branch are failing. When running the product-query test suite locally, it also failed, so probably worth investigating the causes.

The E2E tests fail in trunk too. I will take a look at them next week!

2023-03-15 09:06 UTC, imanish003 approved these changes
I tested the PR & it's working as expected. I left one minor suggestion but pre-approving PR because that's not a blocker 🚀

2023-03-15 09:06 UTC, imanish003 commented on assets/js/blocks/product-query/inspector-controls.tsx
> +								/>
AFAIU `queryObjectBeforeInheritEnabled` & `defaultWooQueryParams` will be used in only `wooInherit`.  If that's the case then I think instead of passing these as props, we should calculate it inside `wooInherit` function. 

As we are using hooks (ex. `usePrevious`), I believe we will need to extract the wooInherit function as a component, something like this.
```
wooInherit: WooInheritToggleControl
```

IMO this would make the code easier to understand, but please feel free to ignore my suggestion if you disagree.

2023-03-15 14:16 UTC, gigitux commented on assets/js/blocks/product-query/inspector-controls.tsx
> +								/>
Nice suggestion! I addressed it via 33fbac9cf1e874904c36164dc2f54104ba0f3a0b.
I tested it, and it works. Please, could you recheck it?

2023-03-16 09:20 UTC, imanish003 requested changes
Hi @gigitux,
There is one issue. If I set keyword in filters as shown in screenshot below:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/16707866/225570498-aaa5b04c-c362-4ec6-b708-72950f6f09e9.png">

And then enable `Inherit query from template` then, keyword effect is still there, i.e., I still see products that are filtered by the Keyword. 

Is it expected? AFAIK filters shouldn't have any effect when `Inherit query from template` is enabled. I might be wrong 🤷🏻‍♂️

2023-03-16 09:49 UTC, gigitux commented
> Hi @gigitux, There is one issue. If I set keyword in filters as shown in screenshot below: <img alt="image" width="279" src="https://user-images.githubusercontent.com/16707866/225570498-aaa5b04c-c362-4ec6-b708-72950f6f09e9.png">
> 
> And then enable `Inherit query from template` then, keyword effect is still there, i.e., I still see products that are filtered by the Keyword.
> 
> Is it expected? AFAIK filters shouldn't have any effect when `Inherit query from template` is enabled. I might be wrong 🤷🏻‍♂️

That is a good point, but I can replicate this issue on the trunk. I think that it is a bug in the Query Loop block. Should we open another issue or write the issue on https://github.com/WordPress/gutenberg/issues/29438?

2023-03-16 10:02 UTC, imanish003 approved these changes
@gigitux You are right. We can open a new issue on Gutenberg repo. Approving the PR 🚀

Although I think the issue you mentioned is a different one & not related to Inherit query from template toggle. You can also see [my comment](https://github.com/WordPress/gutenberg/issues/29438#issuecomment-1413572661) on the issue.

2023-03-16 10:04 UTC, gigitux commented
Thanks for the review!

> We can open a new issue on Gutenberg repo.

Can you take care of this?

2023-03-16 10:04 UTC, merged

2023-03-16 10:08 UTC, imanish003 commented
> Can you take care of this?

Sure, I will take case of this 🤝