Attribute, Rating and Stock filters: Fix the dropdown indicator icon display
woocommerce/woocommerce-gutenberg-products-block pull request #8080
Opened 2023-01-03 13:06 UTC by danieldudzic

This PR fixes the display logic of the dropdown indicator icon (chevron) for the `Single` option of `Allow selecting multiple options?` setting.

Fixes #8075

### Screenshots

| Before | After |
| ------ | ----- |
|![Products_–_ratings-2](https://user-images.githubusercontent.com/905781/210362266-de6a9b7b-1ad4-4877-ae24-b826790b12e6.jpg)|![Products_–_ratings](https://user-images.githubusercontent.com/905781/210362300-2a71177e-b78e-476c-b02c-27393a014e02.jpg)|

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Add the Attribute, Rating and Stock filter blocks.
2. Set the `Display Style` to `Dropdown` and `Allow selecting multiple options?` to `Single`.
3. Ensure the dropdown chevron displays correctly both in the editor and the page.
4. Ensure there's no conflict between the cancel 'x' icon and the chevron when dropdown options are selected.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Attribute, Rating and Stock filters: Dropdown indicator icon display fix.

2023-01-03 15:04 UTC, kmanijak requested changes
Thanks for working on this. As I wrote in a comment I spotted one issue with the Multiple version of the Dropdowns.

If you feel like you want, you can also cover [this issue](https://github.com/woocommerce/woocommerce-blocks/issues/7889) 💪

2023-01-03 15:04 UTC, kmanijak commented on assets/js/blocks/attribute-filter/block.tsx
> +						{ checked.length === 0 && ! isLoading && (
That change covers the case where dropdown is set to Single choice, but it little bug for dropdowns with Multiple choice: when user selected at least one option, the chevron would be hidden, even though there's more options to choose from. So this case should also be covered. Maybe something among those lines:

```suggestion
						{ multiple || checked.length === 0 && ! isLoading && (
```

There's also [this issue](https://github.com/woocommerce/woocommerce-blocks/issues/7889) about hiding chevron if there's no more options to choose from in Multiple choice dropdowns, which now I think it's much easier than I thought at the time I created the issue 🙈 I think the above suggestion could be extended with:

```
const showChevron = multiple ?
  checked.length < displayedOptions.length : // MULTIPLE: show chevron only when not every option is chosen
  checked.length === 0                       // SINGLE: show chevron only when none option is chosen
```

to cover each case.

But if you feel that's out of scope of this PR it's fine and you can just stick to the first suggestion 🙌

2023-01-04 08:49 UTC, kmanijak approved these changes
Works like a charm 🎉 

Considering that you fixed https://github.com/woocommerce/woocommerce-blocks/issues/7889 as well, you can mention it in the description (so the issue will be closed) and extend the testing steps, so it's covered during release.

But anyway, approving! 👍

2023-01-04 17:21 UTC, danielwrobert approved these changes
I also tested and everything works according to the test plan!

It would be nice to be able to click the input field when the dropdown is open a second time to close it, as opposed to clicking outside the field (see below). That is beyond the scope of this PR and I can create an Issue to investigate separately – I mainly wanted to make a note of it since I noticed while testing. 🙂

![CleanShot 2023-01-04 at 12 17 41](https://user-images.githubusercontent.com/481776/210612780-d9bd55e9-f89b-40ef-a346-5c3a7966eeec.gif)

Nice work! 🚀

2023-01-04 17:37 UTC, merged