Allow observers to set `billingAddress` by returning `billingData`
woocommerce/woocommerce-gutenberg-products-block pull request #8163
Opened 2023-01-11 16:13 UTC by opr

This is required since we didn't correctly deprecate `billingData` when we changed the name to `billingAddress`, so some extensions could still be returning `billingData` to the `onPaymentProcessing` observer.

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### Internal Developer Testing

1. Install the Stripe plugin from source.
2. Go to https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8ffd22aff3b06eda02a1ae2fd8368b71450b36a9/client/blocks/credit-card/use-payment-processing.js#L136 and change `billingData` to:
```js
billingData: {
  ...bilingData,
  first_name: 'Set from',
  last_name: 'Stripe plugin',
}
```
4. Add items to your cart and load the Checkout block.
5. Open the console and enable `Preserve log`.
6. Check out using Stripe.
7. Ensure you see a deprecated notice for `billingData`.
8. Edit the previous code, and change the key: `billingData` to `billingAddress`
```js
billingAddress: {
  ...bilingData,
  first_name: 'Set from',
  last_name: 'Stripe plugin',
}
```
9. Check out again and ensure the deprecation notice does not appear.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Skipping.

2023-01-12 11:22 UTC, alexflorisca requested changes
Nice catch, we also need to do this in the errorResponse condition as well. We could maybe optimise it so we destructure the data from `response.meta` outside the `if...else` statement

2023-01-12 12:45 UTC, alexflorisca approved these changes
Noice one, looks good 👍

2023-01-17 18:07 UTC, opr commented
@alexflorisca I added tests, and also changed `shippingData` to `shippingAddress` - please re-test, and also re-test with `shippingData` and `shippingAddress`, as well as with `billingData`.

2023-01-19 11:25 UTC, alexflorisca approved these changes
Nice one, tested with the shippingAddress and all good. Thanks for writing the tests and the type-guards as well, stellar work ⭐

2023-01-19 11:25 UTC, alexflorisca commented on assets/js/data/payment/thunks.ts
> +				const {
It would be helpful to add a comment here to explain this craziness

2023-01-19 12:35 UTC, opr commented on assets/js/data/payment/thunks.ts
> +				const {
Good idea, added.

2023-01-23 16:27 UTC, opr commented
I think the E2E fails are unrelated to these changes. I will merge this.

2023-01-23 16:28 UTC, merged