Add how checkout block processes an order to the repo docs
woocommerce/woocommerce-gutenberg-products-block pull request #8240
Opened 2023-01-19 15:16 UTC by alexflorisca

This PR adds the "How The Checkout Block Processes An Order" P2 (pdFofs-hi-p2) to the repo docs based on @beaulebens suggestion (pdFofs-hi-p2#comment-306)

2023-01-19 16:53 UTC, tarunvijwani commented on docs/third-party-developers/extensibility/README.md
> +| [How the Checkout Block processes an order](./checkout-block/how-checkout-processes-an-order.md) | The `IntegrationInterface` class and how to use it to register scripts, styles, and data with WooC
```suggestion
| [How the Checkout Block processes an order](./checkout-block/how-checkout-processes-an-order.md) | The detailed inner workings of the Checkout Flow. |
```

I think you missed updating the description here. 🙂

2023-01-20 10:29 UTC, alexflorisca commented on docs/third-party-developers/extensibility/README.md
> +| [How the Checkout Block processes an order](./checkout-block/how-checkout-processes-an-order.md) | The `IntegrationInterface` class and how to use it to register scripts, styles, and data with WooC
good spot, thanks Tarun!

2023-01-20 21:06 UTC, tarunvijwani requested changes
Thank you for working on this! This is very useful document. It helped me learn the whole checkout flow. 

I feel the tone and sentence framing used in the document could be modified better. It is good for our internal p2s. However, for the product documents, it should sound formal.


Example: 
This lives [here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/context/providers/cart-checkout/checkout-provider.js), and wraps all the contexts mentioned above around the CheckoutProcessor component.

Can be converted to:

The [Checkout Provider](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/base/context/providers/cart-checkout/checkout-provider.js)  wraps all the contexts mentioned above around the CheckoutProcessor component.

`This is what happens when a user places an order:` can be converted to `Below is the complete checkout flow:`

I'd love to pair with you once you're back from AFK and we can work on it together. It would be a great learning for me. 🙂

2023-02-02 15:46 UTC, tarunvijwani approved these changes
The doc looks good! Thank you so much for publishing it. 👍

2023-02-02 17:25 UTC, merged