Checkout - Available Payment Method Filtering
woocommerce/woocommerce-gutenberg-products-block pull request #8441
Opened 2023-02-15 14:13 UTC by mikejolley

This is a solution for compatibility with the `woocommerce_available_payment_gateways` filter. This filter hook can be used to remove payment methods from the core checkout, and in our case, can prevent certain gateways from being used to checkout. It doesn't however filter visible methods in the Checkout Block because we're not using it.

You can test this filter with some custom code:

```
add_filter(
	'woocommerce_available_payment_gateways',
	function( $payments ) {
		unset( $payments['cod'] );
		return $payments;
	}
);
```

The above example would disable the cash on delivery payment method.

The problem we have is that the settings API grabs all registered/enabled payment gateways early on and statically, so cart data and other globals cannot reliable be consumed by `woocommerce_available_payment_gateways`, which would also become stale if cart data changed.

The solution I've come up with in this PR is to return available payment methods with the cart response, so the list of payment methods can be filtered on the fly as the cart changes. I've also updated the checkout response to correctly filter available methods, since for some reason it was returning all of them in the `enum`.

Fixes #8322

This PR could use feedback on approach and testing. I had to update tests so that the cart listed available methods that were registered/mocked in the test suite. cc @senadir 

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Add the code above to your site. 
2. Ensure COD, BACs are enabled.
3. Go to the checkout page. COD should not be shown on checkout.
4. Place an order successfully with an available method. 

You can also test an OPTIONS request to `/wp-json/wc/store/checkout` to check the enum is valid for `payment_methods`. It should only include available methods.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Added support for `woocommerce_available_payment_gateways` to the Store API

2023-02-22 07:31 UTC, tarhi-saad reviewed
@mikejolley, I followed the testing instruction, and every time the `cod` payment method is also filtered out in the Checkout Block. I used the same code snippet in the PR description and added it using the `Code Snippet` plugin! I also tried debugging the issue locally, and I was indeed getting a `cartData` with the filtered-out `cod` payment method from the store API `/wc/store/v1/cart`. Do you have any idea what I may be doing wrong?

2023-02-22 11:29 UTC, mikejolley commented
@tarhi-saad sorry I am not following you. COD should be filtered out - thats what the snippet does. 

If you test the snippet against trunk you'll see COD on checkout and when you place the order you'll see `The cod payment gateway is not available.`.

2023-02-22 11:50 UTC, tarhi-saad commented
@mikejolley, I think I misunderstood the following explanation from the PR description:

> This filter hook can be used to remove payment methods from the core checkout... It doesn't however filter visible methods in the Checkout Block because we're not using it

Does this mean the code snippet should filter out the `cod` payment method from the Woo core's checkout and keep it visible in the Checkout Block? In my tests, the `cod` snippet was filtered out from both checkouts. (i.e., core and Blocks)

2023-02-22 16:06 UTC, mikejolley commented
@tarhi-saad That statement was describing the current behaviour. The hook works for core but not for blocks. With this PR, it should disable COD for both.

2023-02-23 12:13 UTC, tarhi-saad requested changes
Thank you, @mikejolley, for the explanation! 🙌 I've reviewed the PR and left some suggestions below!

2023-02-23 12:13 UTC, tarhi-saad commented on assets/js/base/context/hooks/cart/use-store-cart.ts
>  } from '@woocommerce/block-data';
This is unrelated to the changes in this PR, but could we fix the TS error in this line? The TS error is `Projects must list all files or use an 'include' pattern.`, and the possible solution is to update the file `assets/js/base/context/hooks/tsconfig.json` by adding the path `"../../../data/index.ts"` to the `"include"` list!

2023-02-23 12:13 UTC, tarhi-saad commented on src/StoreApi/Schemas/V1/CartSchema.php
> +				'description' => __( 'List of available payment method IDs that can used to process the order.', 'woo-gutenberg-products-block' ),
```suggestion
				'description' => __( 'List of available payment method IDs that can be used to process the order.', 'woo-gutenberg-products-block' ),
```

2023-02-23 12:13 UTC, tarhi-saad commented on assets/js/data/payment/utils/check-payment-methods.ts
> +		  ).filter( ( key ) => canPayArgument.paymentMethods.includes( key ) );
@mikejolley, this filter is causing a regression in the `editor`. We will always get the static list of available payment gateways from the `previewCart` (i.e., `[ 'cod', 'bacs', 'cheque' ]`). This will cause showing any other payment gateway in the notice of incompatible gateways:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/14235870/220891010-a8d94455-0f9d-4bf9-8ac2-5d64ea7b5aad.png">

We can get payment methods from the cart instead of the preview, even when we are in the editor. But when I tested it, `cod` showed as an incompatible gateway! So, maybe we should take another approach.

So, the following line filters out `cod` payment method from the list of available payment gateway:

```TS
filter( ( key ) => canPayArgument.paymentMethods.includes( key ) );
```

And the notice of incompatible gateways using the `globalPaymentMethods` to get the list of enabled gateways. See https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/payment/selectors.ts#L16-L24 and https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/payment/selectors.ts#L113-L125. And see https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypes/Checkout.php#L315-L332 for the `globalPaymentMethods` definition.

Does this hook `woocommerce_available_payment_gateways` hide a payment method and doesn't disable it?

2023-02-23 12:13 UTC, tarhi-saad commented on assets/js/data/payment/test/check-payment-methods.tsx
> +	} );
We have a TS error in this line. We need a `CartResponse` object. We can use the `previewCart` object which include already these 3 payment methods:

```js
import { previewCart } from '@woocommerce/resource-previews';

wpDataFunctions.dispatch( CART_STORE_KEY ).receiveCart( previewCart );
```

2023-02-23 12:13 UTC, tarhi-saad commented on assets/js/blocks/cart-checkout-shared/payment-methods/test/payment-methods.js
> +		} );
`defaultCartState` isn't a `CartResponse` object. We can use the `previewCart` object, which includes these payment methods: `[ 'cod', 'bacs', 'cheque' ]`

```js
wpDataFunctions.dispatch( CART_STORE_KEY ).receiveCart( {
		...previewCart,
		payment_methods: [ 'cod', 'credit-card' ],
} );
```

2023-03-06 13:09 UTC, mikejolley commented on assets/js/data/payment/utils/check-payment-methods.ts
> +		  ).filter( ( key ) => canPayArgument.paymentMethods.includes( key ) );
I've modified it to only filter on the frontend.

2023-03-10 08:41 UTC, tarhi-saad approved these changes
Thank you, @mikejolley, for the changes! Everything looks good! Let's 🚢 it!

2023-03-13 10:29 UTC, merged

2023-03-14 07:38 UTC, PanosSynetos commented
Thank you @mikejolley !

2023-04-15 01:00 UTC, senadir commented
This broke checking out with COD if COD is condtional.

2023-04-17 10:11 UTC, mikejolley commented
@senadir is there an issue logged? Assuming the conditional is on the server, it should allow us to return the updated list of payment methods in the cart response...

2023-04-17 10:40 UTC, senadir commented
Sorry I didn’t expand much in this, I will create and issue later. It happens on the schema generation level, cod is not in the payment method enum so it’s rejected by Store API