Fix total shipping display info when no shipping are available
woocommerce/woocommerce-gutenberg-products-block pull request #8819
Opened 2023-03-22 11:07 UTC by tarhi-saad

When there is no shipping method, local pickup won't remove the pickup cost from the Cart totals.

Fixes #8206

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|        |       |

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Enable local pickup with pickup price
2. Remove the shipping methods from the WC settings
3. Go to the Checkout block and select the local pickup option
4. Notice the local pickup price from the totals will get removed when you select the shipping option, and display: `Calculated during checkout`

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

### Changelog

> Add suggested changelog entry here.

2023-03-28 05:57 UTC, nielslange approved these changes
Thanks for working on this, @tarhi-saad! I've successfully tested the change. While reviewing, I saw that the buyer's notice `No shipping options available` could be improved:

<img width="279" alt="Screenshot 2023-03-28 at 12 54 42" src="https://user-images.githubusercontent.com/3323310/228141480-bbe82999-0863-42d6-9c20-b55f47a0948c.png">

I then recalled that @mikejolley is currently working on [Feature Branch: Updated Buyer Notices](https://github.com/woocommerce/woocommerce-blocks/pull/8659). Once that PR has been merged, I believe we should improve the  `No shipping options available` message in the sidebar. But that's another story. For now, let's ⛴ this PR.

2023-03-30 00:45 UTC, tarhi-saad commented
Hello @tarunvijwani, @nielslange! We finally fixed a conflict me and @tarunvijwani between this PR and #8141. I added additional testing instructions to ensure we didn't introduce regression! Feel free to merge this PR if you think everything works well!

2023-04-04 04:23 UTC, nielslange commented
Case 1 / Step 5 states:

> Select `Shipping` under the `Shipping Method` section. Ensure `No shipping options available` is displayed under `shipping` in the `Order Summary` Block

Despite not having any shipping zones defined, I still see `Local Pickup` under `Shipping` in the `Order Summary` Block. 

<img width="2877" alt="Screen Shot 2023-04-04 at 11 21 09" src="https://user-images.githubusercontent.com/3323310/229686241-ce95a588-b10f-4173-9102-88b3127e73c8.png">

> The order of the test cases is important!

Given that the first test case failed, I've stopped the review, as other tests might also fail, given that _"The order of the test cases is important"_.

2023-04-05 09:04 UTC, nielslange reviewed
See https://github.com/woocommerce/woocommerce-blocks/pull/8819#issuecomment-1495327006

2023-04-07 15:28 UTC, opr approved these changes
I was unable to replicate the bug Niels shared.

I have Local Pickup enabled, I have no shipping zones or fallback rates configured. On the Checkout block I never see the local pickup rates unless I specifically select the local pickup button.

I found a bug in the code where the `pickup_location` string was used, however third-party methods supporting `local-pickup` will not be considered in this, I pushed an update to fix this.

We should also add unit tests for that method.

I will merge this.

2023-04-07 15:28 UTC, opr commented on assets/js/base/components/cart-checkout/totals/shipping/utils.ts
> +						shippingRate.method_id !== 'pickup_location'
This will not work for third-party collectible rates, we need to check if the method ID is in `collectableRateIds` from the server.

2023-04-10 13:31 UTC, opr commented
Bumping to 10.1.0 after p1681129771372729/1681128388.500929-slack-C02UBB1EPEF

2023-04-11 06:56 UTC, nielslange approved these changes
I reviewed the PR again and now all testing steps worked as expected. 

@opr I see that both you and @tarhi-saad applied various changes yesterday. Given that @tarhi-saad will be AFK until April 28, shall we merge this PR, if all testing steps are passing for you as well?

2023-04-14 17:35 UTC, tarunvijwani requested changes
I'm little hesitant in approving the PR as this still have shipping total error. 
If I select the shipping and don't enter the valid address, it calculates the local pickup cost but doesn't display in the order summary. 

| Shipping | Local pickup |
|---|---|
|![image](https://user-images.githubusercontent.com/11503784/232116539-5281d89f-d74b-4a08-ac7b-c587a79ff40e.png)| ![image](https://user-images.githubusercontent.com/11503784/232116668-08a09dd2-1772-4c12-a8ba-8f5b3003e7bf.png)|

2023-04-22 15:04 UTC, opr commented
The issue here is that if "Shipping" is selected while an address is not entered, there are no "shipping" rates, so it falls back to the local pickup option, which in this case is $4. This is used to calculate taxes, too.

To fix this, we would need to get the taxes and the current shipping price and manipulate the totals in-place to show the correct value. I don't think there's a way we can correct this on the server, because as far as the server is concerned, there is no difference between a local pickup rate and a shippable rate. We would then need to remove the correct amounts from each tax line, if it's being displayed in an itemized list. This is diffficult as we'd need to know what percent each tax line applies, and subtract the shipping tax from each one.

I think it will be _very_ hard to get the correct totals to display when "shipping" is selected but before the address, and with little benefit.

I propose we add a notice saying totals will be calculated when an address is entered.
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/5656702/233792244-e6f6080b-6150-4806-bc82-8d65d58f1e0d.png">

2023-04-24 14:19 UTC, thealexandrelara commented
WooCommerce Blocks 10.1.0 will be released soon. I'm bumping this PR to the next milestone

2023-04-27 13:59 UTC, opr commented
@tarunvijwani please could you re-review this? @nielslange please also feel free to give it another look, it incorporates the changes we made in #9171

2023-04-28 03:31 UTC, nielslange approved these changes
I've successfully tested the PR again, so I pre-approved the PR, but I struggled a bit with the testing instructions, see below:

I wonder if we should refine the testing instructions for better efficiency. The complexity arising from the statement, "The order of the test cases is important!" has made testing more challenging. Each step requires recalling the previous ones. For instance, Steps 2 and 4 of Case 4, as well as Step 1 of Case 5, direct users to revisit steps from prior cases. I found this constant back-and-forth mentally exhausting, reducing my ability to effectively conduct the review. In my view, it would be more efficient if test cases were designed to be independent of one another, allowing for streamlined and focused testing. What are your thought on that, @opr?

2023-05-01 09:29 UTC, tarunvijwani reviewed
@opr Thank you for adding the notice to the checkout summary. It helps a lot to understand that shipping will be recalculated and avoid confusion. However, I noticed two bugs now:

1. My entered email address get removed automatically when I start entering the shipping address.  
2. Even after adding the correct address, if I select local pickup and select back shipping. It displays the notice, which is not valid anymore. 

Here is the screen recording for your reference: 


https://user-images.githubusercontent.com/11503784/235434644-d8f3aa4c-341d-4572-a9f1-2a7484dd065f.mov

2023-05-01 09:41 UTC, opr commented
@tarunvijwani thanks, are you able to reproduce the email issue on trunk? I don't see how that could be caused by this PR.

How long did you wait after switching method, it looks like the `select-shipping-rate` request to the server did not complete. This is on the basis that the selected method is still "Pickup" at the end of your screenshare.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/5656702/235436195-25d3cccb-1291-4b25-9329-cd33197b01ba.png">

2023-05-01 16:08 UTC, tarunvijwani commented
>thanks, are you able to reproduce the email issue on trunk? I don't see how that could be caused by this PR

No, I am unable to reproduce it now. It could be a glitch as I'm not able to reproduce it on this branch as well.

>How long did you wait after switching method, it looks like the select-shipping-rate request to the server did not complete. This is on the basis that the selected method is still "Pickup" at the end of your screenshare.

@opr I tried again, I'm getting the same results even if I wait for a couple of minutes.

2023-05-02 07:53 UTC, opr commented
Hi @tarunvijwani ok, great well I have not reproduced that and since you can't either I don't think it's anything too problematic, we can keep an eye on this and see if it happens again - the cause will be the server sending a new cart for some reason with the email address missing from the billing address. 

As for the second part, I am not able to reproduce that

https://www.loom.com/share/17fc62458d1b41bcb81686f8d0ab29cb

Would you be able to set up a JN site and have a completely fresh install using the testing zip file?

2023-05-02 09:56 UTC, tarunvijwani commented
@opr Here is the JN site: https://mean-platypus.jurassic.ninja/checkout/
I can reproduce both issues on it. 
Steps to reproduce:
1. Add a product to the cart. 
2. Go to the checkout page. 
3. Select the shipping option. 
4. Confirm the notice appears in the Checkout summary.  
5. Enter your email address. 
6. Start entering the address. 
7. Notice email address entered is cleared, and a validation error appears. 
8. After entering the address, enter the email address. 
9. Confirm the notice in the checkout summary block no longer appears. 
10. Select local pickup. 
11. Select shipping again. 
12. Notice appears again in the checkout summary block even with the valid address.

2023-05-02 12:31 UTC, tarunvijwani commented
Created a ticket for email address issue: https://github.com/woocommerce/woocommerce-blocks/issues/9321

2023-05-08 06:39 UTC, kmanijak commented
PR bumped to the next milestone (10.3.0)

2023-05-08 17:48 UTC, tarunvijwani approved these changes
Thank you for fixing the errors. I have added a note in the PR description that notice will appear for a few seconds until we receive the server's response, even with the valid shipping address, when we change the shipping method.

2023-05-22 11:32 UTC, mikejolley commented
Bumping to 10.4.0.

2023-05-23 16:31 UTC, ralucaStan commented
@tarhi-saad what is preventing this PR from getting merged?

2023-05-23 16:33 UTC, opr commented
> @tarhi-saad what is preventing this PR from getting merged?

Since I worked on this a lot during Saad's AFK, I asked if he could do one final review/test before merging.

2023-05-25 05:08 UTC, tarhi-saad commented
Everything works as expected!

2023-05-25 05:31 UTC, merged