Mini Cart block: exclude already-enqueued scripts from scripts to lazy load
woocommerce/woocommerce-gutenberg-products-block pull request #8979
Opened 2023-04-06 14:13 UTC by Aljullu

The Mini Cart block registers an object (`scripts_to_lazy_load`) where we store all scripts that we need to lazy load. This PR makes it a bit more clever, so if a script is already enqueued (ie: another block has enqueued it), it will not be added to the scripts to lazy load.

### Testing

#### User Facing Testing

1. Add the Mini Cart block to the header of your site (via Appearance > Editor).
2. Create a post or page with the All Products block.
3. Create another post or page without any WC Blocks.
4. In the frontend, visit both pages and in the browser console (<kbd>F12</kbd>) print these values: `Object.keys( wcBlocksMiniCartFrontendDependencies ).length` and `wcBlocksMiniCartFrontendDependencies['wp-i18n']`.
5. Verify in the All Products block page: `wcBlocksMiniCartFrontendDependencies['wp-i18n']` is defined.
6. Verify in the page with no blocks: `wcBlocksMiniCartFrontendDependencies['wp-i18n']` is undefined and `Object.keys( wcBlocksMiniCartFrontendDependencies ).length` is smaller.
7. Verify in both pages you can interact with the Mini Cart block: open the drawer, change the items quantity, remove items from the cart, etc.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Exclude already-enqueued scripts from scripts to lazy load in the Mini Cart block

2023-04-07 06:29 UTC, imanish003 requested changes
Hi @Aljullu,
The code changes look good to me, but while following testing instructions, I am seeing:
- All Products block page: wcBlocksMiniCartFrontendDependencies['wp-i18n'] is undefined.
- Page with no blocks: wcBlocksMiniCartFrontendDependencies['wp-i18n'] is defined

May be I am doing something wrong while testing? 🤷🏻‍♂️

https://user-images.githubusercontent.com/16707866/230553941-2c01685c-caf2-46f4-ad14-8467e1654197.mov

2023-04-13 10:13 UTC, Aljullu commented
> Maybe I am doing something wrong while testing on my local setup? 🤷🏻‍♂️

My bad, that was me writing the testing steps incorrectly. :man_facepalming:  What you can reproduce is the expected behavior:

* `wcBlocksMiniCartFrontendDependencies['wp-i18n']` is undefined in the All Products page because that script has already been loaded by the All Products block, thus, it doesn't need to be lazy-loaded.
* `wcBlocksMiniCartFrontendDependencies['wp-i18n']` is defined in the no-block page because that script hasn't been loaded, so it needs to be lazy-loaded for the Mini Cart block.

I updated the testing steps accordingly. Sorry for the confusion! :pray:

2023-04-13 10:28 UTC, imanish003 commented
@Aljullu, no problem. Thanks for the clarification and updating the testing steps. I'm going to approve it now since I've already tested it 🙂

2023-04-13 10:29 UTC, imanish003 approved these changes
LGTM 🚀🙌🏻

2023-04-17 11:09 UTC, merged