fix/8129: remove rounding the caused issue with UI
woocommerce/woocommerce-gutenberg-products-block pull request #9118
Opened 2023-04-19 13:47 UTC by Sidsector9

Fixes #8129 

Thie PR removes the rounding of `low` and `high` values that caused issue with the range slider's UI.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

#### Before

<img width="2336" alt="Screenshot 2023-04-19 at 7 15 18 PM" src="https://user-images.githubusercontent.com/17757960/233094659-27a2a274-a442-43c4-926f-94769ba77e95.png">

#### After

<img width="2355" alt="Screenshot 2023-04-19 at 7 15 54 PM" src="https://user-images.githubusercontent.com/17757960/233094845-ace5aca0-d8d4-4db2-9f91-f088180da3ff.png">

### Testing

Please follow the steps from the issue for testing.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

### Changelog

> Add suggested changelog entry here.

2023-04-19 17:29 UTC, nefeline requested changes
Hi there @Sidsector9 !

Thank you so much for this contribution! I ran the tests and confirmed the problem is now solved.

Before:

<img width="676" alt="Screenshot 2023-04-19 at 13 12 45" src="https://user-images.githubusercontent.com/15730971/233152394-4c687f02-2750-4ca6-bf78-5f5f247dbb6b.png">

After: 

<img width="674" alt="Screenshot 2023-04-19 at 13 13 29" src="https://user-images.githubusercontent.com/15730971/233152451-d6397afb-2d1b-42c9-9115-a670e6f0a08a.png">

My only recommendation is to fix the JS lint errors. After that, we should be good to go! 🚢 

As a side note, it is possible to run the lint tests locally as well via `npm run lint:js`

2023-04-19 17:29 UTC, nefeline commented on assets/js/base/components/price-slider/index.tsx
> +		);
```suggestion
		const low =
			100 *
			( ( minPrice - minConstraint ) /
				( maxConstraint - minConstraint ) );
```

2023-04-19 17:29 UTC, nefeline commented on assets/js/base/components/price-slider/index.tsx
> +		);
```suggestion
		const high =
			100 *
			( ( maxPrice - minConstraint ) /
				( maxConstraint - minConstraint ) );
```

2023-04-20 00:21 UTC, nielslange reviewed
Hallo @Sidsector9 👋 Thank you so much for your contribution. Besides the changes that @nefeline suggested, could you add testing steps to the PR description? This will help a lot in the future when this PR will get merged into the WooCommerce core. 😀

2023-04-20 05:38 UTC, Sidsector9 commented
@nielslange @nefeline both feedbacks are addressed.

2023-04-20 11:40 UTC, nefeline approved these changes
Thanks for addressing all feedback @Sidsector9 !

Even though the test instructions were listed on the issue, it is always a good practice to add them to the description of PRs to expedite work for the reviewers: thanks, @nielslange, for this excellent suggestion!

All tests are now passing successfully, so I'm going ahead and merging this PR.

Thanks again for contributing to Woo Blocks 🎉 !

2023-04-20 11:41 UTC, merged