[Patterns] Update button colors
woocommerce/woocommerce-gutenberg-products-block pull request #9467
Opened 2023-05-15 13:14 UTC by albarin

Fixes #

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|        |       |

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1.
2.
3.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

### Changelog

> Add suggested changelog entry here.

2023-05-15 13:56 UTC, roykho requested changes
All the patterns tested as expected except the `Footer with 3 menus`. That one does not show "black button with white text".

![XJbAZ4.png](https://github.com/woocommerce/woocommerce-blocks/assets/2132595/71cf3cc7-45a0-4f48-87f8-6e251e7d058f)

2023-05-15 14:31 UTC, albarin commented
> All the patterns tested as expected except the `Footer with 3 menus`. That one does not show "black button with white text".
> 
> ![XJbAZ4.png](https://user-images.githubusercontent.com/2132595/238371430-71cf3cc7-45a0-4f48-87f8-6e251e7d058f.png)

Sorry, wrong testing instructions for that one. I fixed them in the PR description. For the `Footer with 3 menus` the change was making the search button background white.

2023-05-15 14:55 UTC, roykho commented on patterns/footer-with-3-menus.php
> +						echo wp_kses( __( 'Powered by %1$s with %2$s', 'woo-gutenberg-products-block' ), '<a href="https://wordpress.org">WordPress</a>', '<a href="https://woocommerce.com">WooCommerce</a>', array() );
I think here you're wanting to use `echo sprintf( esc_html__( 'Powered by %1$s with %2$s', 'woo-gutenberg-products-block' ), '<a href="https://wordpress.org">WordPress</a>', '<a href="https://woocommerce.com">WooCommerce</a>', array() );`

2023-05-16 09:05 UTC, Aljullu reviewed
Sorry for being late to the discussion, but I wanted to mention that I think it's problematic to hard-code specific button colors to patterns that don't have a hard-coded background color. The issue is that it might cause low-contrast color combinations and that the pattern might look out of place.

For example, this is the `Featured Products 5-item grid` pattern added to the _Swiss_ variation of TT2:

`trunk` | This branch
--- | ---
![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/dd215ac1-0dc4-4aa5-a58a-49b3013ebeaa) | ![imatge](https://github.com/woocommerce/woocommerce-blocks/assets/3616980/415c6379-24c5-491c-9ec2-6f20d74b7c51)

IMO, `trunk` looks better than with the black button.

So from my point of view, we should only hard-code text and button colors in patterns that have a custom background color (like `Hero Product 3 Split`). But in patterns that don't define a specific background color (like `Featured Products 5-item grid`), we should try to let default theme styles to be applied.

What do you think? I'm happy with whatever decision is taken, but wanted to share my thoughts in case somebody else thinks the same. :slightly_smiling_face:

2023-05-16 14:22 UTC, danielwrobert commented
> So from my point of view, we should only hard-code text and button colors in patterns that have a custom background color (like Hero Product 3 Split). But in patterns that don't define a specific background color (like Featured Products 5-item grid), we should try to let default theme styles to be applied.

I agree with this! Alternatively, we could always hard-code the text and background colors to match the design. The user can still adjust once inserted. I did this for the `Hero Product - Split` pattern.

That said, in that case the background was set as explicitly black in the design so it was a little more clear-cut than the examples you've listed. It depends on where we want to draw the line with how much flexibility to leave to the theme in cases where we have white background and black text.

cc @shaunandrews

2023-06-06 08:23 UTC, albarin commented
I have updated this PR following the agreed rule of only hard-coding buttons colors if the background is explicitly set.

2023-06-06 16:54 UTC, danielwrobert approved these changes
LGTM, tests as described! 🚀 

TY for also updating the title to remove the `WooCommerce` prefix. 🙌

2023-06-07 08:10 UTC, merged