Combine country asset data to reduce the amount of data consumed by the cart and checkout blocks
woocommerce/woocommerce-gutenberg-products-block pull request #9552
Opened 2023-05-19 14:16 UTC by mikejolley

I reviewed the `wcSettings` usage and it seems most things are required and loaded by the blocks consuming them. The main exception was the volume of country, state, country locale data which lead to lots of duplication (while both are needed by blocks and inner blocks of cart and checkout).

By combining states, locales, billing and shipping into a single property, I was able to cut the document size from around 188kb to 167kb, so a saving of around 11%.

Fixes #8555

### Testing

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [x] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Go to the block based cart
2. Open the shipping calculator and enter your address, confirming state + country fields are working
3. Go to the block based checkout
4. Fill out the shipping and address forms separately,, confirming the country and state fields populate correctly. Ensure an address with states, such as the US, is used at least once. 
5. In WooCommerce > Settings and change "Shipping location(s)" to specific locations. Limit to a few countries
6. Go back to checkout and confirm the limitations are in place in the shipping address form

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

Smaller document size.

### Changelog

> Reduced the amount of settings data consumed by the cart and checkout blocks

2023-05-25 11:25 UTC, opr requested changes
Tested and it works well, code looks great too, but I added a suggestion for a TS change, it should resolve the TS error mentioned.

There's also a failing PHP unit test, not sure what the cause is but couldn't get my unit tests running locally to investigate further.

2023-05-25 11:25 UTC, opr commented on assets/js/settings/blocks/constants.ts
> +	locale: CountryAddressFields;
Should this be `Record< string, LocaleSpecificAddressField >`? 

I also think the type of [`LocaleSpecificAddressField`](https://github.com/woocommerce/woocommerce-blocks/blob/f53833a86d07fd502785c96f1021cf8bfd8c179d/assets/js/settings/shared/default-address-fields.ts#L23) should be updated to:

```ts
export interface LocaleSpecificAddressField extends Partial< AddressField > {
	priority?: number | undefined;
}
```

because not all fields are required there. [It causes a TS error here](https://github.com/woocommerce/woocommerce-blocks/blob/6e78c7c373f42d74dca45e24f29b1aaf59455651/assets/js/base/components/cart-checkout/address-form/prepare-address-fields.ts#L81).

2023-05-25 11:25 UTC, opr commented on assets/js/settings/blocks/constants.ts
> +	locale: CountryAddressFields;
```suggestion
	locale: Record< string, LocaleSpecificAddressField >;
```

2023-05-30 15:18 UTC, mikejolley commented
Tests are passing 👍🏻

2023-05-30 15:34 UTC, opr approved these changes
Nice work, thanks for fixing the test! Let's merge.

2023-05-31 09:30 UTC, merged