Hide "collection from" text when a location has an incomplete address.
woocommerce/woocommerce-gutenberg-products-block pull request #9808
Opened 2023-06-13 11:57 UTC by mikejolley

Hides the "collection from <address>" section when a local pickup location has no defined address. This prevents repetition of the local pickup rate name, or nonsensical text. 

Fixes #9789

#### User Facing Testing

1. Go to WooCommerce > Settings > Shipping > Local Pickup. Create 2 pickup locations—one should have a full address/pickup location, and one should have no address like so:

![Screenshot 2023-06-13 at 12 48 21](https://github.com/woocommerce/woocommerce-blocks/assets/90977/2dcd6ed7-08ec-4351-8f30-1d6b887eec9d)

2. Add items to your cart and go to checkout.
3. Select Local Pickup
4. Select the pickup location with an address. it should show "collection from" like so:

![Screenshot 2023-06-13 at 12 50 13](https://github.com/woocommerce/woocommerce-blocks/assets/90977/8bd1fd97-ae82-40f8-a4cb-11b5a705488c)

5. Select the pickup location with no address. It should not show the collection from section:
 
![Screenshot 2023-06-13 at 12 50 19](https://github.com/woocommerce/woocommerce-blocks/assets/90977/80dda09b-e99a-4d00-81fb-b3916dddeb9a)

6. Place the order and check the confirmation displays correctly without an address also:

![Screenshot 2023-06-13 at 12 56 19](https://github.com/woocommerce/woocommerce-blocks/assets/90977/7aacfa0d-0ff7-408f-854e-01bfa59da502)

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Local Pickup - Only show collection address when set.

2023-06-16 07:42 UTC, tarunvijwani reviewed
This isn't working for me. Am I missing anything?

https://github.com/woocommerce/woocommerce-blocks/assets/11503784/da89ee54-ca5e-402f-b947-f9ba72a9d6fc

2023-06-16 10:56 UTC, mikejolley commented
@tarunvijwani thats the trunk behaviour. I just retested and its fine in this branch. Suggest rebuilding and clearing caches, or someone else from @woocommerce/rubik can try it.

2023-06-18 15:55 UTC, nielslange commented
> @tarunvijwani thats the trunk behaviour. I just retested and its fine in this branch. Suggest rebuilding and clearing caches, or someone else from @woocommerce/rubik can try it.

@mikejolley I'm getting the same result as @tarunvijwani. To ensure that I'm starting with a fresh environment, I ran the following commands:

```sh
rm composer.lock
rm package-lock.json
rm -rf node_modules
rm -rf vendor
nvm use
composer i
npm i
npm run build
```

<table>
<tr>
<td valign="top">Local Pickup address:
<br><br>

<img width="583" alt="Screenshot 2023-06-18 at 17 52 06" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/406d3b2c-bdb2-4f64-b42d-8952a29ff091">
</td>
<td valign="top">Cart block:
<br><br>

<img width="834" alt="Screenshot 2023-06-18 at 17 53 29" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/fea75021-a254-468b-b755-03765d13cdd6">
</td>
<td valign="top">Checkout block:
<br><br>

<img width="847" alt="Screenshot 2023-06-18 at 17 54 12" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/9ef910aa-f0cf-4c82-b406-10ed579efa26">
</td>
</tr>
</table>

2023-06-21 11:56 UTC, tarunvijwani requested changes
You were right! I was testing it on WooCommerce 7.9. Forgot to enable the WC Blocks plugin after the release.😃
It works as expected. Great work! 🎉 
I left one suggestion for the countries where state is an optional field. Let me know your thoughts about it.

2023-06-21 11:56 UTC, tarunvijwani commented on src/Shipping/PickupLocation.php
> +				$has_pickup_address = ! empty( $location['address'] ) && ! empty( $location['address']['city'] ) && ! empty( $location['address']['state'] ) && ! empty( $location['address']['country'] );
Some countries like UAE don't have a state. This condition will hide the `Collection from` for them as well. 
I feel we should have helper function that will check the address completeness based on the country. 
We have one similar function: `isAddressComplete` in utils. Do you think we should utilize it here?
You can test that with the below address:
![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/46d36eae-0994-4ff8-bd2c-65ce45eac30e)

2023-06-26 16:58 UTC, opr requested changes
Code wise it looks great, Tarun's suggestion is valid though! We should avoid checking for fields that may are not required for that locale.

What do you think of this?

```php
$required_address_fields_for_country = [];
if ( ! empty( $location['address']['country'] ) ) {
	$shipping_address_fields = wc()->countries->get_address_fields( $location['address']['country'], 'shipping_' );
	foreach ( $shipping_address_fields as $field_name => $field ) {
		if ( true === $field['required'] ) {
			$required_address_fields_for_country[] = str_replace( 'shipping_', '', $field_name );
		}
	}
}

$has_pickup_address = ! empty( $location['address'] ) &&
	( ! empty( $location['address']['city'] ) || ! in_array( 'city', $required_address_fields_for_country, true ) ) &&
	( ! empty( $location['address']['state'] ) || ! in_array( 'state', $required_address_fields_for_country, true ) ) &&
	( ! empty( $location['address']['country'] ) );
```

2023-06-28 09:05 UTC, mikejolley commented
I added a helper in https://github.com/woocommerce/woocommerce-blocks/pull/9808/commits/b4bfc94fbfd58a319b13b66058388bd6dd2d8113

2023-06-28 09:27 UTC, opr approved these changes
That helper function is a much cleaner way of doing it than I suggested, nice one!

Do you think we should add tests for it? We could add an issue for this and write them later.

2023-06-28 11:58 UTC, tarunvijwani requested changes
Thank you for updating the code. It seems it still returning null for UAE address. 

![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/ae33e332-03a4-4886-a69a-7cfc1e095c97)


The variable $country_address_fields is returning the correct data though:

| Address | country_address_fields value |
|---|---|
|![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/3bd5728d-0dae-48b3-97da-66b8b698ddf7)|![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/ee555058-f6eb-4219-8d15-c2d17153ad76)|

2023-06-28 12:09 UTC, mikejolley commented
@tarunvijwani missed a check to see if the field was included in address_fields. Try now.

2023-06-28 12:17 UTC, tarunvijwani approved these changes
Works great! Thank you for the changes! 🎉

2023-07-03 09:10 UTC, merged