Return null or object for ImageAttachmentSchema response
woocommerce/woocommerce-gutenberg-products-block pull request #9962
Opened 2023-06-22 14:05 UTC by nielslange

Fixes #9908

In #9908, @whywilson reported:
> _"The return image of product categories should be null or object, but on some categories, it is an empty array. The same issues happened on the image of /wp-json/wc/store/products/categories request."_
### Testing

#### User Facing Testing

1. Make sure to have two test product categories. One test product category should have an image, the other one should not have an image.
2. Open `[YOUR-URL]/wp-json/wc/store/products/categories` and replace `[YOUR-URL]` with the URL of your test site.
3. Alternatively, open `[YOUR-URL]/wp-json/wc/store/products/categories/[ID]` and replace `[ID]` with the ID of the test product category.
4. Verify that the response for the test product category without image is
```json
{
	...
	"image": null,
	...
}
```
5. Verify that the response for the test product category with image is
```json
{
   ...
   "images": { ... },
   ...
}
```

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix: Return null or object for ImageAttachmentSchema response.

2023-06-22 14:41 UTC, mikejolley requested changes
The docblock needs changing but yes, this is what was needed.

Can we ensure that all consumers of these endpoints continue to function before merging. I don't think it will break any backwards compatibility because it would I think be treated as an object anyway, but let's be certain.

Test wise, you could test the response for the cart endpoint and ensure that images are either null or received as an object with said properties. This would be added to the PHP test suite.

2023-06-22 14:41 UTC, mikejolley commented on src/StoreApi/Schemas/V1/ImageAttachmentSchema.php
> +		return (object) [
Make sure to update the function return type to match—it still states array.

2023-06-22 15:26 UTC, nielslange commented
> The docblock needs changing but yes, this is what was needed.

Thanks for your review, @mikejolley. I just added the `docblock` that you mentioned in your review. Somehow, my reply was added as a review. When deleting it, to reply to your review comment, it accidentally also deleted your review comment. 🙈 Nevertheless, your feedback has been adjusted.

> Can we ensure that all consumers of these endpoints continue to function before merging. I don't think it will break any backwards compatibility because it would I think be treated as an object anyway, but let's be certain.
> 
> Test wise, you could test the response for the cart endpoint and ensure that images are either null or received as an object with said properties. This would be added to the PHP test suite.

Thanks for pointing this out. I'll create additional test cases to guarantee that this change will remain backwards compatible.

2023-07-11 09:43 UTC, mikejolley approved these changes
Thanks for adding the tests 🥇

2023-07-11 09:46 UTC, opr approved these changes
Looks good to me!

2023-07-11 11:43 UTC, nielslange commented
Thanks for your reviews, @mikejolley and @opr! 🙌

2023-07-11 11:43 UTC, merged